<?php
$batchNum = 8;
$isLastBatch = false;
$batchSongs = array (
  0 => 
  array (
    'id' => 2554,
    'spotify_id' => '7ucwhjWSGTEh5e18h6WFER',
    'title' => 'Milikmu Selalu',
    'artist' => 'Andien',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27329c0c626336ca4374aac48e0',
    'meaning' => 'Lagu "Milikmu Selalu" karya Andien mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/7ucwhjWSGTEh5e18h6WFER',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:09',
  ),
  1 => 
  array (
    'id' => 2565,
    'spotify_id' => '4G0I9EAPTKcazhjeFMSazd',
    'title' => 'Simpan Saja',
    'artist' => 'Ecoutez',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e26c269711c86c07e7d6bca3',
    'meaning' => 'Keputusan untuk memendam perasaan cinta secara rahasia demi menjaga hubungan dan menghindari kekecewaan.',
    'spotify_url' => 'https://open.spotify.com/track/4G0I9EAPTKcazhjeFMSazd',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:10',
  ),
  2 => 
  array (
    'id' => 2566,
    'spotify_id' => '7s0E1B1ZiyOs6tFl1fKTq2',
    'title' => 'Simpan Sampah (feat. Hawa)',
    'artist' => 'Panji Sakti, Hawa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736c960a23f00ff4d2adb7051e',
    'meaning' => 'Lagu "Simpan Sampah (feat. Hawa)" karya Panji Sakti, Hawa mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/7s0E1B1ZiyOs6tFl1fKTq2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:10',
  ),
  3 => 
  array (
    'id' => 2574,
    'spotify_id' => '4QhUPMxHOvY9aLr4NBW3Pu',
    'title' => 'Jelita',
    'artist' => 'Humania',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27373d20ff070f673c3f9f79732',
    'meaning' => 'Karya "Jelita" oleh Humania melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4QhUPMxHOvY9aLr4NBW3Pu',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:10',
  ),
  4 => 
  array (
    'id' => 2576,
    'spotify_id' => '6ZyHtGekIRu905FklcnDxl',
    'title' => 'Simpan Dihati Saja',
    'artist' => 'Bunga Citra Lestari',
    'cover_url' => 'https://i.scdn.co/image/ef1449c90805ed3487f7fe023fecddd503614aa9',
    'meaning' => 'Lagu "Simpan Dihati Saja" karya Bunga Citra Lestari mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/6ZyHtGekIRu905FklcnDxl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:10',
  ),
  5 => 
  array (
    'id' => 2608,
    'spotify_id' => '5y2ijHECwFYWqcAHKTZgzD',
    'title' => 'Risk It All',
    'artist' => 'Bruno Mars',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733eb8dc748f7efb1470f74395',
    'meaning' => 'Karya "Risk It All" oleh Bruno Mars melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5y2ijHECwFYWqcAHKTZgzD',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  6 => 
  array (
    'id' => 2611,
    'spotify_id' => '4DrJqdZgPBHoMNVG5iOLlG',
    'title' => 'Bersenja Gurau',
    'artist' => 'Raim Laode',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a9d1f9b5d3275b0625e13e79',
    'meaning' => 'Lagu "Bersenja Gurau" karya Raim Laode membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/4DrJqdZgPBHoMNVG5iOLlG',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  7 => 
  array (
    'id' => 2612,
    'spotify_id' => '2fCwv2ppU5nTRTckomIGsd',
    'title' => 'REDRED',
    'artist' => 'CORTIS',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27324ace1518851b27e9983f739',
    'meaning' => 'Karya "REDRED" oleh CORTIS melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2fCwv2ppU5nTRTckomIGsd',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  8 => 
  array (
    'id' => 2613,
    'spotify_id' => '3oTuTpF1F3A7rEC6RKsMRz',
    'title' => 'Raindance (feat. Tems)',
    'artist' => 'Dave, Tems',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273fecaa7826bb0cbe139a8cb83',
    'meaning' => 'Lagu "Raindance (feat. Tems)" karya Dave, Tems menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/3oTuTpF1F3A7rEC6RKsMRz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  9 => 
  array (
    'id' => 2614,
    'spotify_id' => '3fL35dqYnnabdEp8Sln0lf',
    'title' => 'rollerblade',
    'artist' => 'no na',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273211f708536bf8c46dbd2b309',
    'meaning' => 'Karya "rollerblade" oleh no na melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3fL35dqYnnabdEp8Sln0lf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  10 => 
  array (
    'id' => 2616,
    'spotify_id' => '670sqeIKIxTu0DweRjnjKt',
    'title' => 'Rabun Jauh',
    'artist' => 'Bernadya',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d06c6c5a80cadc718d09fdcb',
    'meaning' => 'Lagu "Rabun Jauh" karya Bernadya membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/670sqeIKIxTu0DweRjnjKt',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  11 => 
  array (
    'id' => 2617,
    'spotify_id' => '2uXlHCUbq9OMUwx3hrk06o',
    'title' => 'Riptide',
    'artist' => 'Vance Joy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27305d081cbdc2f67d37a364d63',
    'meaning' => 'Karya "Riptide" oleh Vance Joy melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2uXlHCUbq9OMUwx3hrk06o',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  12 => 
  array (
    'id' => 2620,
    'spotify_id' => '1gD4PyWw2BDZLtrZqTkO3Y',
    'title' => 'Rindiani',
    'artist' => 'Slam',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c48e636c3da7c57161292b48',
    'meaning' => 'Karya "Rindiani" oleh Slam melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1gD4PyWw2BDZLtrZqTkO3Y',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  13 => 
  array (
    'id' => 2621,
    'spotify_id' => '0pDVCQpK0jAjhWYrzrz91x',
    'title' => 'Risalah Hati',
    'artist' => 'Pamungkas',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e15ac0d90ad533c2dc21008a',
    'meaning' => 'Karya "Risalah Hati" oleh Pamungkas melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0pDVCQpK0jAjhWYrzrz91x',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  14 => 
  array (
    'id' => 2622,
    'spotify_id' => '7yq4Qj7cqayVTp3FF9CWbm',
    'title' => 'Riptide',
    'artist' => 'Vance Joy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d3ce97395ff522b0d70c1094',
    'meaning' => 'Karya "Riptide" oleh Vance Joy melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7yq4Qj7cqayVTp3FF9CWbm',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  15 => 
  array (
    'id' => 2623,
    'spotify_id' => '1pnYULGLMdIJCGeDnNmka3',
    'title' => 'Rindu Tebal',
    'artist' => 'Iwan Fals',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734c3c17b4babd8a1e0a98ea5f',
    'meaning' => 'Lagu "Rindu Tebal" karya Iwan Fals membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/1pnYULGLMdIJCGeDnNmka3',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  16 => 
  array (
    'id' => 2624,
    'spotify_id' => '4rqQuXXJWAhIyexWnZvKE3',
    'title' => 'Rindu Sendiri (Dilan 1990)',
    'artist' => 'Iqbaal Ramadhan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ea46fea516653611ad188d11',
    'meaning' => 'Lagu "Rindu Sendiri (Dilan 1990)" karya Iqbaal Ramadhan membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/4rqQuXXJWAhIyexWnZvKE3',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  17 => 
  array (
    'id' => 2625,
    'spotify_id' => '0cc9lgdfHqeS8t9BzbFFmj',
    'title' => 'Risalah Hati',
    'artist' => 'Dewa',
    'cover_url' => 'https://i.scdn.co/image/64825eca60656397ee6133105402d94df84af353',
    'meaning' => 'Karya "Risalah Hati" oleh Dewa melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0cc9lgdfHqeS8t9BzbFFmj',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  18 => 
  array (
    'id' => 2627,
    'spotify_id' => '2xql0pid3EUwW38AsywxhV',
    'title' => 'Reflections',
    'artist' => 'The Neighbourhood',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739b6ac98a52f62d5cb473da40',
    'meaning' => 'Karya "Reflections" oleh The Neighbourhood melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2xql0pid3EUwW38AsywxhV',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  19 => 
  array (
    'id' => 2628,
    'spotify_id' => '5gpqDeNLrBTbT5x1RUOxbP',
    'title' => 'Radja',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273eb02d122994e3dbc33ffc7b0',
    'meaning' => 'Karya "Radja" oleh Rif melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5gpqDeNLrBTbT5x1RUOxbP',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  20 => 
  array (
    'id' => 2629,
    'spotify_id' => '6zIf9TLUuwVRwuPvY1Qpid',
    'title' => 'Lo Toe Ye',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ff39b0770a41f35a1dd6e966',
    'meaning' => 'Karya "Lo Toe Ye" oleh Rif melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6zIf9TLUuwVRwuPvY1Qpid',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  21 => 
  array (
    'id' => 2630,
    'spotify_id' => '0rby5eEWJ8Z1yCvkrGzemq',
    'title' => 'Bunga',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273eb02d122994e3dbc33ffc7b0',
    'meaning' => 'Simbol cinta abadi yang tidak akan pernah layu dan selalu mekar melintasi batas waktu.',
    'spotify_url' => 'https://open.spotify.com/track/0rby5eEWJ8Z1yCvkrGzemq',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  22 => 
  array (
    'id' => 2631,
    'spotify_id' => '64kzvA5vFdnTMwgAtNZvAC',
    'title' => 'Cinta Adalah...',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27312fef68c4c16993c1f66dccc',
    'meaning' => 'Lagu "Cinta Adalah..." karya Rif mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/64kzvA5vFdnTMwgAtNZvAC',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  23 => 
  array (
    'id' => 2632,
    'spotify_id' => '0k4JxeUJOpORGNBOhHmFvX',
    'title' => 'Salah Jurusan',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27312fef68c4c16993c1f66dccc',
    'meaning' => 'Karya "Salah Jurusan" oleh Rif melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0k4JxeUJOpORGNBOhHmFvX',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  24 => 
  array (
    'id' => 2633,
    'spotify_id' => '5GOUQrOWk3jXMs3M7PXZ0e',
    'title' => 'Radja',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737ef5a6e034328eff8d72db3c',
    'meaning' => 'Karya "Radja" oleh Rif melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5GOUQrOWk3jXMs3M7PXZ0e',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  25 => 
  array (
    'id' => 2634,
    'spotify_id' => '4VU2aau8xAeANUvTCVuknc',
    'title' => 'Fight',
    'artist' => 'Rif',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736f1504470229aa03c0896e76',
    'meaning' => 'Karya "Fight" oleh Rif melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4VU2aau8xAeANUvTCVuknc',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  26 => 
  array (
    'id' => 2636,
    'spotify_id' => '5TXDeTFVRVY7Cvt0Dw4vWW',
    'title' => 'Revenge',
    'artist' => 'XXXTENTACION',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273203c89bd4391468eea4cc3f5',
    'meaning' => 'Karya "Revenge" oleh XXXTENTACION melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5TXDeTFVRVY7Cvt0Dw4vWW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  27 => 
  array (
    'id' => 2637,
    'spotify_id' => '3hhbDnFUb2bicI2df6VurK',
    'title' => 'River',
    'artist' => 'Leon Bridges',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733921e3e980d81e65f259cc78',
    'meaning' => 'Karya "River" oleh Leon Bridges melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3hhbDnFUb2bicI2df6VurK',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:42',
  ),
  28 => 
  array (
    'id' => 2669,
    'spotify_id' => '7pBzCp7qNLlsH6rzEFkSwN',
    'title' => 'FREAKED OUT',
    'artist' => 'Fat Papi, prodshushy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273dae2db6b9b0a2d5ef298075f',
    'meaning' => 'Karya "FREAKED OUT" oleh Fat Papi, prodshushy melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7pBzCp7qNLlsH6rzEFkSwN',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  29 => 
  array (
    'id' => 2670,
    'spotify_id' => '20ese6JGfEV2efwCzPuVqq',
    'title' => 'ONE - ENGLISH Version',
    'artist' => 'Lee Soo Young',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273030f940b55e6f8aa4a3eeb1c',
    'meaning' => 'Karya "ONE - ENGLISH Version" oleh Lee Soo Young melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/20ese6JGfEV2efwCzPuVqq',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  30 => 
  array (
    'id' => 2671,
    'spotify_id' => '1jwaf6CWAWUrbqAT5mrKrA',
    'title' => 'Cinta Melulu',
    'artist' => 'Efek Rumah Kaca',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27359eaf2f9fca6f4c449fc9fc0',
    'meaning' => 'Lagu "Cinta Melulu" karya Efek Rumah Kaca mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/1jwaf6CWAWUrbqAT5mrKrA',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  31 => 
  array (
    'id' => 2672,
    'spotify_id' => '1H5tV0SkvBqxGllQ3HEVSy',
    'title' => 'Reflection - From "Mulan"',
    'artist' => 'Yura Yunita, SIVIA, Agatha Pricilla, Nadin Amizah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27353ed01e5ef78749eee7b8668',
    'meaning' => 'Karya "Reflection - From "Mulan"" oleh Yura Yunita, SIVIA, Agatha Pricilla, Nadin Amizah melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1H5tV0SkvBqxGllQ3HEVSy',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  32 => 
  array (
    'id' => 2673,
    'spotify_id' => '3M0RfjqAJZ1f6qXJkP1Uej',
    'title' => 'Sebelah Mata',
    'artist' => 'Efek Rumah Kaca',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27359eaf2f9fca6f4c449fc9fc0',
    'meaning' => 'Karya "Sebelah Mata" oleh Efek Rumah Kaca melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3M0RfjqAJZ1f6qXJkP1Uej',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  33 => 
  array (
    'id' => 2674,
    'spotify_id' => '0H3I8PJh0mbJ5tSRleYywg',
    'title' => 'Kau dan Aku Menuju Ruang Hampa',
    'artist' => 'Efek Rumah Kaca',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730c0f7067fc2bb2ad9f288d7a',
    'meaning' => 'Permohonan maaf yang tulus dan keikhlasan dilupakan demi menghapus penderitaan kekasih akibat kesalahan diri.',
    'spotify_url' => 'https://open.spotify.com/track/0H3I8PJh0mbJ5tSRleYywg',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  34 => 
  array (
    'id' => 2675,
    'spotify_id' => '2OoS1aZFAFscH1cUiKlazH',
    'title' => 'Refuse / Resist',
    'artist' => 'Sepultura',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739c0b2d74cfb910735ca55317',
    'meaning' => 'Karya "Refuse / Resist" oleh Sepultura melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2OoS1aZFAFscH1cUiKlazH',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  35 => 
  array (
    'id' => 2676,
    'spotify_id' => '5uHCw6YJdAv3LO8boVPg9p',
    'title' => 'Refugee',
    'artist' => 'Jordan Sandhu, Kaptaan, ABY',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27318748e6908c3adf2aebb99f9',
    'meaning' => 'Permohonan maaf yang tulus dan keikhlasan dilupakan demi menghapus penderitaan kekasih akibat kesalahan diri.',
    'spotify_url' => 'https://open.spotify.com/track/5uHCw6YJdAv3LO8boVPg9p',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  36 => 
  array (
    'id' => 2677,
    'spotify_id' => '5ApQ5Kxc3XYDEnwM8dIOjA',
    'title' => 'Revia',
    'artist' => 'Ramses Ravi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ffa0035df92ed3ce136bbd6d',
    'meaning' => 'Karya "Revia" oleh Ramses Ravi melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5ApQ5Kxc3XYDEnwM8dIOjA',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:59:52',
  ),
  37 => 
  array (
    'id' => 2734,
    'spotify_id' => '7g4Ewuh8njWucqfwY7PdmR',
    'title' => 'Tunggal Eka',
    'artist' => 'Denny Caknan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730314e6ec7ebe1ce2013d5f7c',
    'meaning' => 'Karya "Tunggal Eka" oleh Denny Caknan melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7g4Ewuh8njWucqfwY7PdmR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  38 => 
  array (
    'id' => 2735,
    'spotify_id' => '6eLQXa6uk2EW8drsiKbABZ',
    'title' => 'TU SANCHO',
    'artist' => 'Fuerza Regida',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a2e90fbdec84b25e46573469',
    'meaning' => 'Karya "TU SANCHO" oleh Fuerza Regida melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6eLQXa6uk2EW8drsiKbABZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  39 => 
  array (
    'id' => 2736,
    'spotify_id' => '6uiQ0DqbXTBc8tl0AUKZkR',
    'title' => 'TU VAS SIN (fav)',
    'artist' => 'Rels B',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730e409fad9527196e73e423ba',
    'meaning' => 'Karya "TU VAS SIN (fav)" oleh Rels B melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6uiQ0DqbXTBc8tl0AUKZkR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  40 => 
  array (
    'id' => 2737,
    'spotify_id' => '0Sa8aRfGckW0qUGLrBwoBG',
    'title' => 'Todo Lo Fue',
    'artist' => 'Lenin Ramírez',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27334fc9cf3365e3e9d5f86ffe3',
    'meaning' => 'Karya "Todo Lo Fue" oleh Lenin Ramírez melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0Sa8aRfGckW0qUGLrBwoBG',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  41 => 
  array (
    'id' => 2739,
    'spotify_id' => '3jjtFEoA1watKCxXwa7eRj',
    'title' => 'Tunggal Eka',
    'artist' => 'La Tasya',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ba52b2565c271b5c2d062f03',
    'meaning' => 'Karya "Tunggal Eka" oleh La Tasya melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3jjtFEoA1watKCxXwa7eRj',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  42 => 
  array (
    'id' => 2740,
    'spotify_id' => '4aFuuljaGlBPNnRgM6NTge',
    'title' => 'Tunjukkan Cintamu',
    'artist' => 'Nosstress',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273dfed2fe693569b62f3bf1677',
    'meaning' => 'Keberanian untuk mengungkapkan rasa cinta secara jujur dan terbuka tanpa ada keraguan.',
    'spotify_url' => 'https://open.spotify.com/track/4aFuuljaGlBPNnRgM6NTge',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  43 => 
  array (
    'id' => 2741,
    'spotify_id' => '4GUphFvzqaCHPDkS2VDn2I',
    'title' => 'Tunggu Apa Lagi',
    'artist' => 'Paul Aro',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273332c54557556b882c53206ef',
    'meaning' => 'Karya "Tunggu Apa Lagi" oleh Paul Aro melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4GUphFvzqaCHPDkS2VDn2I',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  44 => 
  array (
    'id' => 2742,
    'spotify_id' => '0Z0K5nZGqw8WuV4WOLxVnR',
    'title' => 'Tunggu Aku Di Jakarta',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e8d4f0596d66ccbe5241918d',
    'meaning' => 'Karya "Tunggu Aku Di Jakarta" oleh Sheila On 7 melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0Z0K5nZGqw8WuV4WOLxVnR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  45 => 
  array (
    'id' => 2743,
    'spotify_id' => '0nPBQcxySyO61KVV2HKw8J',
    'title' => 'Tunggulah Tunggu',
    'artist' => 'Monkey Boots',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273778b4bccda4ed7387713f9b8',
    'meaning' => 'Karya "Tunggulah Tunggu" oleh Monkey Boots melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0nPBQcxySyO61KVV2HKw8J',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  46 => 
  array (
    'id' => 2744,
    'spotify_id' => '1As1hz5xjRyOgKS18p9sbi',
    'title' => 'Tunggal Eka',
    'artist' => 'Silvy Kumalasari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730b4aa52dd5d871476924a932',
    'meaning' => 'Karya "Tunggal Eka" oleh Silvy Kumalasari melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1As1hz5xjRyOgKS18p9sbi',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  47 => 
  array (
    'id' => 2745,
    'spotify_id' => '0Hxa8rxKGhFzsyZpqZVSmQ',
    'title' => 'tongue',
    'artist' => 'Bella Kay',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739596fe56f6e29ff9d519ac08',
    'meaning' => 'Karya "tongue" oleh Bella Kay melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0Hxa8rxKGhFzsyZpqZVSmQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  48 => 
  array (
    'id' => 2746,
    'spotify_id' => '0KNJrBUU6A93gsBlPo9F7Q',
    'title' => 'Tunnel Noise',
    'artist' => 'Ecstatix',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27385f85d4a01ef6e6d3c23a5ee',
    'meaning' => 'Karya "Tunnel Noise" oleh Ecstatix melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0KNJrBUU6A93gsBlPo9F7Q',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  49 => 
  array (
    'id' => 2747,
    'spotify_id' => '4Q3N4Ct4zCuIHuZ65E3BD4',
    'title' => 'Tunnel Vision',
    'artist' => 'Kodak Black',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731541a676423805fc68ff3e66',
    'meaning' => 'Karya "Tunnel Vision" oleh Kodak Black melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4Q3N4Ct4zCuIHuZ65E3BD4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:00',
  ),
  50 => 
  array (
    'id' => 2749,
    'spotify_id' => '6pOmOGrSIPy2MEdQ9riRHF',
    'title' => 'Tunjuk Satu Bintang',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e8d4f0596d66ccbe5241918d',
    'meaning' => 'Harapan dan petunjuk cinta di tengah kegelapan, bagaikan menunjuk satu bintang terang pemandu arah.',
    'spotify_url' => 'https://open.spotify.com/track/6pOmOGrSIPy2MEdQ9riRHF',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/f6/39/ea/f639eaa0-13d4-29d7-d340-e102d55a78ca/mzaf_16998589234019814405.plus.aac.p.m4a',
    'created_at' => '2026-08-05 12:00:01',
  ),
  51 => 
  array (
    'id' => 2750,
    'spotify_id' => '0hzIdk9dIvDablVS6UW7Vi',
    'title' => 'Yang Patah Tumbuh, Yang Hilang Berganti',
    'artist' => 'Banda Neira',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737a173b7767ca05f9bb17464e',
    'meaning' => 'Lagu "Yang Patah Tumbuh, Yang Hilang Berganti" karya Banda Neira mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/0hzIdk9dIvDablVS6UW7Vi',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  52 => 
  array (
    'id' => 2751,
    'spotify_id' => '2x3vwXWuecPrRqgEUuSUJA',
    'title' => 'Semua Aku Dirayakan',
    'artist' => 'Nadin Amizah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e1ea9379951ad47d8fef07d6',
    'meaning' => 'Karya "Semua Aku Dirayakan" oleh Nadin Amizah melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2x3vwXWuecPrRqgEUuSUJA',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  53 => 
  array (
    'id' => 2752,
    'spotify_id' => '2a49aqOHDWxsdbNjmTVdF3',
    'title' => 'Tunjukkan Padaku',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27358961269cc5263913f9e0b40',
    'meaning' => 'Keberanian untuk mengungkapkan rasa cinta secara jujur dan terbuka tanpa ada keraguan.',
    'spotify_url' => 'https://open.spotify.com/track/2a49aqOHDWxsdbNjmTVdF3',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  54 => 
  array (
    'id' => 2753,
    'spotify_id' => '4B3DEANIvod8552CbwftCG',
    'title' => 'Sampai Jadi Debu (Menampilkan Gardika Gigih)',
    'artist' => 'Banda Neira',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737a173b7767ca05f9bb17464e',
    'meaning' => 'Karya "Sampai Jadi Debu (Menampilkan Gardika Gigih)" oleh Banda Neira melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4B3DEANIvod8552CbwftCG',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  55 => 
  array (
    'id' => 2754,
    'spotify_id' => '2iE5HPk4aVALAqU5pQNhto',
    'title' => 'Cinta Jangan Sembunyi',
    'artist' => 'Seventeen',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736c115028946a54c7d2a14bf4',
    'meaning' => 'Lagu "Cinta Jangan Sembunyi" karya Seventeen mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/2iE5HPk4aVALAqU5pQNhto',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  56 => 
  array (
    'id' => 2755,
    'spotify_id' => '1nS26Wl57XmKszgKt9FQ61',
    'title' => 'Tunjukkan Cintamu',
    'artist' => 'RAN',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a9aa03093d967c97ef72c18b',
    'meaning' => 'Keberanian untuk mengungkapkan rasa cinta secara jujur dan terbuka tanpa ada keraguan.',
    'spotify_url' => 'https://open.spotify.com/track/1nS26Wl57XmKszgKt9FQ61',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  57 => 
  array (
    'id' => 2756,
    'spotify_id' => '52QHaMwIh2jrerfGIRgCou',
    'title' => 'Tunjuk Satu Bintang',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739c5397f4251f7137ac19d93e',
    'meaning' => 'Harapan dan petunjuk cinta di tengah kegelapan, bagaikan menunjuk satu bintang terang pemandu arah.',
    'spotify_url' => 'https://open.spotify.com/track/52QHaMwIh2jrerfGIRgCou',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  58 => 
  array (
    'id' => 2757,
    'spotify_id' => '2919WffLDSzq1EhCdMrFT9',
    'title' => 'Tűnj El!',
    'artist' => 'Horváth Tamás',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e14739c0cb325349a2facc3b',
    'meaning' => 'Karya "Tűnj El!" oleh Horváth Tamás melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2919WffLDSzq1EhCdMrFT9',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  59 => 
  array (
    'id' => 2766,
    'spotify_id' => '5eIXgtuDxCbTAAhNV4zzJ6',
    'title' => 'Tunjukkan Padaku',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739c5397f4251f7137ac19d93e',
    'meaning' => 'Keberanian untuk mengungkapkan rasa cinta secara jujur dan terbuka tanpa ada keraguan.',
    'spotify_url' => 'https://open.spotify.com/track/5eIXgtuDxCbTAAhNV4zzJ6',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  60 => 
  array (
    'id' => 2767,
    'spotify_id' => '4jyDAFEYhayQxPjrUfVbXX',
    'title' => 'Tunjuk Satu Bintang - Re-Mix',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27398b7cd420705531db32b3aeb',
    'meaning' => 'Harapan dan petunjuk cinta di tengah kegelapan, bagaikan menunjuk satu bintang terang pemandu arah.',
    'spotify_url' => 'https://open.spotify.com/track/4jyDAFEYhayQxPjrUfVbXX',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  61 => 
  array (
    'id' => 2777,
    'spotify_id' => '04wuZ1XIwcVyxUzAneO1O1',
    'title' => 'Gelora Cintaku',
    'artist' => 'Trio Lestari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f388c0c4d951c9a92aeb5155',
    'meaning' => 'Perasaan cinta yang membara dan bergelora menghiasi relung hati dengan kebahagiaan.',
    'spotify_url' => 'https://open.spotify.com/track/04wuZ1XIwcVyxUzAneO1O1',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  62 => 
  array (
    'id' => 2780,
    'spotify_id' => '3TW8XLF8PyA3kFsV1l5713',
    'title' => 'Mesra-mesraannya kecil-kecilan dulu',
    'artist' => 'Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273680f1025f6619c42a3c23864',
    'meaning' => 'Kehangatan cinta sederhana yang tumbuh pelan-pelan melalui momen-momen kecil yang sangat berarti.',
    'spotify_url' => 'https://open.spotify.com/track/3TW8XLF8PyA3kFsV1l5713',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  63 => 
  array (
    'id' => 2782,
    'spotify_id' => '5OBZxj4TWITOd5yUmynp91',
    'title' => 'Tunjukkan',
    'artist' => 'Afgan, Raisa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27388de31af312f97b1bf111b90',
    'meaning' => 'Keberanian untuk mengungkapkan rasa cinta secara jujur dan terbuka tanpa ada keraguan.',
    'spotify_url' => 'https://open.spotify.com/track/5OBZxj4TWITOd5yUmynp91',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  64 => 
  array (
    'id' => 2786,
    'spotify_id' => '6uzq3ot6zEAmmgBbUepwZE',
    'title' => 'Tunjukkanku Bahagia',
    'artist' => 'Syamel',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732a09fc4b4f164f79488d65e7',
    'meaning' => 'Keberanian untuk mengungkapkan rasa cinta secara jujur dan terbuka tanpa ada keraguan.',
    'spotify_url' => 'https://open.spotify.com/track/6uzq3ot6zEAmmgBbUepwZE',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:00:01',
  ),
  65 => 
  array (
    'id' => 2838,
    'spotify_id' => '4HtnRLeRu7N7sTGtwOvdjY',
    'title' => 'Bunga Abadi',
    'artist' => 'Rio Clappy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27376d805fb6b4fdb20b348b0e1',
    'meaning' => 'Simbol cinta abadi yang tidak akan pernah layu dan selalu mekar melintasi batas waktu.',
    'spotify_url' => 'https://open.spotify.com/track/4HtnRLeRu7N7sTGtwOvdjY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:34',
  ),
  66 => 
  array (
    'id' => 2839,
    'spotify_id' => '25Q9BijrYpnveu4cNUYyNF',
    'title' => 'Bunga Terakhir',
    'artist' => 'Romeo',
    'cover_url' => 'https://i.scdn.co/image/3360aa4767b5f05dafeee92f871d6d8f990ef0d8',
    'meaning' => 'Ungkapan perpisahan terakhir dan penghormatan setinggi-tingginya kepada kekasih jiwa yang tak tergantikan.',
    'spotify_url' => 'https://open.spotify.com/track/25Q9BijrYpnveu4cNUYyNF',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:34',
  ),
  67 => 
  array (
    'id' => 2843,
    'spotify_id' => '5mfqUkr1zbnVPb1vHQY6oJ',
    'title' => 'Bukti',
    'artist' => 'Virgoun',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27371ceae5c6f90a2874dc04cc8',
    'meaning' => 'Rasa syukur dan bukti nyata kasih sayang atas anugerah sosok pasangan yang setia mendampingi hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5mfqUkr1zbnVPb1vHQY6oJ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  68 => 
  array (
    'id' => 2844,
    'spotify_id' => '5dhJhL42WWQLYBUTbMtLF7',
    'title' => 'Bukan Dia Tapi Aku',
    'artist' => 'Judika',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735f14b2386437640366a1e6de',
    'meaning' => 'Jeritan hati seseorang yang merasa lebih layak mencintai dan memperjuangkan pasangan ketimbang orang lain.',
    'spotify_url' => 'https://open.spotify.com/track/5dhJhL42WWQLYBUTbMtLF7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  69 => 
  array (
    'id' => 2845,
    'spotify_id' => '41d2WjuL0ikRKVjxmL7ZFz',
    'title' => 'BOOMPALA',
    'artist' => 'LE SSERAFIM',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733fba33983638fcf9704c965d',
    'meaning' => 'Karya "BOOMPALA" oleh LE SSERAFIM melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/41d2WjuL0ikRKVjxmL7ZFz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  70 => 
  array (
    'id' => 2846,
    'spotify_id' => '4zmXWmILSBkn7gTvIyCiNi',
    'title' => 'bad thing (bunny hop)',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738baf677ee2d8dda6cc9fcbd7',
    'meaning' => 'Karya "bad thing (bunny hop)" oleh Ariana Grande melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4zmXWmILSBkn7gTvIyCiNi',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  71 => 
  array (
    'id' => 2847,
    'spotify_id' => '2ixsaeFioXJmMgkkbd4uj1',
    'title' => 'Budapest',
    'artist' => 'George Ezra',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733a60095e50104070cc89ed9f',
    'meaning' => 'Karya "Budapest" oleh George Ezra melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2ixsaeFioXJmMgkkbd4uj1',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  72 => 
  array (
    'id' => 2848,
    'spotify_id' => '5D5hmvNJW09h5bgCg3nQE7',
    'title' => 'Buahagia',
    'artist' => 'HalloHEXA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b558546cd2338bd597ba5ee8',
    'meaning' => 'Karya "Buahagia" oleh HalloHEXA melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5D5hmvNJW09h5bgCg3nQE7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  73 => 
  array (
    'id' => 2849,
    'spotify_id' => '4pQVElveW9lmo7PaBjAdcA',
    'title' => 'Buah Hati',
    'artist' => 'Armada',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273599b380d3606ddbb235e682e',
    'meaning' => 'Karya "Buah Hati" oleh Armada melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4pQVElveW9lmo7PaBjAdcA',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  74 => 
  array (
    'id' => 2850,
    'spotify_id' => '6fp5H6JgnlAnS69SktBhpg',
    'title' => 'Buat Aku Tersenyum',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27358961269cc5263913f9e0b40',
    'meaning' => 'Harapan sederhana agar sang kekasih selalu hadir membawa tawa, kedamaian, dan ketenangan di kala duka.',
    'spotify_url' => 'https://open.spotify.com/track/6fp5H6JgnlAnS69SktBhpg',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/a0/12/94/a0129452-657b-490a-65ad-45b5fa5c2166/mzaf_10264557792612538075.plus.aac.p.m4a',
    'created_at' => '2026-08-05 12:07:35',
  ),
  75 => 
  array (
    'id' => 2851,
    'spotify_id' => '0gwOixLwtjRpnC52W7aHYR',
    'title' => 'Hapus Aku',
    'artist' => 'Nidji',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273706b70b10dfbf83dd4b1e7d8',
    'meaning' => 'Karya "Hapus Aku" oleh Nidji melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0gwOixLwtjRpnC52W7aHYR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  76 => 
  array (
    'id' => 2852,
    'spotify_id' => '4NHC7OLNMxhGFSI7CoDlsj',
    'title' => 'Buai Laju-Laju (Live Version)',
    'artist' => 'Upin & Ipin',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732a29d4c3ec460979039835e1',
    'meaning' => 'Karya "Buai Laju-Laju (Live Version)" oleh Upin & Ipin melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4NHC7OLNMxhGFSI7CoDlsj',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  77 => 
  array (
    'id' => 2853,
    'spotify_id' => '4J9DouSADdyakPD9h6oD6N',
    'title' => 'Kita Buat Menyenangkan',
    'artist' => 'Bernadya',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a0ef802fc11295f6ffa4cbc2',
    'meaning' => 'Ajakan untuk menikmati setiap detik hubungan dengan kegembiraan, ketulusan, dan tanpa beban.',
    'spotify_url' => 'https://open.spotify.com/track/4J9DouSADdyakPD9h6oD6N',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  78 => 
  array (
    'id' => 2854,
    'spotify_id' => '7esAWY5aFUAGi59jpf1qzy',
    'title' => 'Lelaki Buaya Darat',
    'artist' => 'Ratu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273590a08574756e4b72b54d8c9',
    'meaning' => 'Karya "Lelaki Buaya Darat" oleh Ratu melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7esAWY5aFUAGi59jpf1qzy',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
  79 => 
  array (
    'id' => 2855,
    'spotify_id' => '0D5jTvo7vLIDupgrl12cHW',
    'title' => 'Buaya Buntung',
    'artist' => 'Inul Daratista',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f9c2fad06cdb8c65a00c2521',
    'meaning' => 'Karya "Buaya Buntung" oleh Inul Daratista melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0D5jTvo7vLIDupgrl12cHW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 12:07:35',
  ),
);
$allLocalSongs = [];
$allMessages = [];
require __DIR__ . '/migration_common.php';
?>
