<?php
$batchNum = 5;
$isLastBatch = false;
$batchSongs = array (
  0 => 
  array (
    'id' => 1656,
    'spotify_id' => '1LwnJ36kvYmZVQ0Ol6ULn4',
    'title' => 'Wals Akhir Zaman',
    'artist' => 'Rony Parulian',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27358be25a2a5319d5e6136cd1e',
    'meaning' => 'Lagu "Wals Akhir Zaman" karya Rony Parulian mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/1LwnJ36kvYmZVQ0Ol6ULn4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  1 => 
  array (
    'id' => 1657,
    'spotify_id' => '562SZ62uMo9PKOEMmpm3yT',
    'title' => 'Akhir Pekan Yang Hilang',
    'artist' => 'Bilal Indrajaya',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735d1da90de21f8421a73f51e6',
    'meaning' => 'Pertanyaan dan imajinasi tentang apa yang akan terjadi jika perasaan cinta yang terpendam akhirnya diungkapkan.',
    'spotify_url' => 'https://open.spotify.com/track/562SZ62uMo9PKOEMmpm3yT',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  2 => 
  array (
    'id' => 1658,
    'spotify_id' => '0M0ANKNzmM4Odd7FNKghzW',
    'title' => 'Akhiyaan Gulaab (From "Teri Baaton Mein Aisa Uljha Jiya")',
    'artist' => 'Mitraz',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27352e3a807b72281cb40c08092',
    'meaning' => 'Karya "Akhiyaan Gulaab (From "Teri Baaton Mein Aisa Uljha Jiya")" oleh Mitraz melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0M0ANKNzmM4Odd7FNKghzW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  3 => 
  array (
    'id' => 1659,
    'spotify_id' => '22TntnVO3lQNDR5nsvxGRs',
    'title' => 'Achilles Come Down',
    'artist' => 'Gang of Youths',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a2329c84c1421041f06a7ad5',
    'meaning' => 'Karya "Achilles Come Down" oleh Gang of Youths melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/22TntnVO3lQNDR5nsvxGRs',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  4 => 
  array (
    'id' => 1680,
    'spotify_id' => '3ZwqWrRpylU9nfy99qwKdR',
    'title' => 'Pelangi',
    'artist' => 'Hivi!',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273abbee551b5c821d7624949ae',
    'meaning' => 'Karya "Pelangi" oleh Hivi! melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3ZwqWrRpylU9nfy99qwKdR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  5 => 
  array (
    'id' => 1681,
    'spotify_id' => '3GdN5n6p34yFMd12WKq8jL',
    'title' => 'Penyangkalan',
    'artist' => 'For Revenge',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730b2982815e3f47c2fb7b74c4',
    'meaning' => 'Karya "Penyangkalan" oleh For Revenge melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3GdN5n6p34yFMd12WKq8jL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  6 => 
  array (
    'id' => 1683,
    'spotify_id' => '0tgVpDi06FyKpA1z0VMD4v',
    'title' => 'Perfect',
    'artist' => 'Ed Sheeran',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96',
    'meaning' => 'Lagu romantisme sejati tentang menemukan pasangan hidup sejak masa muda dan membangun harapan serta impian masa depan bersama.',
    'spotify_url' => 'https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  7 => 
  array (
    'id' => 1687,
    'spotify_id' => '0wH6QrjxtfuDRWJg4sr596',
    'title' => 'Pikiran Yang Matang',
    'artist' => 'Perunggu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27387221ad6b867ad30afdf048c',
    'meaning' => 'Karya "Pikiran Yang Matang" oleh Perunggu melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0wH6QrjxtfuDRWJg4sr596',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  8 => 
  array (
    'id' => 1688,
    'spotify_id' => '70pVCVMGjmIWPbWXDwf11e',
    'title' => 'petal',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738baf677ee2d8dda6cc9fcbd7',
    'meaning' => 'Karya "petal" oleh Ariana Grande melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/70pVCVMGjmIWPbWXDwf11e',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  9 => 
  array (
    'id' => 1689,
    'spotify_id' => '2gam98EZKrF9XuOkU13ApN',
    'title' => 'Promiscuous',
    'artist' => 'Nelly Furtado, Timbaland',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a6f439c8957170652f9410e2',
    'meaning' => 'Karya "Promiscuous" oleh Nelly Furtado, Timbaland melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2gam98EZKrF9XuOkU13ApN',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  10 => 
  array (
    'id' => 1692,
    'spotify_id' => '7F4tV8SiUy6itZTdAzdafO',
    'title' => 'penjaga hati',
    'artist' => 'Nadhif Basalamah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735c60335b52110564cbe57176',
    'meaning' => 'Keinginan kuat dan tekad tulus untuk menjadi sosok pelindung dan tempat pulang paling aman bagi kekasih tercinta.',
    'spotify_url' => 'https://open.spotify.com/track/7F4tV8SiUy6itZTdAzdafO',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  11 => 
  array (
    'id' => 1698,
    'spotify_id' => '060LysflCUxQKLKGLe9zJW',
    'title' => 'petal',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27322f0df4c56abce4f20200cb9',
    'meaning' => 'Karya "petal" oleh Ariana Grande melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/060LysflCUxQKLKGLe9zJW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  12 => 
  array (
    'id' => 1699,
    'spotify_id' => '1wrA9K1P177mkPNt9BB2OZ',
    'title' => 'Peão Todo Tatuado',
    'artist' => 'Jeninho, Mariana Fagundes',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734b475e7b048541cd6fcc3bdc',
    'meaning' => 'Karya "Peão Todo Tatuado" oleh Jeninho, Mariana Fagundes melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1wrA9K1P177mkPNt9BB2OZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  13 => 
  array (
    'id' => 1702,
    'spotify_id' => '33UIshRVxXEBzITjCzo6al',
    'title' => 'Sadrah',
    'artist' => 'For Revenge',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736b7b08b4347fc245118ad80c',
    'meaning' => 'Lagu "Sadrah" karya For Revenge mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/33UIshRVxXEBzITjCzo6al',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  14 => 
  array (
    'id' => 1703,
    'spotify_id' => '6i9Ci0IN1q1GcnhdbKU7kZ',
    'title' => 'penjaga hati',
    'artist' => 'Nadhif Basalamah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27325001f594384ffb7fb952347',
    'meaning' => 'Keinginan kuat dan tekad tulus untuk menjadi sosok pelindung dan tempat pulang paling aman bagi kekasih tercinta.',
    'spotify_url' => 'https://open.spotify.com/track/6i9Ci0IN1q1GcnhdbKU7kZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  15 => 
  array (
    'id' => 1704,
    'spotify_id' => '09eWF5r8kasfOEp8RFRQLv',
    'title' => 'Serana',
    'artist' => 'For Revenge',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27366de8f7224e459d2cc0f9a1f',
    'meaning' => 'Karya "Serana" oleh For Revenge melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/09eWF5r8kasfOEp8RFRQLv',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  16 => 
  array (
    'id' => 1705,
    'spotify_id' => '5BEaISZ1DicXxN6DJ5kdtg',
    'title' => 'Penyangkalan',
    'artist' => 'For Revenge',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273bf09e5d5661fe469bdf8e622',
    'meaning' => 'Karya "Penyangkalan" oleh For Revenge melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5BEaISZ1DicXxN6DJ5kdtg',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  17 => 
  array (
    'id' => 1706,
    'spotify_id' => '6bwnZc3E6u1AMZcw0dRhpd',
    'title' => 'PENYIHIR',
    'artist' => 'Ghea Indrawari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27314814de2da42fd2273d0fcff',
    'meaning' => 'Karya "PENYIHIR" oleh Ghea Indrawari melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6bwnZc3E6u1AMZcw0dRhpd',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  18 => 
  array (
    'id' => 1707,
    'spotify_id' => '0peDS2F3fH9U5YKSF9SZmm',
    'title' => 'Pendampingmu #TahtaHatiku',
    'artist' => 'Shabrina Leanor',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27326c1094206bbd6c4d516115d',
    'meaning' => 'Karya "Pendampingmu #TahtaHatiku" oleh Shabrina Leanor melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0peDS2F3fH9U5YKSF9SZmm',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  19 => 
  array (
    'id' => 1708,
    'spotify_id' => '7CzCzHw4TYwbGNMt9A9V0S',
    'title' => 'Penghujung Cerita',
    'artist' => 'Murphy Radio',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731e06ecd6c3dcffece1004f40',
    'meaning' => 'Karya "Penghujung Cerita" oleh Murphy Radio melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7CzCzHw4TYwbGNMt9A9V0S',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  20 => 
  array (
    'id' => 1709,
    'spotify_id' => '1xKP7GVLY33i5jmx1bB1Kk',
    'title' => 'Piensa En Mí',
    'artist' => 'Grupo Mojado',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f25a5393f9b7461032b15b07',
    'meaning' => 'Karya "Piensa En Mí" oleh Grupo Mojado melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1xKP7GVLY33i5jmx1bB1Kk',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  21 => 
  array (
    'id' => 1712,
    'spotify_id' => '3PP82ZJqkAFRFEMoAt0yy8',
    'title' => 'Pengorbanan',
    'artist' => 'Setia Band, Nenden',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a7d533df31a4d9a81e7e89c0',
    'meaning' => 'Karya "Pengorbanan" oleh Setia Band, Nenden melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3PP82ZJqkAFRFEMoAt0yy8',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  22 => 
  array (
    'id' => 1713,
    'spotify_id' => '6rxFUsLmRp8Z3KQEfZXZQA',
    'title' => 'NGANGGUR',
    'artist' => 'Masdddho',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273fc782ab9ed3e567fab3a8442',
    'meaning' => 'Karya "NGANGGUR" oleh Masdddho melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6rxFUsLmRp8Z3KQEfZXZQA',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  23 => 
  array (
    'id' => 1714,
    'spotify_id' => '3awTnPYtwJsTCqlgSMwSji',
    'title' => 'Kelam Malam',
    'artist' => 'The Spouse, Aimee Saras',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273518f9b4446239f7625dd1a50',
    'meaning' => 'Lagu "Kelam Malam" karya The Spouse, Aimee Saras membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/3awTnPYtwJsTCqlgSMwSji',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  24 => 
  array (
    'id' => 1715,
    'spotify_id' => '2sxrq1v5KQl233eWUGE8wb',
    'title' => 'Pengingat',
    'artist' => 'Good Morning Everyone',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735daba6257693af7ac822067d',
    'meaning' => 'Lagu "Pengingat" karya Good Morning Everyone menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/2sxrq1v5KQl233eWUGE8wb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  25 => 
  array (
    'id' => 1716,
    'spotify_id' => '2oIwHFzs7Zbcp62djGsLJ4',
    'title' => 'Pengenku Siji',
    'artist' => 'Hai Ges',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739005a82e267384851b1f4415',
    'meaning' => 'Karya "Pengenku Siji" oleh Hai Ges melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2oIwHFzs7Zbcp62djGsLJ4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  26 => 
  array (
    'id' => 1717,
    'spotify_id' => '4UUMA9msejPgKPn2vHFI0G',
    'title' => 'The Penguin Dance',
    'artist' => 'Pinkfong',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27311723f2867f29b2134ae47e4',
    'meaning' => 'Lagu "The Penguin Dance" karya Pinkfong menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/4UUMA9msejPgKPn2vHFI0G',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  27 => 
  array (
    'id' => 1718,
    'spotify_id' => '2GWyZi7oZ0mR5irhyt5DzM',
    'title' => 'Pengen Bali',
    'artist' => 'Lavora',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a7caf89c61663cd67ec9580f',
    'meaning' => 'Karya "Pengen Bali" oleh Lavora melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2GWyZi7oZ0mR5irhyt5DzM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  28 => 
  array (
    'id' => 1719,
    'spotify_id' => '7L15RIYFpoiHKJQNHsYhWM',
    'title' => 'Peng Black Girls Remix - A COLORS SHOW',
    'artist' => 'ENNY, Jorja Smith',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27381d5cb10c2b706f754f2a2e8',
    'meaning' => 'Karya "Peng Black Girls Remix - A COLORS SHOW" oleh ENNY, Jorja Smith melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7L15RIYFpoiHKJQNHsYhWM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  29 => 
  array (
    'id' => 1720,
    'spotify_id' => '1Ib0UNLoqBEWTmBvXeFSni',
    'title' => 'Pemuja Rahasia',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f0a7efc94687cc049b821529',
    'meaning' => 'Karya "Pemuja Rahasia" oleh Sheila On 7 melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1Ib0UNLoqBEWTmBvXeFSni',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  30 => 
  array (
    'id' => 1724,
    'spotify_id' => '0SVbu8vTED9s6TziofnNJY',
    'title' => 'Pengarepan',
    'artist' => 'Twentynine',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c8de92abb9d7adc510d1e623',
    'meaning' => 'Karya "Pengarepan" oleh Twentynine melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0SVbu8vTED9s6TziofnNJY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  31 => 
  array (
    'id' => 1725,
    'spotify_id' => '4rWrIURR4Xs4oZ7Gh2nklf',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Detik',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739c982ccb06b4ea30125bcb6e',
    'meaning' => 'Karya "Pengagum Rahasia" oleh Detik melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4rWrIURR4Xs4oZ7Gh2nklf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  32 => 
  array (
    'id' => 1726,
    'spotify_id' => '5H1xH94JI3itF88r43tZ2l',
    'title' => 'Pengantin Baru',
    'artist' => 'Gasentra Pajampangan, Salma',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273015c67f54c44e3d3cf13d582',
    'meaning' => 'Karya "Pengantin Baru" oleh Gasentra Pajampangan, Salma melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5H1xH94JI3itF88r43tZ2l',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:42',
  ),
  33 => 
  array (
    'id' => 1727,
    'spotify_id' => '5yKKCOyaVe9IOv0J7K9YDp',
    'title' => 'Pengarepan',
    'artist' => 'Royal Music, Dinda Teratu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730e9712eb8062e5690923f352',
    'meaning' => 'Karya "Pengarepan" oleh Royal Music, Dinda Teratu melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5yKKCOyaVe9IOv0J7K9YDp',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  34 => 
  array (
    'id' => 1728,
    'spotify_id' => '20Elh8amCvzTczYlu73BBn',
    'title' => 'Pengantar Tidur Malam',
    'artist' => 'Musik Relaksasi ID',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737b308115656bf9d1296619cf',
    'meaning' => 'Lagu "Pengantar Tidur Malam" karya Musik Relaksasi ID membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/20Elh8amCvzTczYlu73BBn',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  35 => 
  array (
    'id' => 1729,
    'spotify_id' => '51yxokB0Oqcvew4QLfwPkj',
    'title' => 'Pengarepan',
    'artist' => 'DJ ALMIRA BERTO',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731934f3a0bf880a569f3cb9ea',
    'meaning' => 'Karya "Pengarepan" oleh DJ ALMIRA BERTO melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/51yxokB0Oqcvew4QLfwPkj',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  36 => 
  array (
    'id' => 1734,
    'spotify_id' => '5PZj5xHp2quaDlLq7V2RMM',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Nabila Taqiyyah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732cc7eb853887837e0a4b726e',
    'meaning' => 'Pertanyaan dan imajinasi tentang apa yang akan terjadi jika perasaan cinta yang terpendam akhirnya diungkapkan.',
    'spotify_url' => 'https://open.spotify.com/track/5PZj5xHp2quaDlLq7V2RMM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  37 => 
  array (
    'id' => 1736,
    'spotify_id' => '3hYkmzdRTtPfsQB1Dz0nRp',
    'title' => 'Pengagungan',
    'artist' => 'Army Of God Worship',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e137877ce53dcb51eb92dace',
    'meaning' => 'Karya "Pengagungan" oleh Army Of God Worship melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3hYkmzdRTtPfsQB1Dz0nRp',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  38 => 
  array (
    'id' => 1738,
    'spotify_id' => '76Yr1kxouggBO023HqBZ9o',
    'title' => 'Pengagungan',
    'artist' => 'Army Of God Worship',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732365c1ef1be1f038c96d7b1d',
    'meaning' => 'Karya "Pengagungan" oleh Army Of God Worship melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/76Yr1kxouggBO023HqBZ9o',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  39 => 
  array (
    'id' => 1740,
    'spotify_id' => '7nVQ1PZxJGh19ITwZO7OhM',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Dimas Yuniarr',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27315f6b212e9a3f56f75a65453',
    'meaning' => 'Karya "Pengagum Rahasia" oleh Dimas Yuniarr melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/7nVQ1PZxJGh19ITwZO7OhM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  40 => 
  array (
    'id' => 1743,
    'spotify_id' => '3mfsulPqSjxyXfLv2fYI9u',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Pendhoza',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273530dc0abe88251af831a6389',
    'meaning' => 'Karya "Pengagum Rahasia" oleh Pendhoza melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3mfsulPqSjxyXfLv2fYI9u',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  41 => 
  array (
    'id' => 1753,
    'spotify_id' => '4bDVT4vPR2KM2RdOV4mTJL',
    'title' => 'Pengagum',
    'artist' => 'Rafi Sudirman',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273653ae5aa85d06ba739adfba1',
    'meaning' => 'Karya "Pengagum" oleh Rafi Sudirman melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4bDVT4vPR2KM2RdOV4mTJL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  42 => 
  array (
    'id' => 1756,
    'spotify_id' => '01ZEAmXSePhM6t2QnUA5mX',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Rendy Laks',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c3852ce27a82dbaaa3ad7c9a',
    'meaning' => 'Karya "Pengagum Rahasia" oleh Rendy Laks melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/01ZEAmXSePhM6t2QnUA5mX',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:43',
  ),
  43 => 
  array (
    'id' => 1776,
    'spotify_id' => '1wTETzX8B6wWgXWR67eZHb',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Blue Eyes',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734fbd50fc8bba5dddf46f5540',
    'meaning' => 'Karya "Pengagum Rahasia" oleh Blue Eyes melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1wTETzX8B6wWgXWR67eZHb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:51',
  ),
  44 => 
  array (
    'id' => 1787,
    'spotify_id' => '0NrGEbLL9aggrUwsWJUWaT',
    'title' => 'Pengganti Aku',
    'artist' => 'Raisa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273390b568b7e725b7039585800',
    'meaning' => 'Karya "Pengganti Aku" oleh Raisa melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0NrGEbLL9aggrUwsWJUWaT',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:51',
  ),
  45 => 
  array (
    'id' => 1789,
    'spotify_id' => '52v1IcYW8l17Q72wWMeklf',
    'title' => 'Rayakan Pemenang',
    'artist' => 'Morfem',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b6a736c753e4de1be8cb4649',
    'meaning' => 'Karya "Rayakan Pemenang" oleh Morfem melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/52v1IcYW8l17Q72wWMeklf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:51',
  ),
  46 => 
  array (
    'id' => 1799,
    'spotify_id' => '2RyLNtxzGh14jilLNe6NEq',
    'title' => 'PenyertaanMu',
    'artist' => 'JCC Worship, Sisca Verina, Veren',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d87b4bd362dd7b977688a42c',
    'meaning' => 'Karya "PenyertaanMu" oleh JCC Worship, Sisca Verina, Veren melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2RyLNtxzGh14jilLNe6NEq',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:51',
  ),
  47 => 
  array (
    'id' => 1818,
    'spotify_id' => '6yBUU8IqliBbRsaIxBjTHO',
    'title' => 'Pengharapanku',
    'artist' => 'Keluarga Allah Worship',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27328bd6175ae0c8e287a7a4070',
    'meaning' => 'Karya "Pengharapanku" oleh Keluarga Allah Worship melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6yBUU8IqliBbRsaIxBjTHO',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:52',
  ),
  48 => 
  array (
    'id' => 1827,
    'spotify_id' => '2x7FNOlOS0ZYn0Bsv8S3FG',
    'title' => 'Rahasia Perempuan',
    'artist' => 'Ari Lasso',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27311c348a4c084b1add0c8ad1c',
    'meaning' => 'Karya "Rahasia Perempuan" oleh Ari Lasso melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2x7FNOlOS0ZYn0Bsv8S3FG',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:52',
  ),
  49 => 
  array (
    'id' => 1838,
    'spotify_id' => '1X80KdFJpedU4as4WGIgYM',
    'title' => 'Rahasia Hati',
    'artist' => 'Element',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735764299de24a6d0a74237ce9',
    'meaning' => 'Karya "Rahasia Hati" oleh Element melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1X80KdFJpedU4as4WGIgYM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:52',
  ),
  50 => 
  array (
    'id' => 1841,
    'spotify_id' => '3pg3W2ELwNr3sJBR8TsLP7',
    'title' => 'Pengecut',
    'artist' => 'Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b20f21a54cb065ef7e0a110a',
    'meaning' => 'Karya "Pengecut" oleh Fiersa Besari melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3pg3W2ELwNr3sJBR8TsLP7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  51 => 
  array (
    'id' => 1842,
    'spotify_id' => '62GMLUJmqCFevPiohzM2jk',
    'title' => 'Ego',
    'artist' => 'L.Y.O.N',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731022ae9d90bf28fee90a3d25',
    'meaning' => 'Karya "Ego" oleh L.Y.O.N melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/62GMLUJmqCFevPiohzM2jk',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  52 => 
  array (
    'id' => 1843,
    'spotify_id' => '6NEO6FFVCO40TVYh9usJ14',
    'title' => 'Pengagum Rahasia',
    'artist' => 'CONT1NUEs',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27391977e4c6db06240221eae4a',
    'meaning' => 'Karya "Pengagum Rahasia" oleh CONT1NUEs melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6NEO6FFVCO40TVYh9usJ14',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  53 => 
  array (
    'id' => 1844,
    'spotify_id' => '5gistNWeagt8KbCNXvgyRW',
    'title' => 'Pengecut',
    'artist' => 'Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f81359f7eef90a8bf323b50d',
    'meaning' => 'Karya "Pengecut" oleh Fiersa Besari melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5gistNWeagt8KbCNXvgyRW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  54 => 
  array (
    'id' => 1845,
    'spotify_id' => '6SXTodU8kYpDalKpvXyjiB',
    'title' => 'Detik Waktu',
    'artist' => 'Karimata',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730e4bd882645a1abe37051fab',
    'meaning' => 'Karya "Detik Waktu" oleh Karimata melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/6SXTodU8kYpDalKpvXyjiB',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  55 => 
  array (
    'id' => 1846,
    'spotify_id' => '1svU65QddvvLA0YY9mdiqF',
    'title' => 'Menghitung Hari 2',
    'artist' => 'Anda Perdana',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b7045ac05d83bd7087e91096',
    'meaning' => 'Permohonan maaf yang tulus dan keikhlasan dilupakan demi menghapus penderitaan kekasih akibat kesalahan diri.',
    'spotify_url' => 'https://open.spotify.com/track/1svU65QddvvLA0YY9mdiqF',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  56 => 
  array (
    'id' => 1847,
    'spotify_id' => '42si4ikg5dh732gPuQ0xHb',
    'title' => 'C.H.R.I.S.Y.E.',
    'artist' => 'Diskoria, Laleilmanino, Eva Celia',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738d4c74b4164f0ea7e4006a99',
    'meaning' => 'Karya "C.H.R.I.S.Y.E." oleh Diskoria, Laleilmanino, Eva Celia melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/42si4ikg5dh732gPuQ0xHb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  57 => 
  array (
    'id' => 1848,
    'spotify_id' => '0f60ebJZ2PmrO8ThHIbHsz',
    'title' => 'Tak Bisa Ku Sembunyikan',
    'artist' => 'MAKRIFAT',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27310ae32823a167d035a19cd4b',
    'meaning' => 'Karya "Tak Bisa Ku Sembunyikan" oleh MAKRIFAT melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0f60ebJZ2PmrO8ThHIbHsz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  58 => 
  array (
    'id' => 1849,
    'spotify_id' => '5L4f7iwl51uOieZmSzNgUL',
    'title' => 'Hanya Dalam Diam',
    'artist' => 'INDRAZA Experimental Project',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738856d23c05fd79ac9cf66627',
    'meaning' => 'Karya "Hanya Dalam Diam" oleh INDRAZA Experimental Project melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5L4f7iwl51uOieZmSzNgUL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:19:59',
  ),
  59 => 
  array (
    'id' => 1862,
    'spotify_id' => '3USY5eGZWQuUnO1pVmse2a',
    'title' => 'Pengagum Rahasia',
    'artist' => 'Hb Fisip Ub, Grooveyard',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273dcac4bc6448ebf3d71036a8e',
    'meaning' => 'Karya "Pengagum Rahasia" oleh Hb Fisip Ub, Grooveyard melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/3USY5eGZWQuUnO1pVmse2a',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:05',
  ),
  60 => 
  array (
    'id' => 1864,
    'spotify_id' => '0AVK7svoJcxQ97mPGDH1zR',
    'title' => 'Pengagum Rahasiamu',
    'artist' => 'Radho Lumud',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ba35b3f92fafa129325fd552',
    'meaning' => 'Karya "Pengagum Rahasiamu" oleh Radho Lumud melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0AVK7svoJcxQ97mPGDH1zR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:06',
  ),
  61 => 
  array (
    'id' => 1865,
    'spotify_id' => '7jlb7IGXrGklp6USpQR7jx',
    'title' => 'Rest in Your Love',
    'artist' => 'Sandiwarap',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738f57a9a1a2bc70b6fe4917f1',
    'meaning' => 'Lagu "Rest in Your Love" karya Sandiwarap mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/7jlb7IGXrGklp6USpQR7jx',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:06',
  ),
  62 => 
  array (
    'id' => 1866,
    'spotify_id' => '2qesxmkERgsBDoZvoDkDFq',
    'title' => 'Rahasia Hati',
    'artist' => 'Element',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730263ffc0d021d1fb21cc9174',
    'meaning' => 'Karya "Rahasia Hati" oleh Element melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2qesxmkERgsBDoZvoDkDFq',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:06',
  ),
  63 => 
  array (
    'id' => 1868,
    'spotify_id' => '0WSPwTU2eVhdRoQVzMeZJt',
    'title' => 'Sulit Tuk Mencinta',
    'artist' => 'Raja Irfan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27315e7c74c95ac8733d09103d1',
    'meaning' => 'Lagu "Sulit Tuk Mencinta" karya Raja Irfan mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/0WSPwTU2eVhdRoQVzMeZJt',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:06',
  ),
  64 => 
  array (
    'id' => 1869,
    'spotify_id' => '5B4UcPazeQXMTd5Gs3klOW',
    'title' => 'Niskala',
    'artist' => 'Dandi Ganesh, Zull',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27351c5fd2f02ec3f3dea6ca5a0',
    'meaning' => 'Permohonan maaf yang tulus dan keikhlasan dilupakan demi menghapus penderitaan kekasih akibat kesalahan diri.',
    'spotify_url' => 'https://open.spotify.com/track/5B4UcPazeQXMTd5Gs3klOW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:06',
  ),
  65 => 
  array (
    'id' => 1879,
    'spotify_id' => '5SQYOu8ZP75g6LRL2WofEk',
    'title' => 'Could I',
    'artist' => 'Guerilla 810',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738774f5cb12294f3fb70296a8',
    'meaning' => 'Karya "Could I" oleh Guerilla 810 melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/5SQYOu8ZP75g6LRL2WofEk',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:20:06',
  ),
  66 => 
  array (
    'id' => 1972,
    'spotify_id' => '2P6u1e3bo4UvB9shPbx8QX',
    'title' => 'About You (Live From The AO Arena, Manchester, 17.02.24)',
    'artist' => 'The 1975',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f8c612676555cafc479e25cf',
    'meaning' => 'Perasaan nostalgia mendalam di mana setiap sudut kehidupan dan bayangan kenangan selalu mengingatkan pada satu sosok yang tak pernah benar-benar pergi dari ingatan.',
    'spotify_url' => 'https://open.spotify.com/track/2P6u1e3bo4UvB9shPbx8QX',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  67 => 
  array (
    'id' => 1974,
    'spotify_id' => '3GCdLUSnKSMJhs4Tj6CV3s',
    'title' => 'All The Stars (with SZA) - From "Black Panther: The Album"',
    'artist' => 'Kendrick Lamar, SZA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c027ad28821777b00dcaa888',
    'meaning' => 'Lagu "All The Stars (with SZA) - From "Black Panther: The Album"" karya Kendrick Lamar, SZA membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/3GCdLUSnKSMJhs4Tj6CV3s',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  68 => 
  array (
    'id' => 1975,
    'spotify_id' => '0XZW4ZKXOwo9kCyDpXGNc7',
    'title' => 'Oceans & Engines',
    'artist' => 'NIKI',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d3997a4c208ac08dafff374f',
    'meaning' => 'Karya "Oceans & Engines" oleh NIKI melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/0XZW4ZKXOwo9kCyDpXGNc7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  69 => 
  array (
    'id' => 1976,
    'spotify_id' => '2FTeQQ5Rg9tBpgpTF5mnhE',
    'title' => 'Still Think About You',
    'artist' => 'A Boogie Wit da Hoodie',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f2baf6d743ae26f97777f026',
    'meaning' => 'Perasaan nostalgia mendalam di mana setiap sudut kehidupan dan bayangan kenangan selalu mengingatkan pada satu sosok yang tak pernah benar-benar pergi dari ingatan.',
    'spotify_url' => 'https://open.spotify.com/track/2FTeQQ5Rg9tBpgpTF5mnhE',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  70 => 
  array (
    'id' => 1977,
    'spotify_id' => '04a44cx2PJthIbN2aLMXhl',
    'title' => 'TIT FOR TAT',
    'artist' => 'Tate McRae',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d0401a5b4ca2a799cd599abf',
    'meaning' => 'Karya "TIT FOR TAT" oleh Tate McRae melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/04a44cx2PJthIbN2aLMXhl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  71 => 
  array (
    'id' => 1978,
    'spotify_id' => '1dByUyyoRKL99fJJ6VCQzb',
    'title' => 'TIT FOR TAT',
    'artist' => 'Tate McRae',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c40dccc1952bb5ed96986869',
    'meaning' => 'Karya "TIT FOR TAT" oleh Tate McRae melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/1dByUyyoRKL99fJJ6VCQzb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  72 => 
  array (
    'id' => 1979,
    'spotify_id' => '2LD9hy8QAphFB9pS9Tbp3W',
    'title' => 'You Could Know As Much About A Stranger',
    'artist' => 'Gene Watson',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27391834e432a93d7c486d25088',
    'meaning' => 'Karya "You Could Know As Much About A Stranger" oleh Gene Watson melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2LD9hy8QAphFB9pS9Tbp3W',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:01',
  ),
  73 => 
  array (
    'id' => 1993,
    'spotify_id' => '4m0q0xQ2BNl9SCAGKyfiGZ',
    'title' => 'Somebody Else',
    'artist' => 'The 1975',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273206517a3f7e4c34bf0bfc531',
    'meaning' => 'Karya "Somebody Else" oleh The 1975 melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/4m0q0xQ2BNl9SCAGKyfiGZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:02',
  ),
  74 => 
  array (
    'id' => 1994,
    'spotify_id' => '709ZIqPHyFOpx2QdjmeWAM',
    'title' => 'Dracula',
    'artist' => 'Tame Impala',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734806a1c10aa685b1b936158b',
    'meaning' => 'Karya "Dracula" oleh Tame Impala melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/709ZIqPHyFOpx2QdjmeWAM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:02',
  ),
  75 => 
  array (
    'id' => 1996,
    'spotify_id' => '2FAZskT9yRjp2Oow9szJD8',
    'title' => 'The Days - NOTION Remix',
    'artist' => 'Chrystal, NOTION',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739041b9965925059507fb44af',
    'meaning' => 'Karya "The Days - NOTION Remix" oleh Chrystal, NOTION melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2FAZskT9yRjp2Oow9szJD8',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:02',
  ),
  76 => 
  array (
    'id' => 1997,
    'spotify_id' => '5FMCBVnugUvShPqgxBFDpU',
    'title' => 'Worried About You - Live At The El Mocambo 1977',
    'artist' => 'The Rolling Stones',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732ca908eb9f3741338ec8d5d9',
    'meaning' => 'Perasaan nostalgia mendalam di mana setiap sudut kehidupan dan bayangan kenangan selalu mengingatkan pada satu sosok yang tak pernah benar-benar pergi dari ingatan.',
    'spotify_url' => 'https://open.spotify.com/track/5FMCBVnugUvShPqgxBFDpU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:02',
  ),
  77 => 
  array (
    'id' => 1998,
    'spotify_id' => '3zEN0ii6s4DHHBpnTp3RP7',
    'title' => 'We Are The People',
    'artist' => 'Empire Of The Sun',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f3aa0e6ca22a382007f61e4d',
    'meaning' => 'Lagu "We Are The People" karya Empire Of The Sun menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/3zEN0ii6s4DHHBpnTp3RP7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:02',
  ),
  78 => 
  array (
    'id' => 1999,
    'spotify_id' => '5o47ZqRTyHccIrzHna2mNf',
    'title' => 'Something There Is About You - Live at Madison Square Garden, New York City, NY - January 30, 1974',
    'artist' => 'Bob Dylan, The Band',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ade1f3c9f6338d412045f65a',
    'meaning' => 'Perasaan nostalgia mendalam di mana setiap sudut kehidupan dan bayangan kenangan selalu mengingatkan pada satu sosok yang tak pernah benar-benar pergi dari ingatan.',
    'spotify_url' => 'https://open.spotify.com/track/5o47ZqRTyHccIrzHna2mNf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:02',
  ),
  79 => 
  array (
    'id' => 2010,
    'spotify_id' => '2YRHj7X19faZv4WZZ3JnZq',
    'title' => 'iqro\'',
    'artist' => 'Raim Laode',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e455819f67875ffb8d96e837',
    'meaning' => 'Karya "iqro\'" oleh Raim Laode melukiskan perasaan mendalam tentang bisikan emosi, harapan tersirat, serta ikatan jiwa yang terukir indah dalam tiap alunan nadanya.',
    'spotify_url' => 'https://open.spotify.com/track/2YRHj7X19faZv4WZZ3JnZq',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:04',
  ),
);
$allLocalSongs = [];
$allMessages = [];
require __DIR__ . '/migration_common.php';
?>
