<?php
$batchNum = 7;
$isLastBatch = false;
$batchSongs = array (
  0 => 
  array (
    'id' => 2234,
    'spotify_id' => '4LeP389CNcbrQX8ZECZlPw',
    'title' => 'Terakhir',
    'artist' => 'Sufian Suhaimi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733d5d2fb9ce449eb563ace97a',
    'meaning' => 'Ungkapan perpisahan terakhir dan penghormatan setinggi-tingginya kepada kekasih jiwa yang tak tergantikan.',
    'spotify_url' => 'https://open.spotify.com/track/4LeP389CNcbrQX8ZECZlPw',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  1 => 
  array (
    'id' => 2235,
    'spotify_id' => '0BD9boQC7jUTWkAoib4Z0d',
    'title' => 'Meleğim',
    'artist' => 'Soolking, Dadju',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b28db1e5c8c53e67c6969c06',
    'meaning' => 'Lagu "Meleğim" karya Soolking, Dadju mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0BD9boQC7jUTWkAoib4Z0d',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  2 => 
  array (
    'id' => 2236,
    'spotify_id' => '6yCjU5j6YHbux2VQCBTTE1',
    'title' => 'Tu jardín con enanitos',
    'artist' => 'Melendi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273420c7ba982f6f92351fc0a2b',
    'meaning' => 'Lagu "Tu jardín con enanitos" karya Melendi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6yCjU5j6YHbux2VQCBTTE1',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  3 => 
  array (
    'id' => 2237,
    'spotify_id' => '2sMxswHr9wX7kTUHULvJBJ',
    'title' => 'Destino o casualidad',
    'artist' => 'Melendi, Ha*Ash',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734306fd3cc49f5da4417ed1f2',
    'meaning' => 'Lagu "Destino o casualidad" karya Melendi, Ha*Ash mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2sMxswHr9wX7kTUHULvJBJ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  4 => 
  array (
    'id' => 2241,
    'spotify_id' => '3rpwAgSsnId9fCoogNeJCt',
    'title' => 'Kau Masih Kekasihku',
    'artist' => 'NaFF',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733fdee3a1eae6c6ecffdeadc3',
    'meaning' => 'Lagu "Kau Masih Kekasihku" karya NaFF mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/3rpwAgSsnId9fCoogNeJCt',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  5 => 
  array (
    'id' => 2243,
    'spotify_id' => '7u86WTK3SPdT0cA0vgSbwe',
    'title' => 'Melepaskanmu',
    'artist' => 'Kaleb J',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273012ff0707d787fc1c1508930',
    'meaning' => 'Lagu "Melepaskanmu" karya Kaleb J mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/7u86WTK3SPdT0cA0vgSbwe',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  6 => 
  array (
    'id' => 2244,
    'spotify_id' => '3g0zKSpa5uA0mibXdSaLRb',
    'title' => 'Melepasmu',
    'artist' => 'Drive',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732efabab3982ab74de8d3dc4e',
    'meaning' => 'Keberanian dan keikhlasan hati untuk merelakan sosok kekasih pergi ketika menyadari jiwanya tak lagi ada untuk kita.',
    'spotify_url' => 'https://open.spotify.com/track/3g0zKSpa5uA0mibXdSaLRb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  7 => 
  array (
    'id' => 2246,
    'spotify_id' => '1CopCjPsJ1HQYPudZ0SRbO',
    'title' => 'Melepaskanmu',
    'artist' => 'The Valt',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27306d6a892f7f7522d8207598e',
    'meaning' => 'Lagu "Melepaskanmu" karya The Valt mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/1CopCjPsJ1HQYPudZ0SRbO',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  8 => 
  array (
    'id' => 2247,
    'spotify_id' => '0JfUFx2MxBIkYfGjhft80f',
    'title' => 'Melepaskanmu',
    'artist' => 'Sakura Band',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738713cacdecfa74a87dbc972e',
    'meaning' => 'Lagu "Melepaskanmu" karya Sakura Band mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/0JfUFx2MxBIkYfGjhft80f',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  9 => 
  array (
    'id' => 2265,
    'spotify_id' => '2dIBMHByUGcNPzmYBJ6OAj',
    'title' => 'Evaluasi',
    'artist' => 'Hindia',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d623688488865906052ef96b',
    'meaning' => 'Lagu "Evaluasi" karya Hindia mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2dIBMHByUGcNPzmYBJ6OAj',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  10 => 
  array (
    'id' => 2267,
    'spotify_id' => '5sfqofsV9JjNPgc9rFh1eL',
    'title' => 'Melepas Senja',
    'artist' => 'KenjiTri, Zaidir Burhan, Emiel Kurnia, Sho Dehira',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ec456785badc01e3fe240172',
    'meaning' => 'Lagu "Melepas Senja" karya KenjiTri, Zaidir Burhan, Emiel Kurnia, Sho Dehira mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5sfqofsV9JjNPgc9rFh1eL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  11 => 
  array (
    'id' => 2270,
    'spotify_id' => '70GUGyk1sJYFTqZpSJj2KM',
    'title' => 'Di Ujung Jalan',
    'artist' => 'SAMSONS',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27317f5145bfb22a8ca721c6812',
    'meaning' => 'Lagu "Di Ujung Jalan" karya SAMSONS mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/70GUGyk1sJYFTqZpSJj2KM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  12 => 
  array (
    'id' => 2273,
    'spotify_id' => '6l9L0ssWzD5XI1aJgVFpaS',
    'title' => 'Mengenangmu',
    'artist' => 'Kerispatih',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734986516d6ce56f0d19cdc41d',
    'meaning' => 'Lagu "Mengenangmu" karya Kerispatih mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6l9L0ssWzD5XI1aJgVFpaS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  13 => 
  array (
    'id' => 2274,
    'spotify_id' => '7kc1RYFM6SYM6pevFlrZlB',
    'title' => 'Melepasmu',
    'artist' => 'Difarina Indra Adella',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273610f210424fac0f2f05436e3',
    'meaning' => 'Keberanian dan keikhlasan hati untuk merelakan sosok kekasih pergi ketika menyadari jiwanya tak lagi ada untuk kita.',
    'spotify_url' => 'https://open.spotify.com/track/7kc1RYFM6SYM6pevFlrZlB',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  14 => 
  array (
    'id' => 2276,
    'spotify_id' => '3s3Rs7L4bymkiyXurBtqvM',
    'title' => 'Tak Mungkin Ku Melepasmu (feat. Andina)',
    'artist' => 'Dygta, Andina',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f83db6d60641b4da72829d3c',
    'meaning' => 'Keberanian dan keikhlasan hati untuk merelakan sosok kekasih pergi ketika menyadari jiwanya tak lagi ada untuk kita.',
    'spotify_url' => 'https://open.spotify.com/track/3s3Rs7L4bymkiyXurBtqvM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:54',
  ),
  15 => 
  array (
    'id' => 2421,
    'spotify_id' => '2n8ahxBEyotfmkDbIGaTID',
    'title' => 'Perceraian Lara',
    'artist' => 'Ipank',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27329e0c3c8437c12d127449672',
    'meaning' => 'Lagu "Perceraian Lara" karya Ipank mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2n8ahxBEyotfmkDbIGaTID',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  16 => 
  array (
    'id' => 2424,
    'spotify_id' => '6XD6sH8A7G4NiuKVuaI5yw',
    'title' => 'Pergilah Kau',
    'artist' => 'Sherina Munaf',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27352b52a9d8361bbfd60f76415',
    'meaning' => 'Lagu "Pergilah Kau" karya Sherina Munaf mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/6XD6sH8A7G4NiuKVuaI5yw',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  17 => 
  array (
    'id' => 2425,
    'spotify_id' => '3NLnwwAQbbFKcEcV8hDItk',
    'title' => 'Perfect',
    'artist' => 'One Direction',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734a075ca70ae4143a37eb4fbe',
    'meaning' => 'Lagu romantisme sejati tentang menemukan pasangan hidup sejak masa muda dan membangun harapan serta impian masa depan bersama.',
    'spotify_url' => 'https://open.spotify.com/track/3NLnwwAQbbFKcEcV8hDItk',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  18 => 
  array (
    'id' => 2426,
    'spotify_id' => '41P6Tnd8KIHqON0QIydx6a',
    'title' => 'the perfect pair',
    'artist' => 'beabadoobee',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273384d10f967c2b914de7e2713',
    'meaning' => 'Lagu romantisme sejati tentang menemukan pasangan hidup sejak masa muda dan membangun harapan serta impian masa depan bersama.',
    'spotify_url' => 'https://open.spotify.com/track/41P6Tnd8KIHqON0QIydx6a',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  19 => 
  array (
    'id' => 2427,
    'spotify_id' => '3w1h7uNU1Dfk2tOaHiIGat',
    'title' => 'PERO NO TE ENAMORES',
    'artist' => 'Fuerza Regida',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27358f920f157b29869020a0f0d',
    'meaning' => 'Lagu "PERO NO TE ENAMORES" karya Fuerza Regida mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3w1h7uNU1Dfk2tOaHiIGat',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  20 => 
  array (
    'id' => 2429,
    'spotify_id' => '4YxEeCKhUl1DawPzsxCPbq',
    'title' => 'Peradaban',
    'artist' => '.Feast',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a8701a073f15323f29e39d56',
    'meaning' => 'Lagu "Peradaban" karya .Feast mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4YxEeCKhUl1DawPzsxCPbq',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  21 => 
  array (
    'id' => 2430,
    'spotify_id' => '1RyqmamAZTAB9WSZpX4S3f',
    'title' => 'perayaan mati rasa',
    'artist' => 'Umay Shahab, Natania Karin',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737bd45a97ae19bfec2197d3f8',
    'meaning' => 'Proses penerimaan rasa sakit hati setelah kekecewaan besar, hingga mencapai titik di mana perasaan luka berubah menjadi mati rasa yang sunyi.',
    'spotify_url' => 'https://open.spotify.com/track/1RyqmamAZTAB9WSZpX4S3f',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/5c/29/81/5c2981f4-b00d-31c9-1b8d-f282c317672e/mzaf_10520829442049114238.plus.aac.p.m4a',
    'created_at' => '2026-08-05 11:42:56',
  ),
  22 => 
  array (
    'id' => 2431,
    'spotify_id' => '5SbrY0QeN03TpEXT9l29GR',
    'title' => 'Perahu Kertas',
    'artist' => 'Maudy Ayunda',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734ee6c0713af0507f42e13b02',
    'meaning' => 'Lagu "Perahu Kertas" karya Maudy Ayunda mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5SbrY0QeN03TpEXT9l29GR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  23 => 
  array (
    'id' => 2432,
    'spotify_id' => '38yM3PwNtTSsb8UqEgqaUl',
    'title' => 'Kami Belum Tentu',
    'artist' => '.Feast',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734882b70b50a67a05b132ec06',
    'meaning' => 'Lagu "Kami Belum Tentu" karya .Feast mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/38yM3PwNtTSsb8UqEgqaUl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  24 => 
  array (
    'id' => 2433,
    'spotify_id' => '4Og4juk5rJcl5lLjq8e7gM',
    'title' => 'Perahu Kertas',
    'artist' => 'Rainyst',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739cba315371e562efa1911587',
    'meaning' => 'Lagu "Perahu Kertas" karya Rainyst mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4Og4juk5rJcl5lLjq8e7gM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  25 => 
  array (
    'id' => 2434,
    'spotify_id' => '4Y6adQKCHeDlTBtgY4w6kz',
    'title' => 'Prau Layar',
    'artist' => 'Niken Salindry',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734b53032b18c7bfab03af3c01',
    'meaning' => 'Lagu "Prau Layar" karya Niken Salindry mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4Y6adQKCHeDlTBtgY4w6kz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  26 => 
  array (
    'id' => 2435,
    'spotify_id' => '7FASTpnu9gXtBb5T3vkJer',
    'title' => 'Perayaan Patah Hati',
    'artist' => 'For Revenge, Wira Nagara',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273322ce4ba8eb959ebee609fd8',
    'meaning' => 'Lagu "Perayaan Patah Hati" karya For Revenge, Wira Nagara mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/7FASTpnu9gXtBb5T3vkJer',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  27 => 
  array (
    'id' => 2436,
    'spotify_id' => '3OQBF9W7op3SL6Dp7tjxZF',
    'title' => 'Perawan Atau Janda',
    'artist' => 'Cita Citata',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ac3054c40113448b3dc29306',
    'meaning' => 'Lagu "Perawan Atau Janda" karya Cita Citata mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3OQBF9W7op3SL6Dp7tjxZF',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  28 => 
  array (
    'id' => 2437,
    'spotify_id' => '1rvDerPMTjVKtMkMdLwxmS',
    'title' => 'Peranbae (From "Modern Love Chennai")',
    'artist' => 'Yuvan Shankar Raja, Shivani Panneerselvam',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27397ad8529813cc171faae2fe5',
    'meaning' => 'Lagu "Peranbae (From "Modern Love Chennai")" karya Yuvan Shankar Raja, Shivani Panneerselvam mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/1rvDerPMTjVKtMkMdLwxmS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:56',
  ),
  29 => 
  array (
    'id' => 2442,
    'spotify_id' => '0v0XEH9pzcIPKrehl914ky',
    'title' => 'Laut',
    'artist' => 'Midnight Serenade',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735ec8efb857a83fb36d6d5305',
    'meaning' => 'Lagu "Laut" karya Midnight Serenade mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0v0XEH9pzcIPKrehl914ky',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  30 => 
  array (
    'id' => 2443,
    'spotify_id' => '0bo1p4mHN913d1MgixiHLo',
    'title' => 'Perayaan Patah Hati',
    'artist' => 'For Revenge, Wira Nagara',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ed10d729acb683dca01e0254',
    'meaning' => 'Lagu "Perayaan Patah Hati" karya For Revenge, Wira Nagara mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/0bo1p4mHN913d1MgixiHLo',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  31 => 
  array (
    'id' => 2444,
    'spotify_id' => '6AyBbSvcR2ZwTeR30I4jb9',
    'title' => 'Jakarta Hari Ini',
    'artist' => 'For Revenge, Stereo Wall',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273322ce4ba8eb959ebee609fd8',
    'meaning' => 'Lagu "Jakarta Hari Ini" karya For Revenge, Stereo Wall mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6AyBbSvcR2ZwTeR30I4jb9',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  32 => 
  array (
    'id' => 2445,
    'spotify_id' => '0PtJbtW50jcvvswNPn3QGd',
    'title' => 'Serana',
    'artist' => 'For Revenge',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273322ce4ba8eb959ebee609fd8',
    'meaning' => 'Lagu "Serana" karya For Revenge mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0PtJbtW50jcvvswNPn3QGd',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  33 => 
  array (
    'id' => 2447,
    'spotify_id' => '7cvMLxZM9rUfFTaG6d5DJl',
    'title' => 'Percaya Padaku',
    'artist' => 'Ungu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27376db3518dda8015865411eb4',
    'meaning' => 'Lagu "Percaya Padaku" karya Ungu mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7cvMLxZM9rUfFTaG6d5DJl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  34 => 
  array (
    'id' => 2456,
    'spotify_id' => '66jc8XdpNaiiskmo2nSvjG',
    'title' => 'Raya',
    'artist' => 'The Kick',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730e63028eb5ee9d8a0593528a',
    'meaning' => 'Proses penerimaan rasa sakit hati setelah kekecewaan besar, hingga mencapai titik di mana perasaan luka berubah menjadi mati rasa yang sunyi.',
    'spotify_url' => 'https://open.spotify.com/track/66jc8XdpNaiiskmo2nSvjG',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  35 => 
  array (
    'id' => 2457,
    'spotify_id' => '0zAtj0BEvpulETGrk95NPQ',
    'title' => 'Rayuan Perempuan Gila',
    'artist' => 'Nadin Amizah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27394847679fe7b10e27d9803f5',
    'meaning' => 'Lagu "Rayuan Perempuan Gila" karya Nadin Amizah mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0zAtj0BEvpulETGrk95NPQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:42:57',
  ),
  36 => 
  array (
    'id' => 2479,
    'spotify_id' => '35o9a4iAfLl5jRmqMX9c1D',
    'title' => 'Shape of My Heart',
    'artist' => 'Backstreet Boys',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273cf871e6326e334bfa92cff20',
    'meaning' => 'Ungkapan ketulusan hati yang menyerahkan seluruh cinta dan kehangatan kepada pasangan tanpa syarat.',
    'spotify_url' => 'https://open.spotify.com/track/35o9a4iAfLl5jRmqMX9c1D',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  37 => 
  array (
    'id' => 2480,
    'spotify_id' => '4qW3BbQAwZsrnu8a3ZRdyT',
    'title' => 'Self Aware',
    'artist' => 'Temper City',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d6c26d2ae723f7ab553d64cc',
    'meaning' => 'Lagu "Self Aware" karya Temper City mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4qW3BbQAwZsrnu8a3ZRdyT',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  38 => 
  array (
    'id' => 2481,
    'spotify_id' => '5gkTGkjFB5wAd3mSBEcQPY',
    'title' => 'Sephia',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e8d4f0596d66ccbe5241918d',
    'meaning' => 'Lagu "Sephia" karya Sheila On 7 mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5gkTGkjFB5wAd3mSBEcQPY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  39 => 
  array (
    'id' => 2483,
    'spotify_id' => '3R0FDwQSXOiO5gaOZFxKZ5',
    'title' => 'Sweet Scar',
    'artist' => 'Weird Genius, Prince Husein, Eka Gustiwana, Reza Oktovian, Billy Taner',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273878148e61fdb2357925e8bdf',
    'meaning' => 'Lagu "Sweet Scar" karya Weird Genius, Prince Husein, Eka Gustiwana, Reza Oktovian, Billy Taner mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/3R0FDwQSXOiO5gaOZFxKZ5',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  40 => 
  array (
    'id' => 2484,
    'spotify_id' => '3psZu1wcmAoyWrL9RB3y08',
    'title' => 'Sang Badut',
    'artist' => 'Raim Laode',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f26773f6fedf911fa80877bc',
    'meaning' => 'Lagu "Sang Badut" karya Raim Laode mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3psZu1wcmAoyWrL9RB3y08',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  41 => 
  array (
    'id' => 2485,
    'spotify_id' => '7vGuf3Y35N4wmASOKLUVVU',
    'title' => 'Silence',
    'artist' => 'Marshmello, Khalid',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f33ba583059dc2f7d08bf2b8',
    'meaning' => 'Lagu "Silence" karya Marshmello, Khalid mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7vGuf3Y35N4wmASOKLUVVU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  42 => 
  array (
    'id' => 2487,
    'spotify_id' => '68lbSrXDORS51pmyjZv712',
    'title' => 'SWIM',
    'artist' => 'BTS',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273dfa17fad7f190c901603270e',
    'meaning' => 'Lagu "SWIM" karya BTS mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/68lbSrXDORS51pmyjZv712',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  43 => 
  array (
    'id' => 2490,
    'spotify_id' => '5Ohxk2dO5COHF1krpoPigN',
    'title' => 'Sign of the Times',
    'artist' => 'Harry Styles',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733f8b8a9c71b2bd2f3019940b',
    'meaning' => 'Lagu "Sign of the Times" karya Harry Styles mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5Ohxk2dO5COHF1krpoPigN',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  44 => 
  array (
    'id' => 2491,
    'spotify_id' => '7qYyRmqHPwfsNsCyW2WBdY',
    'title' => 'Siapa Di Hatimu',
    'artist' => 'Rahmat',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733b4a79efc6d6fea5209340f3',
    'meaning' => 'Lagu "Siapa Di Hatimu" karya Rahmat mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7qYyRmqHPwfsNsCyW2WBdY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  45 => 
  array (
    'id' => 2493,
    'spotify_id' => '05JCo2qLuSp6Tm4yzqh95Z',
    'title' => 'Sinarengan',
    'artist' => 'Denny Caknan, Bella Bonita',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27352cccf4dabb654281db4b092',
    'meaning' => 'Lagu "Sinarengan" karya Denny Caknan, Bella Bonita mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/05JCo2qLuSp6Tm4yzqh95Z',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:35',
  ),
  46 => 
  array (
    'id' => 2494,
    'spotify_id' => '6O0WEM0QNEhqpU50BKui7o',
    'title' => 'Sial',
    'artist' => 'Mahalini',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736f713eb92ebf7ca05a562542',
    'meaning' => 'Lagu "Sial" karya Mahalini mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6O0WEM0QNEhqpU50BKui7o',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  47 => 
  array (
    'id' => 2495,
    'spotify_id' => '2aDgJHhAbABvdW9NszrAPQ',
    'title' => 'Sialan',
    'artist' => 'Adrian Khalif, Juicy Luicy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c1b41bef62365566a42821bd',
    'meaning' => 'Lagu "Sialan" karya Adrian Khalif, Juicy Luicy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2aDgJHhAbABvdW9NszrAPQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  48 => 
  array (
    'id' => 2496,
    'spotify_id' => '21jGcNKet2qwijlDFuPiPb',
    'title' => 'Circles',
    'artist' => 'Post Malone',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739478c87599550dd73bfa7e02',
    'meaning' => 'Lagu "Circles" karya Post Malone mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/21jGcNKet2qwijlDFuPiPb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  49 => 
  array (
    'id' => 2497,
    'spotify_id' => '6YUTL4dYpB9xZO5qExPf05',
    'title' => 'Summer',
    'artist' => 'Calvin Harris',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738fba5806a323efd272677c4d',
    'meaning' => 'Lagu "Summer" karya Calvin Harris mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6YUTL4dYpB9xZO5qExPf05',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  50 => 
  array (
    'id' => 2498,
    'spotify_id' => '2YVsc4kpRJVFCvEPPN0HF0',
    'title' => 'MUTIARA',
    'artist' => 'Laila Ayu, Irwan D\'Academy, SIMPATIK MUSIC',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ae3355d012f96d381bd72b69',
    'meaning' => 'Lagu "MUTIARA" karya Laila Ayu, Irwan D\'Academy, SIMPATIK MUSIC mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2YVsc4kpRJVFCvEPPN0HF0',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  51 => 
  array (
    'id' => 2499,
    'spotify_id' => '7qaUeAyg0eYYhHDCx58GXa',
    'title' => 'Simplesmente Ela',
    'artist' => 'Mc Gabzin, DJ Marcus Vinicius',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ac55edb96457b3d6427d149b',
    'meaning' => 'Lagu "Simplesmente Ela" karya Mc Gabzin, DJ Marcus Vinicius mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7qaUeAyg0eYYhHDCx58GXa',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  52 => 
  array (
    'id' => 2500,
    'spotify_id' => '6grfR5nHeNzzKcmEyllLZ2',
    'title' => 'Simpan Rasa',
    'artist' => 'Vadel Nasir',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731e9e419bb7b6ca257e044294',
    'meaning' => 'Lagu "Simpan Rasa" karya Vadel Nasir mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/6grfR5nHeNzzKcmEyllLZ2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  53 => 
  array (
    'id' => 2501,
    'spotify_id' => '4j3X4KX8rURekAVIFUhI23',
    'title' => 'Perfect',
    'artist' => 'Simple Plan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273fbee462a3aa4e7ea05e07aa5',
    'meaning' => 'Lagu romantisme sejati tentang menemukan pasangan hidup sejak masa muda dan membangun harapan serta impian masa depan bersama.',
    'spotify_url' => 'https://open.spotify.com/track/4j3X4KX8rURekAVIFUhI23',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  54 => 
  array (
    'id' => 2502,
    'spotify_id' => '5HbQ8H511rysCzppm22YSR',
    'title' => 'Keliling',
    'artist' => 'Farrel Hilal',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273279dd2da85d569e7daba5363',
    'meaning' => 'Lagu "Keliling" karya Farrel Hilal mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5HbQ8H511rysCzppm22YSR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  55 => 
  array (
    'id' => 2503,
    'spotify_id' => '2z8EdqzcH8qq6rwqaC2zXp',
    'title' => 'Andai Tak Berpisah',
    'artist' => 'SIMPATIK MUSIC, Laila Ayu, Irwan D\'Academy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737c55f59c5eacc436abe42e2d',
    'meaning' => 'Lagu "Andai Tak Berpisah" karya SIMPATIK MUSIC, Laila Ayu, Irwan D\'Academy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2z8EdqzcH8qq6rwqaC2zXp',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  56 => 
  array (
    'id' => 2504,
    'spotify_id' => '10rChmECwPcvTTj4w07hq4',
    'title' => 'Welcome to My Life',
    'artist' => 'Simple Plan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736cb8cbc645eebdfc0ebffa72',
    'meaning' => 'Lagu "Welcome to My Life" karya Simple Plan mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/10rChmECwPcvTTj4w07hq4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  57 => 
  array (
    'id' => 2505,
    'spotify_id' => '72gv4zhNvRVdQA0eOenCal',
    'title' => 'Symphony (feat. Zara Larsson)',
    'artist' => 'Clean Bandit, Zara Larsson',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735c66e925d8fe4c92ebfb49ed',
    'meaning' => 'Lagu "Symphony (feat. Zara Larsson)" karya Clean Bandit, Zara Larsson mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/72gv4zhNvRVdQA0eOenCal',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  58 => 
  array (
    'id' => 2506,
    'spotify_id' => '1ju7EsSGvRybSNEsRvc7qY',
    'title' => 'Simple Man',
    'artist' => 'Lynyrd Skynyrd',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273128450651c9f0442780d8eb8',
    'meaning' => 'Lagu "Simple Man" karya Lynyrd Skynyrd mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1ju7EsSGvRybSNEsRvc7qY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  59 => 
  array (
    'id' => 2507,
    'spotify_id' => '42et6fnHCw1HIPSrdPprMl',
    'title' => 'Semi-Charmed Life',
    'artist' => 'Third Eye Blind',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730c12ef918102b8d303dc9e9b',
    'meaning' => 'Lagu "Semi-Charmed Life" karya Third Eye Blind mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/42et6fnHCw1HIPSrdPprMl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:36',
  ),
  60 => 
  array (
    'id' => 2514,
    'spotify_id' => '0I329vpTJRdSRjEcWaQsSL',
    'title' => 'Jet Lag (feat. Natasha Bedingfield)',
    'artist' => 'Simple Plan, Natasha Bedingfield',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273de7ba7b8ecfb253e4550f357',
    'meaning' => 'Lagu "Jet Lag (feat. Natasha Bedingfield)" karya Simple Plan, Natasha Bedingfield mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0I329vpTJRdSRjEcWaQsSL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  61 => 
  array (
    'id' => 2517,
    'spotify_id' => '1rluwEqsWp5tz0lgyOT9rE',
    'title' => 'Symphonia IX',
    'artist' => 'Current Joys',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e341c520c154f89b77bd2aaf',
    'meaning' => 'Lagu "Symphonia IX" karya Current Joys mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1rluwEqsWp5tz0lgyOT9rE',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  62 => 
  array (
    'id' => 2519,
    'spotify_id' => '5iSHWeTO5NuYZTeCvIrMi5',
    'title' => 'Bahtera Cinta',
    'artist' => 'Fira Cantika, Irwan Krisdiyanto',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738fc26f3b9b5a88effc810310',
    'meaning' => 'Lagu "Bahtera Cinta" karya Fira Cantika, Irwan Krisdiyanto mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/5iSHWeTO5NuYZTeCvIrMi5',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  63 => 
  array (
    'id' => 2520,
    'spotify_id' => '2FGtRcojr2wSfT17Cf9Zha',
    'title' => 'Negoro Angin',
    'artist' => 'SIMPATIK MUSIC',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27318da1758aa66c7184e6f5f19',
    'meaning' => 'Lagu "Negoro Angin" karya SIMPATIK MUSIC mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2FGtRcojr2wSfT17Cf9Zha',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  64 => 
  array (
    'id' => 2521,
    'spotify_id' => '2qiODpF8mTIV4n5OqIygHn',
    'title' => 'Simpan Saja',
    'artist' => 'Ecoutez',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27377e6c8d1267a29a7707ec6e3',
    'meaning' => 'Keputusan untuk memendam perasaan cinta secara rahasia demi menjaga hubungan dan menghindari kekecewaan.',
    'spotify_url' => 'https://open.spotify.com/track/2qiODpF8mTIV4n5OqIygHn',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  65 => 
  array (
    'id' => 2524,
    'spotify_id' => '1VUOKxi7G93zZWsUuXotj2',
    'title' => 'Gadis manis kalimantan',
    'artist' => 'Laila Ayu, SIMPATIK MUSIC',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c2459e19a9f41c460c91d061',
    'meaning' => 'Lagu "Gadis manis kalimantan" karya Laila Ayu, SIMPATIK MUSIC mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1VUOKxi7G93zZWsUuXotj2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  66 => 
  array (
    'id' => 2525,
    'spotify_id' => '5fIrBv7PrI2MBcktQOcmpI',
    'title' => 'Sympathy',
    'artist' => 'The Goo Goo Dolls',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739923ca569ea4d53394c0146e',
    'meaning' => 'Lagu "Sympathy" karya The Goo Goo Dolls mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5fIrBv7PrI2MBcktQOcmpI',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  67 => 
  array (
    'id' => 2526,
    'spotify_id' => '4tsoU0ExMe36q2iwSITO5M',
    'title' => 'Sympa',
    'artist' => 'Drift State',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c0aa4e86d8cd897c21004d34',
    'meaning' => 'Lagu "Sympa" karya Drift State mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4tsoU0ExMe36q2iwSITO5M',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  68 => 
  array (
    'id' => 2527,
    'spotify_id' => '5qGx6HUkOxs0NGvPzn9qrz',
    'title' => 'Simplemente Amigos',
    'artist' => 'Ana Gabriel',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273516c015640580ae7a7bdd5fd',
    'meaning' => 'Lagu "Simplemente Amigos" karya Ana Gabriel mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5qGx6HUkOxs0NGvPzn9qrz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:37',
  ),
  69 => 
  array (
    'id' => 2530,
    'spotify_id' => '46ctE3rvCIT5bfVpexI7m4',
    'title' => 'Simpan Saja',
    'artist' => 'Ecoutez',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a71a4ccf37db17959e63d15d',
    'meaning' => 'Keputusan untuk memendam perasaan cinta secara rahasia demi menjaga hubungan dan menghindari kekecewaan.',
    'spotify_url' => 'https://open.spotify.com/track/46ctE3rvCIT5bfVpexI7m4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  70 => 
  array (
    'id' => 2531,
    'spotify_id' => '5fWwmLrK01zpWcKGrT09O5',
    'title' => 'Simpang Limo Ninggal Janji',
    'artist' => 'Yeni Inka',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d565c86a1652d7e4f8f95c4d',
    'meaning' => 'Lagu "Simpang Limo Ninggal Janji" karya Yeni Inka mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5fWwmLrK01zpWcKGrT09O5',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  71 => 
  array (
    'id' => 2532,
    'spotify_id' => '66N0VimAomKQNsJPaYditU',
    'title' => 'Simpang Lima Ninggal Janji',
    'artist' => 'Janur Kuning',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273734d7cc99bf195ef7fa68c1b',
    'meaning' => 'Lagu "Simpang Lima Ninggal Janji" karya Janur Kuning mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/66N0VimAomKQNsJPaYditU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  72 => 
  array (
    'id' => 2533,
    'spotify_id' => '4mU8qRUCFp0vyKvZ7jbNZt',
    'title' => 'Simpan Cintaku',
    'artist' => 'DNANDA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737eb7abc7ac227dcb70f73cb1',
    'meaning' => 'Lagu "Simpan Cintaku" karya DNANDA mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/4mU8qRUCFp0vyKvZ7jbNZt',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  73 => 
  array (
    'id' => 2534,
    'spotify_id' => '72NkBT6mTJrPbMraGz1HJO',
    'title' => 'Simpan 25',
    'artist' => 'Ethismos, Dimitris Koufoudakis',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735bd318ca56cf91d76ea8c6b0',
    'meaning' => 'Lagu "Simpan 25" karya Ethismos, Dimitris Koufoudakis mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/72NkBT6mTJrPbMraGz1HJO',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  74 => 
  array (
    'id' => 2535,
    'spotify_id' => '6T7auNufUswgvcPErsmTPY',
    'title' => 'Simpan Rasa',
    'artist' => 'Adri Saranga',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273558624b11448846adefa95cd',
    'meaning' => 'Lagu "Simpan Rasa" karya Adri Saranga mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/6T7auNufUswgvcPErsmTPY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  75 => 
  array (
    'id' => 2536,
    'spotify_id' => '0YCKakFdUjP9Tzl0HCRUrE',
    'title' => 'Simpul',
    'artist' => 'Fadhilah Intan, Daniesh Suffian',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734ce35e1b06ff29da7f27562f',
    'meaning' => 'Lagu "Simpul" karya Fadhilah Intan, Daniesh Suffian mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0YCKakFdUjP9Tzl0HCRUrE',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  76 => 
  array (
    'id' => 2537,
    'spotify_id' => '5Szv2HkFVcUMlvvAm1Vl3n',
    'title' => 'Simpul',
    'artist' => 'Swellow',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27386de6861d65c40301301e044',
    'meaning' => 'Lagu "Simpul" karya Swellow mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5Szv2HkFVcUMlvvAm1Vl3n',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:54:39',
  ),
  77 => 
  array (
    'id' => 2551,
    'spotify_id' => '1SQsMiTpXb6X8fP6tiXfLs',
    'title' => 'Simpan Saja',
    'artist' => 'Muthia Nadhira',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27355613fcee1d1124b778a3465',
    'meaning' => 'Keputusan untuk memendam perasaan cinta secara rahasia demi menjaga hubungan dan menghindari kekecewaan.',
    'spotify_url' => 'https://open.spotify.com/track/1SQsMiTpXb6X8fP6tiXfLs',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/93/2f/f9/932ff99f-dd9d-a206-1ef8-872c350ee4df/mzaf_10040230541852752717.plus.aac.p.m4a',
    'created_at' => '2026-08-05 11:55:09',
  ),
  78 => 
  array (
    'id' => 2552,
    'spotify_id' => '6nvGrb4m89DNunTWOVHtaI',
    'title' => 'Hanya Untuk-Mu',
    'artist' => 'Ten2Five',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732bbccac60c8305b4236ee503',
    'meaning' => 'Lagu "Hanya Untuk-Mu" karya Ten2Five mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6nvGrb4m89DNunTWOVHtaI',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:09',
  ),
  79 => 
  array (
    'id' => 2553,
    'spotify_id' => '5VDkTaz7DFBvnPmjPuZtZh',
    'title' => 'Simpan Saja',
    'artist' => 'Superglad',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27318141969ca7e34e1ffb28550',
    'meaning' => 'Keputusan untuk memendam perasaan cinta secara rahasia demi menjaga hubungan dan menghindari kekecewaan.',
    'spotify_url' => 'https://open.spotify.com/track/5VDkTaz7DFBvnPmjPuZtZh',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:55:09',
  ),
);
$allLocalSongs = [];
$allMessages = [];
require __DIR__ . '/migration_common.php';
?>
