<?php
$batchNum = 4;
$isLastBatch = false;
$batchSongs = array (
  0 => 
  array (
    'id' => 1319,
    'spotify_id' => '5bIgzvxvlefRUCQK9JPocF',
    'title' => 'Garden Song',
    'artist' => 'Phoebe Bridgers',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a91b75c9ef65ed8d760ff600',
    'meaning' => 'Lagu "Garden Song" karya Phoebe Bridgers mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5bIgzvxvlefRUCQK9JPocF',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:19',
  ),
  1 => 
  array (
    'id' => 1324,
    'spotify_id' => '1WH5m26xZ1wZmTxsVNL8CW',
    'title' => 'Jarang Pulang',
    'artist' => 'Xpinn RMX',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27376918d9621634a8f3c7b96f4',
    'meaning' => 'Lagu "Jarang Pulang" karya Xpinn RMX mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1WH5m26xZ1wZmTxsVNL8CW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:19',
  ),
  2 => 
  array (
    'id' => 1325,
    'spotify_id' => '1oyDjOXDRYbtFxSeKidtTm',
    'title' => 'Jarak',
    'artist' => 'Gie',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f89b8133523921df02471ec1',
    'meaning' => 'Lagu "Jarak" karya Gie mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1oyDjOXDRYbtFxSeKidtTm',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:19',
  ),
  3 => 
  array (
    'id' => 1327,
    'spotify_id' => '0ZyMo6cuekhx6RVqjBfPKs',
    'title' => 'Jaranan Bas Mantap Damar Opo Lilin',
    'artist' => 'Yosep setiawan, Seni jaranan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739750e3889e2d48dae63a62da',
    'meaning' => 'Lagu "Jaranan Bas Mantap Damar Opo Lilin" karya Yosep setiawan, Seni jaranan mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0ZyMo6cuekhx6RVqjBfPKs',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:19',
  ),
  4 => 
  array (
    'id' => 1329,
    'spotify_id' => '2LsbizbOeNa4x6qsi2jAMb',
    'title' => 'La flaca',
    'artist' => 'Jarabe De Palo',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27348de952267002dbeffe048ad',
    'meaning' => 'Lagu "La flaca" karya Jarabe De Palo mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2LsbizbOeNa4x6qsi2jAMb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:19',
  ),
  5 => 
  array (
    'id' => 1359,
    'spotify_id' => '1TMvBhqekWmWJSxpmUMgFz',
    'title' => 'Tenang',
    'artist' => 'Judika, Andi Rianto',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27326160f394d075ef36b4c443b',
    'meaning' => 'Lagu "Tenang" karya Judika, Andi Rianto mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1TMvBhqekWmWJSxpmUMgFz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:25',
  ),
  6 => 
  array (
    'id' => 1363,
    'spotify_id' => '7BVtNEGHh8O2kLyciokFyl',
    'title' => 'Teganya Kau',
    'artist' => 'Lyodra',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ab5d3c815265b9b11b51ed86',
    'meaning' => 'Lagu "Teganya Kau" karya Lyodra mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7BVtNEGHh8O2kLyciokFyl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  7 => 
  array (
    'id' => 1365,
    'spotify_id' => '0qbRvZ1alpPGmV52wKb2gJ',
    'title' => 'Foto kita blur',
    'artist' => 'Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733489e60f1b695d3e2b814682',
    'meaning' => 'Lagu "Foto kita blur" karya Sal Priadi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0qbRvZ1alpPGmV52wKb2gJ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  8 => 
  array (
    'id' => 1371,
    'spotify_id' => '3aM3bFzA2dCtej0U3h4WKH',
    'title' => 'Terbelah Jadi Dua',
    'artist' => 'Gloria Jessica, Ade Govinda',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739e1a03b05439a32c53cc04a1',
    'meaning' => 'Lagu "Terbelah Jadi Dua" karya Gloria Jessica, Ade Govinda mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3aM3bFzA2dCtej0U3h4WKH',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  9 => 
  array (
    'id' => 1374,
    'spotify_id' => '6ksyG6PARbZD5j4WTMJ08G',
    'title' => '1000X',
    'artist' => 'Ghea Indrawari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27353ab629cb64f2dad691e1301',
    'meaning' => 'Lagu "1000X" karya Ghea Indrawari mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6ksyG6PARbZD5j4WTMJ08G',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  10 => 
  array (
    'id' => 1376,
    'spotify_id' => '3fqwjXwUGN6vbzIwvyFMhx',
    'title' => 'Tennessee Whiskey',
    'artist' => 'Chris Stapleton',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273540fc1d083eac5bcff8dad21',
    'meaning' => 'Lagu "Tennessee Whiskey" karya Chris Stapleton mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3fqwjXwUGN6vbzIwvyFMhx',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  11 => 
  array (
    'id' => 1379,
    'spotify_id' => '0k2GOhqsrxDTAbFFSdNJjT',
    'title' => 'Temperature',
    'artist' => 'Sean Paul',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27303e939084d57aba19eb19afb',
    'meaning' => 'Lagu "Temperature" karya Sean Paul mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0k2GOhqsrxDTAbFFSdNJjT',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  12 => 
  array (
    'id' => 1383,
    'spotify_id' => '20RR8TQr1SsZ2XYoCVoI0E',
    'title' => 'เทหมดหน้าตัก (All In)',
    'artist' => 'Phuwin',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a0837096f00e8797d2f64e2e',
    'meaning' => 'Lagu "เทหมดหน้าตัก (All In)" karya Phuwin mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/20RR8TQr1SsZ2XYoCVoI0E',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  13 => 
  array (
    'id' => 1384,
    'spotify_id' => '25FTMokYEbEWHEdss5JLZS',
    'title' => 'Teenage Dirtbag',
    'artist' => 'Wheatus',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730a3740efa638f10f14fabc46',
    'meaning' => 'Lagu "Teenage Dirtbag" karya Wheatus mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/25FTMokYEbEWHEdss5JLZS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  14 => 
  array (
    'id' => 1387,
    'spotify_id' => '27iUCXDMHJOHd4jkwFtSgi',
    'title' => 'เท่ไป',
    'artist' => 'PUNYARB',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273deb83207f62b829b6ec08093',
    'meaning' => 'Lagu "เท่ไป" karya PUNYARB mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/27iUCXDMHJOHd4jkwFtSgi',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  15 => 
  array (
    'id' => 1392,
    'spotify_id' => '3pTsE064ZTJ1n8bP3VAm2c',
    'title' => 'תהום',
    'artist' => 'Omer Adam',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273635571e4dbe218b57bf5c1ff',
    'meaning' => 'Lagu "תהום" karya Omer Adam mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3pTsE064ZTJ1n8bP3VAm2c',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  16 => 
  array (
    'id' => 1393,
    'spotify_id' => '05hpTrbQIXJ2DiXrozJtyF',
    'title' => 'Te He Prometido',
    'artist' => 'Jessie Morales El Original De La Sierra',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27300094e7f763dc45089e8c8cb',
    'meaning' => 'Lagu "Te He Prometido" karya Jessie Morales El Original De La Sierra mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/05hpTrbQIXJ2DiXrozJtyF',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  17 => 
  array (
    'id' => 1394,
    'spotify_id' => '7fBv7CLKzipRk6EC6TWHOB',
    'title' => 'The Hills',
    'artist' => 'The Weeknd',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737fcead687e99583072cc217b',
    'meaning' => 'Lagu "The Hills" karya The Weeknd mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7fBv7CLKzipRk6EC6TWHOB',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  18 => 
  array (
    'id' => 1395,
    'spotify_id' => '742x4cdDwex5kcwMhLfNkb',
    'title' => 'Te He Prometido',
    'artist' => 'Junior Gonzalez',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733a3a4b786017a4cb28940fc2',
    'meaning' => 'Lagu "Te He Prometido" karya Junior Gonzalez mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/742x4cdDwex5kcwMhLfNkb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  19 => 
  array (
    'id' => 1396,
    'spotify_id' => '403jkeVg7hU4yGg40LE2WI',
    'title' => 'Track 8',
    'artist' => 'The Jeblogs, Trigga Coca',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b2ac8e98b0fe410e0bd9fd52',
    'meaning' => 'Lagu "Track 8" karya The Jeblogs, Trigga Coca mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/403jkeVg7hU4yGg40LE2WI',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  20 => 
  array (
    'id' => 1397,
    'spotify_id' => '7122g4Jp2ZrSYfkxbI04Lu',
    'title' => 'Hasta Mañana',
    'artist' => 'Grupo Limite',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27382bf7b11a9019a880752c824',
    'meaning' => 'Lagu "Hasta Mañana" karya Grupo Limite mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7122g4Jp2ZrSYfkxbI04Lu',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  21 => 
  array (
    'id' => 1398,
    'spotify_id' => '2Rz2F6KoLH6TtbX4TZ2qcP',
    'title' => 'Tu Thodi Der Aur Thehar Ja - From "Half Girlfriend"',
    'artist' => 'Shreya Ghoshal, Farhan Saeed, Kumaar',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273fdfdfb32ce2dae56c62c8ac7',
    'meaning' => 'Lagu "Tu Thodi Der Aur Thehar Ja - From "Half Girlfriend"" karya Shreya Ghoshal, Farhan Saeed, Kumaar mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2Rz2F6KoLH6TtbX4TZ2qcP',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:27',
  ),
  22 => 
  array (
    'id' => 1406,
    'spotify_id' => '2HSEx8vqPIu6aMZB60OVTm',
    'title' => 'Sambutlah',
    'artist' => 'The Jeblogs',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b2ac8e98b0fe410e0bd9fd52',
    'meaning' => 'Lagu "Sambutlah" karya The Jeblogs mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2HSEx8vqPIu6aMZB60OVTm',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:28',
  ),
  23 => 
  array (
    'id' => 1407,
    'spotify_id' => '6RmbvJNdfY2IibThAQB9Ur',
    'title' => 'Teh Hijau - Acoustic Version',
    'artist' => 'Tulos',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273afb6c3063a2a8c41c18da754',
    'meaning' => 'Kehangatan sederhana dan ketenangan jiwa yang dihadirkan oleh sosok yang dicintai di tengah riuhnya dunia.',
    'spotify_url' => 'https://open.spotify.com/track/6RmbvJNdfY2IibThAQB9Ur',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:28',
  ),
  24 => 
  array (
    'id' => 1408,
    'spotify_id' => '4UFttgw0BIzx5lFUECcjcA',
    'title' => 'Teh Hijau di Ujung Senja',
    'artist' => 'Bilungka Sulada',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273729a04de8baf6489707b0eae',
    'meaning' => 'Kehangatan sederhana dan ketenangan jiwa yang dihadirkan oleh sosok yang dicintai di tengah riuhnya dunia.',
    'spotify_url' => 'https://open.spotify.com/track/4UFttgw0BIzx5lFUECcjcA',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:28',
  ),
  25 => 
  array (
    'id' => 1409,
    'spotify_id' => '4zifNBHGmv8Yxw340Ifqhz',
    'title' => 'Las Hijas de Don Simón - En Vivo',
    'artist' => 'Secretto',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273512d300e1454715f5e53c8ed',
    'meaning' => 'Lagu "Las Hijas de Don Simón - En Vivo" karya Secretto mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4zifNBHGmv8Yxw340Ifqhz',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:28',
  ),
  26 => 
  array (
    'id' => 1425,
    'spotify_id' => '41jLKrK1nJisuz8JJ2t09Y',
    'title' => 'Sekian, Terima Kasih',
    'artist' => 'Lealona, The Jeblogs',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732de4f60e0218fb110e5d128a',
    'meaning' => 'Lagu "Sekian, Terima Kasih" karya Lealona, The Jeblogs mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/41jLKrK1nJisuz8JJ2t09Y',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:28',
  ),
  27 => 
  array (
    'id' => 1427,
    'spotify_id' => '5HVdMJpq4YC8CqUOI624AP',
    'title' => 'Bersandarlah',
    'artist' => 'The Jeblogs',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b2ac8e98b0fe410e0bd9fd52',
    'meaning' => 'Lagu "Bersandarlah" karya The Jeblogs mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5HVdMJpq4YC8CqUOI624AP',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:28',
  ),
  28 => 
  array (
    'id' => 1435,
    'spotify_id' => '2w21RfWJaElSWUAhhsQAsW',
    'title' => 'Langit Tak Seharusnya Biru',
    'artist' => 'The Jansen',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f7bc95eb2c3b7f2794ff1363',
    'meaning' => 'Lagu "Langit Tak Seharusnya Biru" karya The Jansen mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2w21RfWJaElSWUAhhsQAsW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:29',
  ),
  29 => 
  array (
    'id' => 1436,
    'spotify_id' => '64L8X2Sl7837JKJZREVIa9',
    'title' => 'Teh Hijau',
    'artist' => 'Rusli Ridwan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273bdfe871ae3e3137c37db3d14',
    'meaning' => 'Kehangatan sederhana dan ketenangan jiwa yang dihadirkan oleh sosok yang dicintai di tengah riuhnya dunia.',
    'spotify_url' => 'https://open.spotify.com/track/64L8X2Sl7837JKJZREVIa9',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:09:29',
  ),
  30 => 
  array (
    'id' => 1460,
    'spotify_id' => '5eBk8ZXcd0pb0AO4a5PpOg',
    'title' => 'Gala bunga matahari',
    'artist' => 'Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273686acaaa87bfc6ebb42b3bd2',
    'meaning' => 'Lagu "Gala bunga matahari" karya Sal Priadi menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/5eBk8ZXcd0pb0AO4a5PpOg',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  31 => 
  array (
    'id' => 1461,
    'spotify_id' => '7EPJbZ3UygY2fqhOdqOSaT',
    'title' => 'Gemilang',
    'artist' => 'Perunggu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27387221ad6b867ad30afdf048c',
    'meaning' => 'Lagu "Gemilang" karya Perunggu mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7EPJbZ3UygY2fqhOdqOSaT',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  32 => 
  array (
    'id' => 1462,
    'spotify_id' => '1hlHeIZ36Idpr57xPI8OCD',
    'title' => 'Garam & Madu (Sakit Dadaku)',
    'artist' => 'Tenxi, Jemsii, Naykilla',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273cb0c0208f8bf8c753f6c3d30',
    'meaning' => 'Lagu "Garam & Madu (Sakit Dadaku)" karya Tenxi, Jemsii, Naykilla mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1hlHeIZ36Idpr57xPI8OCD',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  33 => 
  array (
    'id' => 1463,
    'spotify_id' => '1xOqGUkyxGQRdCvGpvWKmL',
    'title' => 'Gabriela',
    'artist' => 'KATSEYE',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f8d4d00ffe09373efb13ce29',
    'meaning' => 'Lagu "Gabriela" karya KATSEYE mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1xOqGUkyxGQRdCvGpvWKmL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  34 => 
  array (
    'id' => 1464,
    'spotify_id' => '1qznWsTv045kybfvqR2yhh',
    'title' => 'Gadis Manis Kalimantan',
    'artist' => 'Maman Fvndy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731e0d67bcc8bfa34cd6e52bed',
    'meaning' => 'Lagu "Gadis Manis Kalimantan" karya Maman Fvndy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1qznWsTv045kybfvqR2yhh',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  35 => 
  array (
    'id' => 1465,
    'spotify_id' => '0Oa9mHOnH14GZ4toWwkf4c',
    'title' => 'Good Life (with G-Eazy & Kehlani)',
    'artist' => 'G-Eazy, Kehlani',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273857ce1238c0bf9cbca89bf55',
    'meaning' => 'Lagu "Good Life (with G-Eazy & Kehlani)" karya G-Eazy, Kehlani mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0Oa9mHOnH14GZ4toWwkf4c',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  36 => 
  array (
    'id' => 1466,
    'spotify_id' => '7ujApz6iFP3PmKIDGcaGbe',
    'title' => 'Great Expectation',
    'artist' => 'SIENNA SPIRO',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b09eea420767969b6729962b',
    'meaning' => 'Lagu "Great Expectation" karya SIENNA SPIRO mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7ujApz6iFP3PmKIDGcaGbe',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  37 => 
  array (
    'id' => 1467,
    'spotify_id' => '4czYdbSTG4j5mlsgS6VWn7',
    'title' => 'Gurun Hujan',
    'artist' => 'Juicy Luicy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27364df5bea172a4f0c2a4ae2af',
    'meaning' => 'Lagu "Gurun Hujan" karya Juicy Luicy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4czYdbSTG4j5mlsgS6VWn7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  38 => 
  array (
    'id' => 1468,
    'spotify_id' => '1CPZ5BxNNd0n0nF4Orb9JS',
    'title' => 'Golden',
    'artist' => 'HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734dcb6c5df15cf74596ab25a4',
    'meaning' => 'Lagu "Golden" karya HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1CPZ5BxNNd0n0nF4Orb9JS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  39 => 
  array (
    'id' => 1469,
    'spotify_id' => '4QNpBfC0zvjKqPJcyqBy9W',
    'title' => 'Give Me Everything (feat. Nayer)',
    'artist' => 'Pitbull, AFROJACK, Ne-Yo, Nayer',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731dc7483a9fcfce54822a2f19',
    'meaning' => 'Lagu "Give Me Everything (feat. Nayer)" karya Pitbull, AFROJACK, Ne-Yo, Nayer mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/4QNpBfC0zvjKqPJcyqBy9W',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  40 => 
  array (
    'id' => 1473,
    'spotify_id' => '6XjDF6nds4DE2BBbagZol6',
    'title' => 'Gata Only',
    'artist' => 'FloyyMenor, Cris MJ',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c4583f3ad76630879a75450a',
    'meaning' => 'Lagu "Gata Only" karya FloyyMenor, Cris MJ mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6XjDF6nds4DE2BBbagZol6',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  41 => 
  array (
    'id' => 1475,
    'spotify_id' => '54w4hHMzXh7GgGhBopak1U',
    'title' => 'Gadis Manis Kalimantan',
    'artist' => 'Syahriyadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ae785c1b13ea9385c334ae30',
    'meaning' => 'Lagu "Gadis Manis Kalimantan" karya Syahriyadi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/54w4hHMzXh7GgGhBopak1U',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  42 => 
  array (
    'id' => 1476,
    'spotify_id' => '70oas4dTyNleIN66R3OgvX',
    'title' => 'Gadis Manis Kalimantan',
    'artist' => 'Ajeng Febria, Brodin',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734e6015d10fb8b5f294556aca',
    'meaning' => 'Lagu "Gadis Manis Kalimantan" karya Ajeng Febria, Brodin mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/70oas4dTyNleIN66R3OgvX',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  43 => 
  array (
    'id' => 1477,
    'spotify_id' => '4eNrw5VHXKNsz33E7Xdw17',
    'title' => 'Gaun Merah',
    'artist' => 'Tryana',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732c4cf5c2bc81d53df1320798',
    'meaning' => 'Lagu "Gaun Merah" karya Tryana mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4eNrw5VHXKNsz33E7Xdw17',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  44 => 
  array (
    'id' => 1478,
    'spotify_id' => '5YoITs1m0q8UOQ4AW7N5ga',
    'title' => 'Gasolina',
    'artist' => 'Daddy Yankee',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27311b9999b620ef9bc0e957623',
    'meaning' => 'Lagu "Gasolina" karya Daddy Yankee mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5YoITs1m0q8UOQ4AW7N5ga',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  45 => 
  array (
    'id' => 1479,
    'spotify_id' => '1DIXPcTDzTj8ZMHt3PDt8p',
    'title' => 'Gangsta\'s Paradise',
    'artist' => 'Coolio, L.V.',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737438996f6fe67c59d75d4e43',
    'meaning' => 'Lagu "Gangsta\'s Paradise" karya Coolio, L.V. mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1DIXPcTDzTj8ZMHt3PDt8p',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:08',
  ),
  46 => 
  array (
    'id' => 1481,
    'spotify_id' => '0b7PI4ikygOrxYu8TSQI92',
    'title' => 'Aku Dah Lupa',
    'artist' => 'MikkyZia, F4dli',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738c04feb343f192925928588f',
    'meaning' => 'Lagu "Aku Dah Lupa" karya MikkyZia, F4dli mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0b7PI4ikygOrxYu8TSQI92',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  47 => 
  array (
    'id' => 1482,
    'spotify_id' => '0Z689JhqeJ61tACWQAGMw1',
    'title' => 'Garam Dan Madu',
    'artist' => 'Maman Fvndy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e15b47530a493f469f24422d',
    'meaning' => 'Lagu "Garam Dan Madu" karya Maman Fvndy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0Z689JhqeJ61tACWQAGMw1',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  48 => 
  array (
    'id' => 1483,
    'spotify_id' => '508YSKJn38A46xt90iqqml',
    'title' => 'GARAM CINA FUNKY',
    'artist' => 'RETROHAND RMX99',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733e19b07c12275ffd9f027945',
    'meaning' => 'Lagu "GARAM CINA FUNKY" karya RETROHAND RMX99 menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/508YSKJn38A46xt90iqqml',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  49 => 
  array (
    'id' => 1484,
    'spotify_id' => '6yGOa7O6oftDgANQGH8XWR',
    'title' => 'Garam Cina',
    'artist' => 'Maman Fvndy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27335c46e4a24dc0a3964f70f9c',
    'meaning' => 'Lagu "Garam Cina" karya Maman Fvndy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6yGOa7O6oftDgANQGH8XWR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  50 => 
  array (
    'id' => 1485,
    'spotify_id' => '4AdCUiCTiJcqqZb6s5Rk4L',
    'title' => 'Gara Gara Rasta',
    'artist' => 'Botagearista, Reggae Indonesia',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ceba45c9961202804567479f',
    'meaning' => 'Lagu "Gara Gara Rasta" karya Botagearista, Reggae Indonesia mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4AdCUiCTiJcqqZb6s5Rk4L',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  51 => 
  array (
    'id' => 1486,
    'spotify_id' => '6JNoIVtIVFTKTwEMk5uHGh',
    'title' => 'Garis Terdepan',
    'artist' => 'Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734c40a9cd4933f3e4624b92ab',
    'meaning' => 'Kisah pengagum rahasia yang rela berdiri di barisan paling depan untuk menjaga dan melindungi orang yang dicintainya, meski sadar hatinya milik orang lain.',
    'spotify_url' => 'https://open.spotify.com/track/6JNoIVtIVFTKTwEMk5uHGh',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/74/7e/9c/747e9cc8-022f-4873-038d-7e572044939f/mzaf_12233235374170506389.plus.aac.p.m4a',
    'created_at' => '2026-08-05 11:13:09',
  ),
  52 => 
  array (
    'id' => 1487,
    'spotify_id' => '4rf1NRUuO9jRXdRSvsYpHC',
    'title' => 'Garee2a Awy - A COLORS SHOW',
    'artist' => 'TUL8TE, COLORS',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27373aa5127d0871a45c130ea55',
    'meaning' => 'Lagu "Garee2a Awy - A COLORS SHOW" karya TUL8TE, COLORS mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4rf1NRUuO9jRXdRSvsYpHC',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  53 => 
  array (
    'id' => 1488,
    'spotify_id' => '19woxaSpjOefa2JnAOoqW5',
    'title' => 'Garden (Say It Like Dat)',
    'artist' => 'SZA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27306d56b057cce5797538a16d5',
    'meaning' => 'Lagu "Garden (Say It Like Dat)" karya SZA mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/19woxaSpjOefa2JnAOoqW5',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  54 => 
  array (
    'id' => 1489,
    'spotify_id' => '4y1LsJpmMti1PfRQV9AWWe',
    'title' => 'Girls Just Want to Have Fun',
    'artist' => 'Cyndi Lauper',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ce023ce7dfdd5199bcdfd5a1',
    'meaning' => 'Lagu "Girls Just Want to Have Fun" karya Cyndi Lauper menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  55 => 
  array (
    'id' => 1490,
    'spotify_id' => '4XjtlZNz9eOA55q3Em4P3B',
    'title' => 'Bulan Bintang, Garis Menyilang',
    'artist' => 'Wijaya 80, Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27300683cf374375329c4df41d6',
    'meaning' => 'Lagu "Bulan Bintang, Garis Menyilang" karya Wijaya 80, Sal Priadi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4XjtlZNz9eOA55q3Em4P3B',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  56 => 
  array (
    'id' => 1492,
    'spotify_id' => '4Nb4cWW0kCuzMxLq3xwxgU',
    'title' => 'Garis Pantai',
    'artist' => 'Mister Nobody, GunZ',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27306fd9d4dc10195b52f5e34d5',
    'meaning' => 'Lagu "Garis Pantai" karya Mister Nobody, GunZ mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4Nb4cWW0kCuzMxLq3xwxgU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  57 => 
  array (
    'id' => 1495,
    'spotify_id' => '3rgw2SuhrikNzyd8pKL09s',
    'title' => 'Garis Waktu',
    'artist' => 'Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27309544d32059e7bb7225c5df7',
    'meaning' => 'Lagu "Garis Waktu" karya Fiersa Besari mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3rgw2SuhrikNzyd8pKL09s',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  58 => 
  array (
    'id' => 1496,
    'spotify_id' => '0LkxnYLXDxIkKHlO1IE8rL',
    'title' => 'Nadir',
    'artist' => 'Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734c40a9cd4933f3e4624b92ab',
    'meaning' => 'Lagu "Nadir" karya Fiersa Besari mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0LkxnYLXDxIkKHlO1IE8rL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  59 => 
  array (
    'id' => 1497,
    'spotify_id' => '3IpqeZAZ6VvOxdvZS39prJ',
    'title' => 'Juara Kedua',
    'artist' => 'Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734c40a9cd4933f3e4624b92ab',
    'meaning' => 'Lagu "Juara Kedua" karya Fiersa Besari mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3IpqeZAZ6VvOxdvZS39prJ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  60 => 
  array (
    'id' => 1498,
    'spotify_id' => '5HMmz01XM5IYaGP0KSsDvQ',
    'title' => 'Gary',
    'artist' => 'Stephen Wilson Jr.',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273110e597e9dd2f75f5ced843f',
    'meaning' => 'Lagu "Gary" karya Stephen Wilson Jr. mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5HMmz01XM5IYaGP0KSsDvQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  61 => 
  array (
    'id' => 1499,
    'spotify_id' => '3yHyiUDJdz02FZ6jfUbsmY',
    'title' => 'Satranga (From "ANIMAL")',
    'artist' => 'Arijit Singh, Shreyas Puranik, Siddharth - Garima',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273021d7017f73387b008eab271',
    'meaning' => 'Lagu "Satranga (From "ANIMAL")" karya Arijit Singh, Shreyas Puranik, Siddharth - Garima mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3yHyiUDJdz02FZ6jfUbsmY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  62 => 
  array (
    'id' => 1507,
    'spotify_id' => '5FWUoCEugiAuSIam4wJGyy',
    'title' => 'Garis Takdir',
    'artist' => 'Mamas plogger, Nita Sadah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27310817f7e315f1dd9549e6f6b',
    'meaning' => 'Lagu "Garis Takdir" karya Mamas plogger, Nita Sadah mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/5FWUoCEugiAuSIam4wJGyy',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  63 => 
  array (
    'id' => 1508,
    'spotify_id' => '1trQRrtJZYUjtHaPcvUrI7',
    'title' => 'Gary\'s Song',
    'artist' => 'SpongeBob SquarePants',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273671d70d370a74b4b3cd2873e',
    'meaning' => 'Lagu "Gary\'s Song" karya SpongeBob SquarePants mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1trQRrtJZYUjtHaPcvUrI7',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  64 => 
  array (
    'id' => 1509,
    'spotify_id' => '7MbvanCDWnqsrVMBNhWmN2',
    'title' => 'Garis Tangan',
    'artist' => 'hadi roeslan',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27330af210885e3c6f7d6695b9f',
    'meaning' => 'Lagu "Garis Tangan" karya hadi roeslan mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7MbvanCDWnqsrVMBNhWmN2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:13:09',
  ),
  65 => 
  array (
    'id' => 1549,
    'spotify_id' => '0KKkJNfGyhkQ5aFogxQAPU',
    'title' => 'That\'s What I Like',
    'artist' => 'Bruno Mars',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273232711f7d66a1e19e89e28c5',
    'meaning' => 'Lagu "That\'s What I Like" karya Bruno Mars mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0KKkJNfGyhkQ5aFogxQAPU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:14:04',
  ),
  66 => 
  array (
    'id' => 1609,
    'spotify_id' => '7LZgdL0MxiElfaKZbuuE4l',
    'title' => 'Asleep - 2011 Remaster',
    'artist' => 'The Smiths',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c9b31b01e4d81f8289e49574',
    'meaning' => 'Lagu "Asleep - 2011 Remaster" karya The Smiths mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7LZgdL0MxiElfaKZbuuE4l',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:14:08',
  ),
  67 => 
  array (
    'id' => 1641,
    'spotify_id' => '3AAAGS7iM1ekDywqdYMJG2',
    'title' => 'Akad',
    'artist' => 'Payung Teduh',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27353037b98177c143a06466ec5',
    'meaning' => 'Lagu "Akad" karya Payung Teduh mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3AAAGS7iM1ekDywqdYMJG2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  68 => 
  array (
    'id' => 1644,
    'spotify_id' => '6G7dG0nZN4I9LRGVzKNVQQ',
    'title' => 'Aku Milikmu',
    'artist' => 'Judika',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f624ea733947a2e6ba8359d3',
    'meaning' => 'Lagu "Aku Milikmu" karya Judika mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/6G7dG0nZN4I9LRGVzKNVQQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  69 => 
  array (
    'id' => 1645,
    'spotify_id' => '2tO8xKwSF82hUZp0sOMLM6',
    'title' => 'Aku Tenang',
    'artist' => 'Fourtwnty',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734fe255e0ba819e903f5fc4e5',
    'meaning' => 'Lagu "Aku Tenang" karya Fourtwnty mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2tO8xKwSF82hUZp0sOMLM6',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  70 => 
  array (
    'id' => 1646,
    'spotify_id' => '43uYsN3TYStVRgxhXqsUsv',
    'title' => 'Aku Kamu',
    'artist' => 'AKSA - DIKSA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739f922900a66d922b6d0e8dbd',
    'meaning' => 'Lagu "Aku Kamu" karya AKSA - DIKSA mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/43uYsN3TYStVRgxhXqsUsv',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  71 => 
  array (
    'id' => 1647,
    'spotify_id' => '7Ldcvhcl4Xj4eOTSWpZus5',
    'title' => 'ACAI',
    'artist' => 'CORTIS',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737a702a4c3a18c1439fdc29ff',
    'meaning' => 'Lagu "ACAI" karya CORTIS mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7Ldcvhcl4Xj4eOTSWpZus5',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  72 => 
  array (
    'id' => 1648,
    'spotify_id' => '312z6PZ8wwREck8613PkJk',
    'title' => 'A Couple Minutes',
    'artist' => 'Olivia Dean',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739a336bfb6d40bbd90a507417',
    'meaning' => 'Lagu "A Couple Minutes" karya Olivia Dean mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/312z6PZ8wwREck8613PkJk',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  73 => 
  array (
    'id' => 1649,
    'spotify_id' => '0KoiMHhqKLoL4xM54rcWYY',
    'title' => 'Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)',
    'artist' => 'DJ Snake, Selena Gomez, Ozuna, Cardi B',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273caf82abb2338880577e472be',
    'meaning' => 'Lagu "Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)" karya DJ Snake, Selena Gomez, Ozuna, Cardi B mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0KoiMHhqKLoL4xM54rcWYY',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  74 => 
  array (
    'id' => 1650,
    'spotify_id' => '0BYoWATcndOBcsCfKdTKRx',
    'title' => 'Akhir Tak Bahagia',
    'artist' => 'Misellia',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731d8c87142038d9c62d74c19f',
    'meaning' => 'Kisah perpisahan yang pahit dan penuh penyesalan ketika sebuah hubungan yang telah diperjuangkan dengan keras harus berakhir dengan kesedihan dan luka.',
    'spotify_url' => 'https://open.spotify.com/track/0BYoWATcndOBcsCfKdTKRx',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/b1/d3/e8/b1d3e8e1-9c3a-3ebf-fe0f-a1bfaff24c5d/mzaf_16906683641981009721.plus.aac.p.m4a',
    'created_at' => '2026-08-05 11:18:00',
  ),
  75 => 
  array (
    'id' => 1651,
    'spotify_id' => '0rO8B4DXATR04ifU4LXGtP',
    'title' => 'Akhirnya Ku Menemukanmu',
    'artist' => 'NaFF',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733fdee3a1eae6c6ecffdeadc3',
    'meaning' => 'Lagu "Akhirnya Ku Menemukanmu" karya NaFF mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/0rO8B4DXATR04ifU4LXGtP',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  76 => 
  array (
    'id' => 1652,
    'spotify_id' => '6Qe5wOREjTPivo6M5kW5h3',
    'title' => 'Akhir Cerita Cinta',
    'artist' => 'Glenn Fredly',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732732e6037be5ba207d19f24c',
    'meaning' => 'Lagu "Akhir Cerita Cinta" karya Glenn Fredly mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/6Qe5wOREjTPivo6M5kW5h3',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  77 => 
  array (
    'id' => 1653,
    'spotify_id' => '1tqPw8Hf88h24Bpt2SzuYE',
    'title' => 'Di Akhir Perang',
    'artist' => 'Nadin Amizah',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27394847679fe7b10e27d9803f5',
    'meaning' => 'Lagu "Di Akhir Perang" karya Nadin Amizah mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/1tqPw8Hf88h24Bpt2SzuYE',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  78 => 
  array (
    'id' => 1654,
    'spotify_id' => '2bPVVwbH6eQA9ISLE2tIe0',
    'title' => 'Akhire Lungo',
    'artist' => 'RNK',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738f3019521bc93e4fc8e0a5f0',
    'meaning' => 'Lagu "Akhire Lungo" karya RNK mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/2bPVVwbH6eQA9ISLE2tIe0',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
  79 => 
  array (
    'id' => 1655,
    'spotify_id' => '304FEq5eVvrxur9KdHhC5I',
    'title' => 'Akhir Tak Bahagia',
    'artist' => 'Misellia',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273fa7b32cf632244ae003d6330',
    'meaning' => 'Kisah perpisahan yang pahit dan penuh penyesalan ketika sebuah hubungan yang telah diperjuangkan dengan keras harus berakhir dengan kesedihan dan luka.',
    'spotify_url' => 'https://open.spotify.com/track/304FEq5eVvrxur9KdHhC5I',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:18:00',
  ),
);
$allLocalSongs = [];
$allMessages = [];
require __DIR__ . '/migration_common.php';
?>
