<?php
$batchNum = 6;
$isLastBatch = false;
$batchSongs = array (
  0 => 
  array (
    'id' => 2014,
    'spotify_id' => '6fl4Gu0lJm5hc8FM5JzCZD',
    'title' => 'ICONIC BY MISTAKE',
    'artist' => 'LE SSERAFIM, ILLIT, KATSEYE',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27355886e2f0784a2b7b62b7fe7',
    'meaning' => 'Lagu "ICONIC BY MISTAKE" karya LE SSERAFIM, ILLIT, KATSEYE mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6fl4Gu0lJm5hc8FM5JzCZD',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:04',
  ),
  1 => 
  array (
    'id' => 2015,
    'spotify_id' => '33KU9huHP1Lv1UWWVkuTYd',
    'title' => 'Impostor Syndrome',
    'artist' => 'Sidney Gish',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f7832bb86831bdec9848acda',
    'meaning' => 'Lagu "Impostor Syndrome" karya Sidney Gish mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/33KU9huHP1Lv1UWWVkuTYd',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:04',
  ),
  2 => 
  array (
    'id' => 2016,
    'spotify_id' => '6Qyc6fS4DsZjB2mRW9DsQs',
    'title' => 'Iris',
    'artist' => 'The Goo Goo Dolls',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273eda9478c39a21e1cdc6609ca',
    'meaning' => 'Lagu "Iris" karya The Goo Goo Dolls mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:04',
  ),
  3 => 
  array (
    'id' => 2017,
    'spotify_id' => '0eAuGrXyGFYwur9ARUe7LJ',
    'title' => 'Earrings',
    'artist' => 'Malcolm Todd',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732c1f34ecc1929fb59908aad1',
    'meaning' => 'Lagu "Earrings" karya Malcolm Todd mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0eAuGrXyGFYwur9ARUe7LJ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:04',
  ),
  4 => 
  array (
    'id' => 2018,
    'spotify_id' => '6VaXKBNmGPX8WPNhMX3OEV',
    'title' => 'I Lay My Love on You',
    'artist' => 'Westlife',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c19d35c176acbe8bbbc2b4f7',
    'meaning' => 'Kerinduan membara yang tak tertahankan untuk kembali ke pelukan orang yang paling dicintai di tanah kelahiran.',
    'spotify_url' => 'https://open.spotify.com/track/6VaXKBNmGPX8WPNhMX3OEV',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:04',
  ),
  5 => 
  array (
    'id' => 2040,
    'spotify_id' => '7mqG8I1JG0iQAejC53qpbU',
    'title' => 'TABOLA BALE',
    'artist' => 'Silet Open Up, Jacson Seran, Juan Reza, Diva Aurel',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f6f7d0c06b8b2bd22ba3eae4',
    'meaning' => 'Lagu "TABOLA BALE" karya Silet Open Up, Jacson Seran, Juan Reza, Diva Aurel mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7mqG8I1JG0iQAejC53qpbU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  6 => 
  array (
    'id' => 2041,
    'spotify_id' => '4XHijJfABTtUCW3Bp6KFvr',
    'title' => 'Tarot',
    'artist' => '.Feast',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c800b90e2092a5328f699117',
    'meaning' => 'Lagu "Tarot" karya .Feast mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4XHijJfABTtUCW3Bp6KFvr',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  7 => 
  array (
    'id' => 2042,
    'spotify_id' => '1XYFuCKBnWOBapFnOhuD1N',
    'title' => 'Tak Sanggup Lagi',
    'artist' => 'Rossa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ccf9933772e83da6a0eeb439',
    'meaning' => 'Lagu "Tak Sanggup Lagi" karya Rossa mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1XYFuCKBnWOBapFnOhuD1N',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  8 => 
  array (
    'id' => 2043,
    'spotify_id' => '1YYhDizHx7PnDhAhko6cDS',
    'title' => 'Take Me Home, Country Roads - Original Version',
    'artist' => 'John Denver',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273795c9ba853f5a9f7a88b4e31',
    'meaning' => 'Lagu "Take Me Home, Country Roads - Original Version" karya John Denver membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/1YYhDizHx7PnDhAhko6cDS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  9 => 
  array (
    'id' => 2044,
    'spotify_id' => '6LRO4Nf1DdNRChmnTFi4ic',
    'title' => 'Tak Kan Hilang',
    'artist' => 'Budi Doremi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f7e5af48832abc7234153e0f',
    'meaning' => 'Lagu "Tak Kan Hilang" karya Budi Doremi mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/6LRO4Nf1DdNRChmnTFi4ic',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  10 => 
  array (
    'id' => 2045,
    'spotify_id' => '4ePs7pCU6Jc82Vp8xwVo6g',
    'title' => 'Tapi Tahukah Kamu?',
    'artist' => 'Dygta, Kamasean',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735ef08777bbb239a1ceefeba4',
    'meaning' => 'Lagu "Tapi Tahukah Kamu?" karya Dygta, Kamasean mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4ePs7pCU6Jc82Vp8xwVo6g',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  11 => 
  array (
    'id' => 2046,
    'spotify_id' => '0T4t1PywlNmJGcveGH5spB',
    'title' => 'Takkan Terganti',
    'artist' => 'Marcell',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735f95864c2e8b42d4253b90db',
    'meaning' => 'Lagu "Takkan Terganti" karya Marcell mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0T4t1PywlNmJGcveGH5spB',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  12 => 
  array (
    'id' => 2047,
    'spotify_id' => '6aJn7Cst74cj4lNIiPRgav',
    'title' => 'Touch',
    'artist' => 'KATSEYE',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737e76c17cfbc723800452a24f',
    'meaning' => 'Lagu "Touch" karya KATSEYE mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6aJn7Cst74cj4lNIiPRgav',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  13 => 
  array (
    'id' => 2048,
    'spotify_id' => '0kl6Ozan3fuUdCl6TlB15v',
    'title' => 'Talk To You (ft. 54 Ultra)',
    'artist' => 'ANOTR, 54 Ultra',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b42ed7f52290f1583760a7e2',
    'meaning' => 'Lagu "Talk To You (ft. 54 Ultra)" karya ANOTR, 54 Ultra mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0kl6Ozan3fuUdCl6TlB15v',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  14 => 
  array (
    'id' => 2049,
    'spotify_id' => '2WfaOiMkCvy7F5fcp2zZ8L',
    'title' => 'Take on Me',
    'artist' => 'a-ha',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e8dd4db47e7177c63b0b7d53',
    'meaning' => 'Lagu "Take on Me" karya a-ha mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  15 => 
  array (
    'id' => 2053,
    'spotify_id' => '3CeCwYWvdfXbZLXFhBrbnf',
    'title' => 'Love Story (Taylor’s Version)',
    'artist' => 'Taylor Swift',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273877ea8fa223c26f19aaef92d',
    'meaning' => 'Lagu "Love Story (Taylor’s Version)" karya Taylor Swift mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/3CeCwYWvdfXbZLXFhBrbnf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  16 => 
  array (
    'id' => 2056,
    'spotify_id' => '2ZVHcGGXwarQ0ZfBnY8HLQ',
    'title' => 'Taifun',
    'artist' => 'Barasuara',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b3c6599412a3177bc251b8a1',
    'meaning' => 'Lagu "Taifun" karya Barasuara menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/2ZVHcGGXwarQ0ZfBnY8HLQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  17 => 
  array (
    'id' => 2057,
    'spotify_id' => '0FIDCNYYjNvPVimz5icugS',
    'title' => 'Timeless (feat Playboi Carti)',
    'artist' => 'The Weeknd, Playboi Carti',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273de79f330bc297af3fae736da',
    'meaning' => 'Lagu "Timeless (feat Playboi Carti)" karya The Weeknd, Playboi Carti mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0FIDCNYYjNvPVimz5icugS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  18 => 
  array (
    'id' => 2058,
    'spotify_id' => '7o9uu2GDtVDr9nsR7ZRN73',
    'title' => 'Time After Time',
    'artist' => 'Cyndi Lauper',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ce023ce7dfdd5199bcdfd5a1',
    'meaning' => 'Lagu "Time After Time" karya Cyndi Lauper mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7o9uu2GDtVDr9nsR7ZRN73',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  19 => 
  array (
    'id' => 2059,
    'spotify_id' => '4iG2gAwKXsOcijVaVXzRPW',
    'title' => 'Time to Pretend',
    'artist' => 'MGMT',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273abdf7749aeb5229dbf305f03',
    'meaning' => 'Lagu "Time to Pretend" karya MGMT mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4iG2gAwKXsOcijVaVXzRPW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:07',
  ),
  20 => 
  array (
    'id' => 2066,
    'spotify_id' => '4pvb0WLRcMtbPGmtejJJ6y',
    'title' => 'exile (feat. Bon Iver)',
    'artist' => 'Taylor Swift, Bon Iver',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27395f754318336a07e85ec59bc',
    'meaning' => 'Lagu "exile (feat. Bon Iver)" karya Taylor Swift, Bon Iver mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4pvb0WLRcMtbPGmtejJJ6y',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:08',
  ),
  21 => 
  array (
    'id' => 2067,
    'spotify_id' => '1jgTiNob5cVyXeJ3WgX5bL',
    'title' => 'Elizabeth Taylor',
    'artist' => 'Taylor Swift',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d7812467811a7da6e6a44902',
    'meaning' => 'Lagu "Elizabeth Taylor" karya Taylor Swift mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1jgTiNob5cVyXeJ3WgX5bL',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:08',
  ),
  22 => 
  array (
    'id' => 2068,
    'spotify_id' => '5xMjhZKSo8yh5r9b5vrYRr',
    'title' => 'Tailor Swif',
    'artist' => 'A$AP Rocky',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b19948b2c6de145ea1c6f1b5',
    'meaning' => 'Lagu "Tailor Swif" karya A$AP Rocky mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5xMjhZKSo8yh5r9b5vrYRr',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:08',
  ),
  23 => 
  array (
    'id' => 2069,
    'spotify_id' => '3jcw3xe2YsP5IlMwaahetO',
    'title' => 'Thailand',
    'artist' => 'Malcolm Todd',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732c1f34ecc1929fb59908aad1',
    'meaning' => 'Lagu "Thailand" karya Malcolm Todd mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3jcw3xe2YsP5IlMwaahetO',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:08',
  ),
  24 => 
  array (
    'id' => 2079,
    'spotify_id' => '7wuJGgpTNzbUyn26IOY6rj',
    'title' => 'Total Eclipse of the Heart',
    'artist' => 'Bonnie Tyler',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738cefe8e2f2cfd63ce073fa96',
    'meaning' => 'Lagu "Total Eclipse of the Heart" karya Bonnie Tyler mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/7wuJGgpTNzbUyn26IOY6rj',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:08',
  ),
  25 => 
  array (
    'id' => 2087,
    'spotify_id' => '1fzAuUVbzlhZ1lJAx9PtY6',
    'title' => 'Daylight',
    'artist' => 'Taylor Swift',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e787cffec20aa2a396a61647',
    'meaning' => 'Lagu "Daylight" karya Taylor Swift membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/1fzAuUVbzlhZ1lJAx9PtY6',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:23:09',
  ),
  26 => 
  array (
    'id' => 2111,
    'spotify_id' => '58DuK2YQrCZHSpPi6aCdyR',
    'title' => 'Sempurna - Acoustic Version',
    'artist' => 'Killercats',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b9048662e26b6b3049b34810',
    'meaning' => 'Lagu "Sempurna - Acoustic Version" karya Killercats mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/58DuK2YQrCZHSpPi6aCdyR',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:21',
  ),
  27 => 
  array (
    'id' => 2112,
    'spotify_id' => '5n1UIhatlpqeBaY3Yhiw0p',
    'title' => 'Karya Terindahmu - Lagu Galau Akustik Terbaru',
    'artist' => 'Seruni Vela',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27331f575be4a65ecf8bfc0d56b',
    'meaning' => 'Lagu "Karya Terindahmu - Lagu Galau Akustik Terbaru" karya Seruni Vela mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5n1UIhatlpqeBaY3Yhiw0p',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:21',
  ),
  28 => 
  array (
    'id' => 2113,
    'spotify_id' => '3f9pldCtjxTMbZzpEXm8jQ',
    'title' => 'Lonely in Bali Skies - Lagu Akustik Terbaru',
    'artist' => 'Seruni Vela',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27331f575be4a65ecf8bfc0d56b',
    'meaning' => 'Lagu "Lonely in Bali Skies - Lagu Akustik Terbaru" karya Seruni Vela mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/3f9pldCtjxTMbZzpEXm8jQ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:21',
  ),
  29 => 
  array (
    'id' => 2114,
    'spotify_id' => '2HoQPMOcn89oR2m0C5tbPv',
    'title' => 'Kecup Aku Sebelum Mati - Lagu Terbaru Slow Pop & Psychedelic Rock',
    'artist' => 'Seruni Vela',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734388aaa252f8c3ff0233345d',
    'meaning' => 'Lagu "Kecup Aku Sebelum Mati - Lagu Terbaru Slow Pop & Psychedelic Rock" karya Seruni Vela mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2HoQPMOcn89oR2m0C5tbPv',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:21',
  ),
  30 => 
  array (
    'id' => 2115,
    'spotify_id' => '36qdfBjy4qB33Z6gJnxk0f',
    'title' => 'Masih Tunggu Kamu',
    'artist' => 'Seruni Vela',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27388779e28570920112cb9934c',
    'meaning' => 'Lagu "Masih Tunggu Kamu" karya Seruni Vela mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/36qdfBjy4qB33Z6gJnxk0f',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:21',
  ),
  31 => 
  array (
    'id' => 2127,
    'spotify_id' => '4y9gE7I7PbA2qgx9W08rrB',
    'title' => 'Dinding Kaca - Slow Lagu Galau Terbaru',
    'artist' => 'Seruni Vela',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27331f575be4a65ecf8bfc0d56b',
    'meaning' => 'Lagu "Dinding Kaca - Slow Lagu Galau Terbaru" karya Seruni Vela mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4y9gE7I7PbA2qgx9W08rrB',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:27',
  ),
  32 => 
  array (
    'id' => 2138,
    'spotify_id' => '0301DpIhbVSPDWceTO8i8I',
    'title' => 'Usik',
    'artist' => 'Feby Putri',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ffd52c142adf359d110eb856',
    'meaning' => 'Lagu "Usik" karya Feby Putri mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0301DpIhbVSPDWceTO8i8I',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  33 => 
  array (
    'id' => 2139,
    'spotify_id' => '009ImBOrIUlWgla8U05RAC',
    'title' => 'Unconditionally',
    'artist' => 'Katy Perry',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731e9a057052d59004caf47e22',
    'meaning' => 'Lagu "Unconditionally" karya Katy Perry mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/009ImBOrIUlWgla8U05RAC',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  34 => 
  array (
    'id' => 2140,
    'spotify_id' => '2tm79rrJ6hJkyqlz6FYI7L',
    'title' => 'Untukku',
    'artist' => 'Chrisye',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738b2625e0fb9735fd16b83b9b',
    'meaning' => 'Lagu "Untukku" karya Chrisye mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2tm79rrJ6hJkyqlz6FYI7L',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  35 => 
  array (
    'id' => 2141,
    'spotify_id' => '0urpBLpcm6DOGzs86rcKd8',
    'title' => 'Untuk Perempuan Yang Sedang Di Pelukan',
    'artist' => 'Payung Teduh',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738ee03809d40edb632fadd3c0',
    'meaning' => 'Lagu "Untuk Perempuan Yang Sedang Di Pelukan" karya Payung Teduh mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/0urpBLpcm6DOGzs86rcKd8',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  36 => 
  array (
    'id' => 2142,
    'spotify_id' => '49FYlytm3dAAraYgpoJZux',
    'title' => 'Umbrella',
    'artist' => 'Rihanna, JAŸ-Z',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f9f27162ab1ed45b8d7a7e98',
    'meaning' => 'Lagu "Umbrella" karya Rihanna, JAŸ-Z mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/49FYlytm3dAAraYgpoJZux',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  37 => 
  array (
    'id' => 2143,
    'spotify_id' => '6Hdc3IQeyCxG5d14uAcwQW',
    'title' => 'u + me = <3',
    'artist' => 'Olivia Rodrigo',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735cf234eeb7a2edf44bf64a46',
    'meaning' => 'Lagu "u + me = <3" karya Olivia Rodrigo mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6Hdc3IQeyCxG5d14uAcwQW',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  38 => 
  array (
    'id' => 2144,
    'spotify_id' => '3B54sVLJ402zGa6Xm4YGNe',
    'title' => 'Unforgettable',
    'artist' => 'French Montana, Swae Lee',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738a31195a371b2233456f6c07',
    'meaning' => 'Lagu "Unforgettable" karya French Montana, Swae Lee mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3B54sVLJ402zGa6Xm4YGNe',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  39 => 
  array (
    'id' => 2145,
    'spotify_id' => '7BDZnj8AJ8vzyrwd01hZV0',
    'title' => 'Jika Itu Yang Terbaik',
    'artist' => 'Ungu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737cfff088f7671523929e60d2',
    'meaning' => 'Lagu "Jika Itu Yang Terbaik" karya Ungu mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7BDZnj8AJ8vzyrwd01hZV0',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  40 => 
  array (
    'id' => 2146,
    'spotify_id' => '7ars3G0mJRy5Br4A7sCYpb',
    'title' => 'Untukmu Selamanya',
    'artist' => 'Ungu',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273be7982704b25a460843a308b',
    'meaning' => 'Lagu "Untukmu Selamanya" karya Ungu mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7ars3G0mJRy5Br4A7sCYpb',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  41 => 
  array (
    'id' => 2147,
    'spotify_id' => '3U5JVgI2x4rDyHGObzJfNf',
    'title' => 'Unwritten',
    'artist' => 'Natasha Bedingfield',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b337e1ca6629a53c66a3b0d4',
    'meaning' => 'Lagu "Unwritten" karya Natasha Bedingfield mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3U5JVgI2x4rDyHGObzJfNf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  42 => 
  array (
    'id' => 2149,
    'spotify_id' => '6Hii26x3qDErVitnGW8QtO',
    'title' => 'Runtuh',
    'artist' => 'Feby Putri, Fiersa Besari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734788f7886c01b9b2ee95cbdd',
    'meaning' => 'Lagu "Runtuh" karya Feby Putri, Fiersa Besari mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6Hii26x3qDErVitnGW8QtO',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  43 => 
  array (
    'id' => 2150,
    'spotify_id' => '5GgRntbjr23OK9MMST02di',
    'title' => 'Usik',
    'artist' => 'Feby Putri',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b43accd449468d819918efea',
    'meaning' => 'Lagu "Usik" karya Feby Putri mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5GgRntbjr23OK9MMST02di',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  44 => 
  array (
    'id' => 2151,
    'spotify_id' => '3nHxZEe1dT7zs73DG6pNll',
    'title' => 'Usai',
    'artist' => 'Tiara Andini',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733ea0e9844c8ce8016a0c5478',
    'meaning' => 'Pernyataan kedewasaan untuk mengakhiri hubungan yang tak lagi sejalan dan merelakan pasangan pergi tanpa rasa benci.',
    'spotify_url' => 'https://open.spotify.com/track/3nHxZEe1dT7zs73DG6pNll',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  45 => 
  array (
    'id' => 2152,
    'spotify_id' => '6i5sIqE4lglanzlXXl8gCj',
    'title' => 'Usai Di Sini',
    'artist' => 'Raisa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f018e2376d8060e0ba1112ab',
    'meaning' => 'Pernyataan kedewasaan untuk mengakhiri hubungan yang tak lagi sejalan dan merelakan pasangan pergi tanpa rasa benci.',
    'spotify_url' => 'https://open.spotify.com/track/6i5sIqE4lglanzlXXl8gCj',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/32/1d/94/321d94c4-fd70-4b98-5b6b-ca2981672b8e/mzaf_7467488100019175573.plus.aac.p.m4a',
    'created_at' => '2026-08-05 11:27:29',
  ),
  46 => 
  array (
    'id' => 2153,
    'spotify_id' => '1hY73ezlX6Lv9egJv2vaTn',
    'title' => 'Ruang Baru',
    'artist' => 'Barsena Bestandhi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2731492171cba5bd7087eb9fa94',
    'meaning' => 'Lagu "Ruang Baru" karya Barsena Bestandhi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1hY73ezlX6Lv9egJv2vaTn',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  47 => 
  array (
    'id' => 2154,
    'spotify_id' => '1HaVR74vV9Re7AukgpzwLT',
    'title' => 'Usir Ketakutan',
    'artist' => 'Fai kencrut',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e35d3256e61f3ee4b807cff5',
    'meaning' => 'Lagu "Usir Ketakutan" karya Fai kencrut mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1HaVR74vV9Re7AukgpzwLT',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  48 => 
  array (
    'id' => 2155,
    'spotify_id' => '4356Typ82hUiFAynbLYbPn',
    'title' => 'DJ Got Us Fallin\' In Love (feat. Pitbull)',
    'artist' => 'USHER, Pitbull',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27386b0c9728ad3ed338eaeea79',
    'meaning' => 'Lagu "DJ Got Us Fallin\' In Love (feat. Pitbull)" karya USHER, Pitbull mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/4356Typ82hUiFAynbLYbPn',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  49 => 
  array (
    'id' => 2156,
    'spotify_id' => '11jVnpAewcZnIdLsq0BKJF',
    'title' => 'Using You',
    'artist' => 'Mars Argo',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273abb30e6f7c89ba2d61a3cbb0',
    'meaning' => 'Lagu "Using You" karya Mars Argo mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/11jVnpAewcZnIdLsq0BKJF',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  50 => 
  array (
    'id' => 2157,
    'spotify_id' => '5VGlqQANWDKJFl0MBG3sg2',
    'title' => 'Use Somebody',
    'artist' => 'Kings of Leon',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732519d01c0cca06f134eeadd8',
    'meaning' => 'Lagu "Use Somebody" karya Kings of Leon mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5VGlqQANWDKJFl0MBG3sg2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:29',
  ),
  51 => 
  array (
    'id' => 2160,
    'spotify_id' => '1b0aDgrG775i4sPQgJGmkU',
    'title' => 'Tak Ingin Usai',
    'artist' => 'Keisya Levronka',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738fa475b368164ab5eebe1a8d',
    'meaning' => 'Lagu "Tak Ingin Usai" karya Keisya Levronka mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/1b0aDgrG775i4sPQgJGmkU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  52 => 
  array (
    'id' => 2161,
    'spotify_id' => '3FwQ3RYYEekzjEeL3jdpUZ',
    'title' => 'Pesan Terakhir',
    'artist' => 'Lyodra',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d00e5994b61f1d93dafe9221',
    'meaning' => 'Lagu "Pesan Terakhir" karya Lyodra mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/3FwQ3RYYEekzjEeL3jdpUZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  53 => 
  array (
    'id' => 2163,
    'spotify_id' => '6iBuCdHWsIJ3qCDs50w2lS',
    'title' => 'Apalah (Arti Menunggu)',
    'artist' => 'Raisa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738bd2fdd47fa594b1362682a9',
    'meaning' => 'Lagu "Apalah (Arti Menunggu)" karya Raisa mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6iBuCdHWsIJ3qCDs50w2lS',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  54 => 
  array (
    'id' => 2164,
    'spotify_id' => '5EbMby7AeD6JjwJ1Axhsvx',
    'title' => 'Usai sudah buang semua',
    'artist' => 'HENDRI SANTANA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27376bb536fe676904af56943b0',
    'meaning' => 'Lagu "Usai sudah buang semua" karya HENDRI SANTANA mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5EbMby7AeD6JjwJ1Axhsvx',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  55 => 
  array (
    'id' => 2165,
    'spotify_id' => '7gB98EWp4p9VKxOToaqrhM',
    'title' => 'Cinta Terakhir',
    'artist' => 'Ari Lasso',
    'cover_url' => 'https://i.scdn.co/image/e850a6af940d44800207bd7cf5d2dbded6ca5c1e',
    'meaning' => 'Lagu "Cinta Terakhir" karya Ari Lasso mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/7gB98EWp4p9VKxOToaqrhM',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  56 => 
  array (
    'id' => 2166,
    'spotify_id' => '0OHr74BS1CEwyZsyY9kml2',
    'title' => 'Tak Ingin Usai',
    'artist' => 'Keisya Levronka',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d640e180e7cb9909fc3d4092',
    'meaning' => 'Lagu "Tak Ingin Usai" karya Keisya Levronka mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/0OHr74BS1CEwyZsyY9kml2',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  57 => 
  array (
    'id' => 2167,
    'spotify_id' => '7r79xIOh04L6ESzJHPawAZ',
    'title' => 'Usai Rasa Itu',
    'artist' => 'Isense',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735679453f91e2a1a893f7e478',
    'meaning' => 'Lagu "Usai Rasa Itu" karya Isense mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/7r79xIOh04L6ESzJHPawAZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  58 => 
  array (
    'id' => 2170,
    'spotify_id' => '1x9jnpPOAMSrr7DuIG5jMl',
    'title' => 'Kita usahakan rumah itu',
    'artist' => 'Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273680f1025f6619c42a3c23864',
    'meaning' => 'Lagu "Kita usahakan rumah itu" karya Sal Priadi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1x9jnpPOAMSrr7DuIG5jMl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  59 => 
  array (
    'id' => 2171,
    'spotify_id' => '3E7dfMvvCLUddWissuqMwr',
    'title' => 'Party In The U.S.A.',
    'artist' => 'Miley Cyrus',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734ea6653890e297d53e93e3e0',
    'meaning' => 'Lagu "Party In The U.S.A." karya Miley Cyrus mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3E7dfMvvCLUddWissuqMwr',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  60 => 
  array (
    'id' => 2174,
    'spotify_id' => '1VmVgeVBNukfpF0OhhpOF4',
    'title' => 'Tak Mungkin Berpaling',
    'artist' => 'Slam',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273052eef066e3b8eda51414b36',
    'meaning' => 'Lagu "Tak Mungkin Berpaling" karya Slam mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1VmVgeVBNukfpF0OhhpOF4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  61 => 
  array (
    'id' => 2175,
    'spotify_id' => '5Egm9N7FnzsThl1CFXB2mm',
    'title' => 'Kita usahakan rumah itu',
    'artist' => 'Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273686acaaa87bfc6ebb42b3bd2',
    'meaning' => 'Lagu "Kita usahakan rumah itu" karya Sal Priadi mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5Egm9N7FnzsThl1CFXB2mm',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  62 => 
  array (
    'id' => 2177,
    'spotify_id' => '5TeM0uxDT663mth1LMOqPg',
    'title' => 'USAD',
    'artist' => 'PABLO',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a8d1c551bfc5bc6bbd69ab35',
    'meaning' => 'Lagu "USAD" karya PABLO mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5TeM0uxDT663mth1LMOqPg',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:27:31',
  ),
  63 => 
  array (
    'id' => 2212,
    'spotify_id' => '5xs9OMUxjOu8bKRd7bnHcl',
    'title' => 'Memori Sekuntum Rindu',
    'artist' => 'Spoon',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733cd96a3db0e265a5884618f9',
    'meaning' => 'Lagu "Memori Sekuntum Rindu" karya Spoon membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/5xs9OMUxjOu8bKRd7bnHcl',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  64 => 
  array (
    'id' => 2213,
    'spotify_id' => '26aNjbOgTVrFZEx7was69A',
    'title' => 'Mencintaimu',
    'artist' => 'Sal Priadi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273489cd3228dbaa5552e5ed8c9',
    'meaning' => 'Lagu "Mencintaimu" karya Sal Priadi mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/26aNjbOgTVrFZEx7was69A',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  65 => 
  array (
    'id' => 2214,
    'spotify_id' => '12MSmLSGPWulxOPvYBy5Ss',
    'title' => 'memories',
    'artist' => 'Maki Otsuki',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f4be8b67276dc58e94a03335',
    'meaning' => 'Lagu "memories" karya Maki Otsuki mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/12MSmLSGPWulxOPvYBy5Ss',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  66 => 
  array (
    'id' => 2215,
    'spotify_id' => '3VegC0PZiHjGxb80DER8XU',
    'title' => 'Merry Go Round',
    'artist' => 'BTS',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273dfa17fad7f190c901603270e',
    'meaning' => 'Lagu "Merry Go Round" karya BTS mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3VegC0PZiHjGxb80DER8XU',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  67 => 
  array (
    'id' => 2216,
    'spotify_id' => '6ifUES3keWjwXgae8pXI3o',
    'title' => 'Me Rehúso',
    'artist' => 'Danny Ocean',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d8243a13e6f41310a5fa7b96',
    'meaning' => 'Lagu "Me Rehúso" karya Danny Ocean mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6ifUES3keWjwXgae8pXI3o',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  68 => 
  array (
    'id' => 2218,
    'spotify_id' => '3c0V0U2cKhOXUVWL86jQ7z',
    'title' => 'Meleleh Bahagia',
    'artist' => 'Mila DA7, Valen DA7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c404599636b2706aa37afc72',
    'meaning' => 'Lagu "Meleleh Bahagia" karya Mila DA7, Valen DA7 menyebarkan energi positif, keceriaan, dan rasa bahagia yang hadir saat seseorang mewarnai hari-hari dengan kehangatan.',
    'spotify_url' => 'https://open.spotify.com/track/3c0V0U2cKhOXUVWL86jQ7z',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  69 => 
  array (
    'id' => 2219,
    'spotify_id' => '60ENzjgcc6MpFD883FjqPS',
    'title' => 'Melepasmu',
    'artist' => 'Drive',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273bd215e9a6f391addd78f63a1',
    'meaning' => 'Keberanian dan keikhlasan hati untuk merelakan sosok kekasih pergi ketika menyadari jiwanya tak lagi ada untuk kita.',
    'spotify_url' => 'https://open.spotify.com/track/60ENzjgcc6MpFD883FjqPS',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/a0/a5/30/a0a530ed-13df-171c-47bc-2aabd2e36124/mzaf_16168724506627647304.plus.aac.p.m4a',
    'created_at' => '2026-08-05 11:30:53',
  ),
  70 => 
  array (
    'id' => 2220,
    'spotify_id' => '7s8c4Ap7Gdzdvb3gGuVGhy',
    'title' => 'Melangitkanmu',
    'artist' => 'Ghea Indrawari',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27336b6a823583611445c30bca1',
    'meaning' => 'Lagu "Melangitkanmu" karya Ghea Indrawari mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7s8c4Ap7Gdzdvb3gGuVGhy',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  71 => 
  array (
    'id' => 2221,
    'spotify_id' => '7Hun5YHQ5TEe9j97cU5XPg',
    'title' => 'Melompat Lebih Tinggi',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27398b7cd420705531db32b3aeb',
    'meaning' => 'Lagu "Melompat Lebih Tinggi" karya Sheila On 7 mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7Hun5YHQ5TEe9j97cU5XPg',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  72 => 
  array (
    'id' => 2222,
    'spotify_id' => '6lnqe1urLVOV4tn0YgmnIw',
    'title' => 'Melting',
    'artist' => 'Kali Uchis',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27388d3a2c03886b0c034c7eb8f',
    'meaning' => 'Lagu "Melting" karya Kali Uchis mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6lnqe1urLVOV4tn0YgmnIw',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  73 => 
  array (
    'id' => 2223,
    'spotify_id' => '1NuvCcuRUGN54bkSLk51LC',
    'title' => 'Melompat Lebih Tinggi',
    'artist' => 'Lomba Sihir',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273566dc9e464e2daa1b8b542ec',
    'meaning' => 'Lagu "Melompat Lebih Tinggi" karya Lomba Sihir mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1NuvCcuRUGN54bkSLk51LC',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  74 => 
  array (
    'id' => 2224,
    'spotify_id' => '6H7lvP0NgAF39Rn3qve4Og',
    'title' => 'Melawan Restu',
    'artist' => 'Mahalini',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2736f713eb92ebf7ca05a562542',
    'meaning' => 'Lagu "Melawan Restu" karya Mahalini mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6H7lvP0NgAF39Rn3qve4Og',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  75 => 
  array (
    'id' => 2225,
    'spotify_id' => '2wYSoFMpRyNzPg7ykw9fyn',
    'title' => 'Melepasmu - New Version',
    'artist' => 'Drive',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273cfc2611fcb32c35858b6c479',
    'meaning' => 'Keberanian dan keikhlasan hati untuk merelakan sosok kekasih pergi ketika menyadari jiwanya tak lagi ada untuk kita.',
    'spotify_url' => 'https://open.spotify.com/track/2wYSoFMpRyNzPg7ykw9fyn',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  76 => 
  array (
    'id' => 2226,
    'spotify_id' => '1kEVqYA0JMm0qKQqykm7gE',
    'title' => 'méli-mélo',
    'artist' => 'kulturr',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27378901c947287e59fb0c5ae85',
    'meaning' => 'Lagu "méli-mélo" karya kulturr mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1kEVqYA0JMm0qKQqykm7gE',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  77 => 
  array (
    'id' => 2227,
    'spotify_id' => '5Y8C6KjzBRKvcT3Aln1Bc4',
    'title' => 'melodrama',
    'artist' => 'disiz, Theodora',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ee5f01b81fd02d6b2dbd70c5',
    'meaning' => 'Lagu "melodrama" karya disiz, Theodora mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5Y8C6KjzBRKvcT3Aln1Bc4',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  78 => 
  array (
    'id' => 2232,
    'spotify_id' => '5oawnHJTadFBnI2SVSKhnf',
    'title' => 'Melewatkanmu',
    'artist' => 'Adera',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f2dcbff793a8e4ba321e2fa7',
    'meaning' => 'Lagu "Melewatkanmu" karya Adera mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5oawnHJTadFBnI2SVSKhnf',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
  79 => 
  array (
    'id' => 2233,
    'spotify_id' => '4d6CbSFdqoeRAWw4ThnNZI',
    'title' => 'MELEPAS LAJANG',
    'artist' => 'Arvian Dwi',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e4f19a917e20e8a20ee3ed9d',
    'meaning' => 'Lagu "MELEPAS LAJANG" karya Arvian Dwi mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/4d6CbSFdqoeRAWw4ThnNZI',
    'preview_url' => NULL,
    'created_at' => '2026-08-05 11:30:53',
  ),
);
$allLocalSongs = [];
$allMessages = [];
require __DIR__ . '/migration_common.php';
?>
