<?php
$batchNum = 2;
$isLastBatch = false;
$batchSongs = array (
  0 => 
  array (
    'id' => 879,
    'spotify_id' => '2zZZQM87GupPuk78UofvFr',
    'title' => 'Maafkan',
    'artist' => 'D\'Bagindas',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b5c19d4252c41b9dec17664b',
    'meaning' => 'Lagu "Maafkan" karya D\'Bagindas mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/2zZZQM87GupPuk78UofvFr',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  1 => 
  array (
    'id' => 880,
    'spotify_id' => '3CBxVM0zGj41BQtE6m7gwb',
    'title' => 'Membasuh',
    'artist' => 'Hindia, Rara Sekar',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d623688488865906052ef96b',
    'meaning' => 'Lagu "Membasuh" karya Hindia, Rara Sekar mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3CBxVM0zGj41BQtE6m7gwb',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  2 => 
  array (
    'id' => 881,
    'spotify_id' => '1qbmS6ep2hbBRaEZFpn7BX',
    'title' => 'Man I Need',
    'artist' => 'Olivia Dean',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e3d69e17dde129037a1f09e2',
    'meaning' => 'Lagu "Man I Need" karya Olivia Dean mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1qbmS6ep2hbBRaEZFpn7BX',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  3 => 
  array (
    'id' => 882,
    'spotify_id' => '003vvx7Niy0yvhvHt4a68B',
    'title' => 'Mr. Brightside',
    'artist' => 'The Killers',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273ccdddd46119a4ff53eaf1f5d',
    'meaning' => 'Lagu "Mr. Brightside" karya The Killers mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  4 => 
  array (
    'id' => 883,
    'spotify_id' => '0wULafSHeHYZFu54R9ZFRJ',
    'title' => 'Mangu',
    'artist' => 'Fourtwnty, Charita Utami',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273fecb2b49d97ed68528fbf44a',
    'meaning' => 'Lagu "Mangu" karya Fourtwnty, Charita Utami mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0wULafSHeHYZFu54R9ZFRJ',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  5 => 
  array (
    'id' => 885,
    'spotify_id' => '3JkDuxcnIzBUngCk6peKZi',
    'title' => 'Magnolia',
    'artist' => 'Magnolia Celebration',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a1747c65e8a8dffde09ab201',
    'meaning' => 'Lagu "Magnolia" karya Magnolia Celebration mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3JkDuxcnIzBUngCk6peKZi',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  6 => 
  array (
    'id' => 886,
    'spotify_id' => '5cCZ0z71pleBJTPLrHCfNx',
    'title' => 'Mantan Terindah',
    'artist' => 'Kahitna',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c657a717d8957efe80692cb5',
    'meaning' => 'Lagu "Mantan Terindah" karya Kahitna mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5cCZ0z71pleBJTPLrHCfNx',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  7 => 
  array (
    'id' => 887,
    'spotify_id' => '3TTZfjYqhTowNALncAmY5v',
    'title' => 'Masa ini, Nanti, dan Masa Indah Lainnya',
    'artist' => 'Nuca',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27372efdd27a433732ba1ab6269',
    'meaning' => 'Lagu "Masa ini, Nanti, dan Masa Indah Lainnya" karya Nuca mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3TTZfjYqhTowNALncAmY5v',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  8 => 
  array (
    'id' => 888,
    'spotify_id' => '1wE4Iqv0tXXuZBA67PoGvw',
    'title' => 'Mantan Terindah',
    'artist' => 'Yovie Widianto, Raisa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27395f411458f0d6ee98424bf6c',
    'meaning' => 'Lagu "Mantan Terindah" karya Yovie Widianto, Raisa mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1wE4Iqv0tXXuZBA67PoGvw',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  9 => 
  array (
    'id' => 889,
    'spotify_id' => '2mLf64m2bZd78XSRa26gU1',
    'title' => 'Mardua Holong',
    'artist' => 'Omega Trio',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273db9a97a555bfa828dc1d062b',
    'meaning' => 'Lagu "Mardua Holong" karya Omega Trio mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2mLf64m2bZd78XSRa26gU1',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  10 => 
  array (
    'id' => 891,
    'spotify_id' => '22l7ocwYpEYGvYpM9T2C5K',
    'title' => 'maggots for brains',
    'artist' => 'Olivia Rodrigo',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735cf234eeb7a2edf44bf64a46',
    'meaning' => 'Lagu "maggots for brains" karya Olivia Rodrigo mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/22l7ocwYpEYGvYpM9T2C5K',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  11 => 
  array (
    'id' => 892,
    'spotify_id' => '4Ilw2lD6z4WBqh65vUUZUf',
    'title' => 'my way',
    'artist' => 'Olivia Rodrigo',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735cf234eeb7a2edf44bf64a46',
    'meaning' => 'Refleksi perjalanan hidup yang dijalani dengan keteguhan hati, keberanian, dan tanpa penyesalan atas setiap pilihan.',
    'spotify_url' => 'https://open.spotify.com/track/4Ilw2lD6z4WBqh65vUUZUf',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  12 => 
  array (
    'id' => 895,
    'spotify_id' => '5JgvmTyhUCPlmaK1jIJA82',
    'title' => 'Maafkan',
    'artist' => 'Slank',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734dbac846068b0573d3ffed86',
    'meaning' => 'Lagu "Maafkan" karya Slank mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5JgvmTyhUCPlmaK1jIJA82',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  13 => 
  array (
    'id' => 896,
    'spotify_id' => '4AqCVi8nDgzUrLvd4cc3RK',
    'title' => 'Maafkan',
    'artist' => 'D\'Bagindas',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732d3484671f0c4b5d3d5e11ad',
    'meaning' => 'Lagu "Maafkan" karya D\'Bagindas mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/4AqCVi8nDgzUrLvd4cc3RK',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  14 => 
  array (
    'id' => 897,
    'spotify_id' => '5geyymsUN6XdGXgoOezm1Y',
    'title' => 'Maafkan',
    'artist' => 'D\'Bagindas',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27305b529f8012a5f8c3a25f72d',
    'meaning' => 'Lagu "Maafkan" karya D\'Bagindas mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5geyymsUN6XdGXgoOezm1Y',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  15 => 
  array (
    'id' => 898,
    'spotify_id' => '4g3dMjHvSSnnG8hupD4SSv',
    'title' => 'Terbaik Untukmu',
    'artist' => 'Tangga',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735573730fe792fc1f86e14038',
    'meaning' => 'Lagu "Terbaik Untukmu" karya Tangga mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4g3dMjHvSSnnG8hupD4SSv',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  16 => 
  array (
    'id' => 899,
    'spotify_id' => '40DrRYTkZ1WnLlrktM6XXH',
    'title' => 'Maafkan Aku - Cover The Orion',
    'artist' => 'Indah Yastami',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27322d96b976bf1d7f8197ec9db',
    'meaning' => 'Lagu "Maafkan Aku - Cover The Orion" karya Indah Yastami mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/40DrRYTkZ1WnLlrktM6XXH',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  17 => 
  array (
    'id' => 900,
    'spotify_id' => '64KxZ9K8PYSQ9CVimLlqxK',
    'title' => 'Mashooqa - From “Cocktail 2”',
    'artist' => 'Pritam, Mahmood, Raghav Chaitanya, Amitabh Bhattacharya, Ruaa Kayy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273bd164e3bbec608aedda85a22',
    'meaning' => 'Lagu "Mashooqa - From “Cocktail 2”" karya Pritam, Mahmood, Raghav Chaitanya, Amitabh Bhattacharya, Ruaa Kayy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/64KxZ9K8PYSQ9CVimLlqxK',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  18 => 
  array (
    'id' => 902,
    'spotify_id' => '7KfaBqVsLdG6AtqHTtX36g',
    'title' => 'MATCHA',
    'artist' => 'Los Dareyes De La Sierra',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733bc78f16328cc9ebef1b4010',
    'meaning' => 'Lagu "MATCHA" karya Los Dareyes De La Sierra mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7KfaBqVsLdG6AtqHTtX36g',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  19 => 
  array (
    'id' => 906,
    'spotify_id' => '2SscarnRY3zdkORvPu9JGZ',
    'title' => 'Demi Cinta',
    'artist' => 'Kerispatih',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273899fb8089df3acdc70fc2459',
    'meaning' => 'Lagu "Demi Cinta" karya Kerispatih mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/2SscarnRY3zdkORvPu9JGZ',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  20 => 
  array (
    'id' => 908,
    'spotify_id' => '26KhLgFuPymkm1uiZkc6Rv',
    'title' => 'Bunga Maaf',
    'artist' => 'The Lantis',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737536908067a37708c3f5ff35',
    'meaning' => 'Lagu "Bunga Maaf" karya The Lantis mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/26KhLgFuPymkm1uiZkc6Rv',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  21 => 
  array (
    'id' => 912,
    'spotify_id' => '5eEiZIdpEABlGLuNmZr7KS',
    'title' => 'Maafkan Aku #terlanjurmencinta',
    'artist' => 'Tiara Andini',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273937d621f0025409ee44285d1',
    'meaning' => 'Lagu "Maafkan Aku #terlanjurmencinta" karya Tiara Andini mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/5eEiZIdpEABlGLuNmZr7KS',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:17',
  ),
  22 => 
  array (
    'id' => 933,
    'spotify_id' => '0fpv8aNzuhHfD3Nssc3mwT',
    'title' => 'Argata',
    'artist' => 'Romi Jahat, Nully',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d3335f7094c28e37498e4dee',
    'meaning' => 'Lagu "Argata" karya Romi Jahat, Nully mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0fpv8aNzuhHfD3Nssc3mwT',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  23 => 
  array (
    'id' => 934,
    'spotify_id' => '20jbSiX29FDX4oQxBXyUEi',
    'title' => 'hate that i made you love me',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b622d42c30697e1e1414343c',
    'meaning' => 'Lagu "hate that i made you love me" karya Ariana Grande mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/20jbSiX29FDX4oQxBXyUEi',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  24 => 
  array (
    'id' => 935,
    'spotify_id' => '7rwScNq2fq2taw6S3tgXA0',
    'title' => 'لو تسمح يا هوى',
    'artist' => 'كامل ايهاب',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739ff3490a90fea7a97183d628',
    'meaning' => 'Lagu "لو تسمح يا هوى" karya كامل ايهاب mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7rwScNq2fq2taw6S3tgXA0',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  25 => 
  array (
    'id' => 936,
    'spotify_id' => '2MIpkAQVJqQIDf9k4YWoHR',
    'title' => 'past life',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735ab3c842fde848df7a4ee6d9',
    'meaning' => 'Lagu "past life" karya Ariana Grande mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/2MIpkAQVJqQIDf9k4YWoHR',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  26 => 
  array (
    'id' => 937,
    'spotify_id' => '1Rweq7vNjK4kZBbGrmxQsl',
    'title' => 'bye',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738b58d20f1b77295730db15b4',
    'meaning' => 'Lagu "bye" karya Ariana Grande mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1Rweq7vNjK4kZBbGrmxQsl',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  27 => 
  array (
    'id' => 938,
    'spotify_id' => '22Nd3GuO7sHopPjdKccRcq',
    'title' => 'An Art Gallery Could Never Be As Unique As You',
    'artist' => 'mrld',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27323f9a7469fb98e80e4ffdf42',
    'meaning' => 'Lagu "An Art Gallery Could Never Be As Unique As You" karya mrld mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/22Nd3GuO7sHopPjdKccRcq',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  28 => 
  array (
    'id' => 939,
    'spotify_id' => '33HagC36ZDbYVqoc9ud6vm',
    'title' => 'Aku Harus Pergi',
    'artist' => 'Whisnu Santika, Ari Lesmana',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e2b65198e6a3093d52037bb6',
    'meaning' => 'Lagu "Aku Harus Pergi" karya Whisnu Santika, Ari Lesmana mengekspresikan kepedihan hati, rasa kehilangan, serta proses merelakan seseorang yang pernah menjadi bagian terpenting dalam hidup.',
    'spotify_url' => 'https://open.spotify.com/track/33HagC36ZDbYVqoc9ud6vm',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  29 => 
  array (
    'id' => 940,
    'spotify_id' => '1WbTgUs0MsUqDBKInVfxwF',
    'title' => 'Art of Guitar',
    'artist' => 'Marcin, RJ Pasin',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733f412f0952db2d442a35a5c3',
    'meaning' => 'Lagu "Art of Guitar" karya Marcin, RJ Pasin mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1WbTgUs0MsUqDBKInVfxwF',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  30 => 
  array (
    'id' => 941,
    'spotify_id' => '46kspZSY3aKmwQe7O77fCC',
    'title' => 'we can\'t be friends (wait for your love)',
    'artist' => 'Ariana Grande',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c75a14e746ffe2030e8cd5da',
    'meaning' => 'Lagu "we can\'t be friends (wait for your love)" karya Ariana Grande mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/46kspZSY3aKmwQe7O77fCC',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  31 => 
  array (
    'id' => 942,
    'spotify_id' => '6J3MMMLXdC6iUiwxVegJ6V',
    'title' => 'An Art Gallery Could Never Be As Unique As You - In Bahasa',
    'artist' => 'mrld',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273068a0bc118a20822f9dc0d7c',
    'meaning' => 'Lagu "An Art Gallery Could Never Be As Unique As You - In Bahasa" karya mrld mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6J3MMMLXdC6iUiwxVegJ6V',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  32 => 
  array (
    'id' => 944,
    'spotify_id' => '03fkIoNyruY4N2Pa5CqTvv',
    'title' => 'Astaga Bercanda',
    'artist' => 'Akbar Chalay, Mingse',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273db45ed33946536fd099548b0',
    'meaning' => 'Lagu "Astaga Bercanda" karya Akbar Chalay, Mingse mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/03fkIoNyruY4N2Pa5CqTvv',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  33 => 
  array (
    'id' => 945,
    'spotify_id' => '1swCJuTvL9tx2IjQKRcsYq',
    'title' => 'Arti Hidup',
    'artist' => 'Raim Laode',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a9d1f9b5d3275b0625e13e79',
    'meaning' => 'Lagu "Arti Hidup" karya Raim Laode mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1swCJuTvL9tx2IjQKRcsYq',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  34 => 
  array (
    'id' => 946,
    'spotify_id' => '1bMkimTb47umgNP6xCi4A1',
    'title' => 'Arz Kiya Hai | Coke Studio Bharat',
    'artist' => 'Anuv Jain',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27325fa2d19b2363a9520a34409',
    'meaning' => 'Lagu "Arz Kiya Hai | Coke Studio Bharat" karya Anuv Jain mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1bMkimTb47umgNP6xCi4A1',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  35 => 
  array (
    'id' => 947,
    'spotify_id' => '5JESuE80fvausWHjcT9QVh',
    'title' => 'Aku Milikmu',
    'artist' => 'Dewa 19',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273bfc7fa507f4bc822cabe7bde',
    'meaning' => 'Lagu "Aku Milikmu" karya Dewa 19 mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/5JESuE80fvausWHjcT9QVh',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  36 => 
  array (
    'id' => 948,
    'spotify_id' => '6mcMQf9In1QxHefreIxUCD',
    'title' => 'Art Gallery',
    'artist' => 'Music4video',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f6c56db7dfb8e414d65676c3',
    'meaning' => 'Lagu "Art Gallery" karya Music4video mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6mcMQf9In1QxHefreIxUCD',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  37 => 
  array (
    'id' => 949,
    'spotify_id' => '1LDYaddflYM0ht2DnSLS4s',
    'title' => 'Arteri',
    'artist' => '.Feast',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c800b90e2092a5328f699117',
    'meaning' => 'Lagu "Arteri" karya .Feast mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1LDYaddflYM0ht2DnSLS4s',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  38 => 
  array (
    'id' => 951,
    'spotify_id' => '5TxRUOsGeWeRl3xOML59Ai',
    'title' => 'ARE WE STILL FRIENDS?',
    'artist' => 'Tyler, The Creator',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27330a635de2bb0caa4e26f6abb',
    'meaning' => 'Lagu "ARE WE STILL FRIENDS?" karya Tyler, The Creator mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5TxRUOsGeWeRl3xOML59Ai',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  39 => 
  array (
    'id' => 952,
    'spotify_id' => '3hEfpBHxgieRLz4t3kLNEg',
    'title' => 'About You',
    'artist' => 'The 1975',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27300702474f8e0e2b6155d48e3',
    'meaning' => 'Perasaan nostalgia mendalam di mana setiap sudut kehidupan dan bayangan kenangan selalu mengingatkan pada satu sosok yang tak pernah benar-benar pergi dari ingatan.',
    'spotify_url' => 'https://open.spotify.com/track/3hEfpBHxgieRLz4t3kLNEg',
    'preview_url' => 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/d0/8c/64/d08c6440-e727-10ab-589c-e36d5afea47e/mzaf_15879604028025493401.plus.aac.p.m4a',
    'created_at' => '2026-08-04 10:11:40',
  ),
  40 => 
  array (
    'id' => 953,
    'spotify_id' => '3Jy0dWV5AnnfyTvHK6UWof',
    'title' => 'Bright Eyes',
    'artist' => 'Art Garfunkel',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273597ed58e677b46451320f711',
    'meaning' => 'Lagu "Bright Eyes" karya Art Garfunkel mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3Jy0dWV5AnnfyTvHK6UWof',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  41 => 
  array (
    'id' => 954,
    'spotify_id' => '4255amV4enzl28KAn16rUO',
    'title' => 'Are You With Me',
    'artist' => 'Lost Frequencies',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c01ab1c4b2dceb2cfc89e6fa',
    'meaning' => 'Lagu "Are You With Me" karya Lost Frequencies mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4255amV4enzl28KAn16rUO',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  42 => 
  array (
    'id' => 955,
    'spotify_id' => '5TTGoX70AFrTvuEtqHK37S',
    'title' => 'No. 1 Party Anthem',
    'artist' => 'Arctic Monkeys',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734ae1c4c5c45aabe565499163',
    'meaning' => 'Lagu "No. 1 Party Anthem" karya Arctic Monkeys mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5TTGoX70AFrTvuEtqHK37S',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  43 => 
  array (
    'id' => 958,
    'spotify_id' => '6l8EbYRtQMgKOyc1gcDHF9',
    'title' => 'Bridge Over Troubled Water',
    'artist' => 'Simon & Garfunkel',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2738453b853c2cc9c077828eefb',
    'meaning' => 'Lagu "Bridge Over Troubled Water" karya Simon & Garfunkel mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6l8EbYRtQMgKOyc1gcDHF9',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  44 => 
  array (
    'id' => 959,
    'spotify_id' => '0BxE4FqsDD1Ot4YuBXwAPp',
    'title' => '505',
    'artist' => 'Arctic Monkeys',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b1f8da74f225fa1225cdface',
    'meaning' => 'Lagu "505" karya Arctic Monkeys mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  45 => 
  array (
    'id' => 960,
    'spotify_id' => '3vkQ5DAB1qQMYO4Mr9zJN6',
    'title' => 'Gimme! Gimme! Gimme! (A Man After Midnight)',
    'artist' => 'ABBA',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273aa22899360d8ba6704732dec',
    'meaning' => 'Lagu "Gimme! Gimme! Gimme! (A Man After Midnight)" karya ABBA membawa nuansa kerinduan hangat dan nostalgia akan kenangan indah bersama seseorang yang selalu bernaung di dalam pikiran.',
    'spotify_url' => 'https://open.spotify.com/track/3vkQ5DAB1qQMYO4Mr9zJN6',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  46 => 
  array (
    'id' => 962,
    'spotify_id' => '1BLfQ6dPXmuDrFmbdfW7Jl',
    'title' => 'A Little Piece of Heaven',
    'artist' => 'Avenged Sevenfold',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27333c52ca8309741c6999ca742',
    'meaning' => 'Lagu "A Little Piece of Heaven" karya Avenged Sevenfold mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1BLfQ6dPXmuDrFmbdfW7Jl',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  47 => 
  array (
    'id' => 963,
    'spotify_id' => '6g8cuDwreIt5rLEBlkukQa',
    'title' => 'Ghetto Love Story',
    'artist' => 'BabyChiefDoit',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27364d676141052c2e389c0b7b3',
    'meaning' => 'Lagu "Ghetto Love Story" karya BabyChiefDoit mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/6g8cuDwreIt5rLEBlkukQa',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  48 => 
  array (
    'id' => 964,
    'spotify_id' => '5FVd6KXrgO9B3JPmC8OPst',
    'title' => 'Do I Wanna Know?',
    'artist' => 'Arctic Monkeys',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2734ae1c4c5c45aabe565499163',
    'meaning' => 'Lagu "Do I Wanna Know?" karya Arctic Monkeys mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5FVd6KXrgO9B3JPmC8OPst',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  49 => 
  array (
    'id' => 966,
    'spotify_id' => '6bK9BH9Ts8Gj5JFvnQkzak',
    'title' => 'Get Busy',
    'artist' => 'Sean Paul',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b85a43ff52cecb0ab0a49677',
    'meaning' => 'Lagu "Get Busy" karya Sean Paul mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6bK9BH9Ts8Gj5JFvnQkzak',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  50 => 
  array (
    'id' => 967,
    'spotify_id' => '40ds3xedbMkWhszkGnZwxi',
    'title' => 'ART',
    'artist' => 'Tyla',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733b4e7b8d3e6d063692406021',
    'meaning' => 'Ungkapan ketulusan hati yang menyerahkan seluruh cinta dan kehangatan kepada pasangan tanpa syarat.',
    'spotify_url' => 'https://open.spotify.com/track/40ds3xedbMkWhszkGnZwxi',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  51 => 
  array (
    'id' => 968,
    'spotify_id' => '4dtP86vkhzwNXCFpCtizce',
    'title' => 'Secret Door',
    'artist' => 'Arctic Monkeys',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273f65d720a5d70dbb93e96d528',
    'meaning' => 'Lagu "Secret Door" karya Arctic Monkeys mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4dtP86vkhzwNXCFpCtizce',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  52 => 
  array (
    'id' => 969,
    'spotify_id' => '4Dvkj6JhhA12EX05fT7y2e',
    'title' => 'As It Was',
    'artist' => 'Harry Styles',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27382ce362511fb3d9dda6578ee',
    'meaning' => 'Lagu "As It Was" karya Harry Styles mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4Dvkj6JhhA12EX05fT7y2e',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  53 => 
  array (
    'id' => 971,
    'spotify_id' => '1eUtfbmI6Qq7Oj6okQ2ktT',
    'title' => 'Scarborough Fair / Canticle',
    'artist' => 'Simon & Garfunkel',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732614432efb0aabf969870646',
    'meaning' => 'Lagu "Scarborough Fair / Canticle" karya Simon & Garfunkel mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1eUtfbmI6Qq7Oj6okQ2ktT',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  54 => 
  array (
    'id' => 972,
    'spotify_id' => '54OJB29vohgBFBM8sHCJeB',
    'title' => 'Arti Cinta',
    'artist' => 'Ari Lasso',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273aed326ff35ac92563f8d12de',
    'meaning' => 'Lagu "Arti Cinta" karya Ari Lasso mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/54OJB29vohgBFBM8sHCJeB',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  55 => 
  array (
    'id' => 973,
    'spotify_id' => '3hUxzQpSfdDqwM3ZTFQY0K',
    'title' => 'august',
    'artist' => 'Taylor Swift',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27395f754318336a07e85ec59bc',
    'meaning' => 'Lagu "august" karya Taylor Swift mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3hUxzQpSfdDqwM3ZTFQY0K',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  56 => 
  array (
    'id' => 975,
    'spotify_id' => '6sGIMrtIzQjdzNndVxe397',
    'title' => 'So Easy (To Fall In Love)',
    'artist' => 'Olivia Dean',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2739a336bfb6d40bbd90a507417',
    'meaning' => 'Lagu "So Easy (To Fall In Love)" karya Olivia Dean mengisahkan tentang ketulusan cinta mendalam, rasa syukur atas kehadiran pasangan, dan kehangatan yang mengikat dua jiwa.',
    'spotify_url' => 'https://open.spotify.com/track/6sGIMrtIzQjdzNndVxe397',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  57 => 
  array (
    'id' => 977,
    'spotify_id' => '5jqNQZBwbZWQXPWfo0ygZF',
    'title' => 'Art Deco',
    'artist' => 'Lana Del Rey',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a3b3f48ca81acacb3ad4ec8a',
    'meaning' => 'Lagu "Art Deco" karya Lana Del Rey mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5jqNQZBwbZWQXPWfo0ygZF',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  58 => 
  array (
    'id' => 978,
    'spotify_id' => '3fF0696fsyJP7zXqhQ7GLC',
    'title' => 'Atmospheric White Noise',
    'artist' => 'Abstract Time',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2733dbc5461983d7e23f20b8f53',
    'meaning' => 'Lagu "Atmospheric White Noise" karya Abstract Time mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3fF0696fsyJP7zXqhQ7GLC',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  59 => 
  array (
    'id' => 979,
    'spotify_id' => '5YBxGJYKJ7Se2Uq7S0pVOL',
    'title' => 'Art House',
    'artist' => 'Malcolm Todd',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2732c1f34ecc1929fb59908aad1',
    'meaning' => 'Lagu "Art House" karya Malcolm Todd mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5YBxGJYKJ7Se2Uq7S0pVOL',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  60 => 
  array (
    'id' => 980,
    'spotify_id' => '5fnOrhQ4KgT5irGCjIccGH',
    'title' => 'Arthur\'s Theme (Best That You Can Do)',
    'artist' => 'Christopher Cross',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273b00a6721828724ce38a1e7a3',
    'meaning' => 'Lagu "Arthur\'s Theme (Best That You Can Do)" karya Christopher Cross mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5fnOrhQ4KgT5irGCjIccGH',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  61 => 
  array (
    'id' => 981,
    'spotify_id' => '0bSlEreR3f5j8DlEc17QqI',
    'title' => 'Game Six',
    'artist' => 'BabyChiefDoit',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27323e3ff515be13d401a9a5a1a',
    'meaning' => 'Lagu "Game Six" karya BabyChiefDoit mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0bSlEreR3f5j8DlEc17QqI',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  62 => 
  array (
    'id' => 982,
    'spotify_id' => '6cDuRZUowDthOJoefs3pdX',
    'title' => 'Arti Kehidupan',
    'artist' => 'Mus Mujiono',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e18b24b054142756ecfce7e1',
    'meaning' => 'Lagu "Arti Kehidupan" karya Mus Mujiono mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6cDuRZUowDthOJoefs3pdX',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  63 => 
  array (
    'id' => 986,
    'spotify_id' => '0cs5ZCMwIiwKs1hICB5Jgt',
    'title' => 'Art Gal',
    'artist' => 'Madd Family',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d1462278b8ca2ede6a7e6d64',
    'meaning' => 'Lagu "Art Gal" karya Madd Family mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0cs5ZCMwIiwKs1hICB5Jgt',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  64 => 
  array (
    'id' => 987,
    'spotify_id' => '3y13QK2mrE3J9xd3ittANF',
    'title' => 'Art Gallery',
    'artist' => 'Love You Later',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a0b814c229e4d097087b8343',
    'meaning' => 'Lagu "Art Gallery" karya Love You Later mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3y13QK2mrE3J9xd3ittANF',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  65 => 
  array (
    'id' => 988,
    'spotify_id' => '0XwCPIPmMhuaoJmgDnpKSH',
    'title' => 'An Art Gallery Could Never Be as Magnificent as You',
    'artist' => 'Scruffpuppie',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273437aaef8cd5c6b203631b003',
    'meaning' => 'Lagu "An Art Gallery Could Never Be as Magnificent as You" karya Scruffpuppie mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0XwCPIPmMhuaoJmgDnpKSH',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  66 => 
  array (
    'id' => 990,
    'spotify_id' => '0gHZoc1QKI2kKV0QSmVxA9',
    'title' => 'Gagal Diet',
    'artist' => 'ArumtaLa',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273352d234b3d10393e7101c5d2',
    'meaning' => 'Lagu "Gagal Diet" karya ArumtaLa mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0gHZoc1QKI2kKV0QSmVxA9',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  67 => 
  array (
    'id' => 991,
    'spotify_id' => '0SGcJpFys6vSrSMPMpMBdC',
    'title' => 'Arti Kehidupan',
    'artist' => 'Coldiac',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2735f499e3bcfb7d76a7a7efb65',
    'meaning' => 'Lagu "Arti Kehidupan" karya Coldiac mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0SGcJpFys6vSrSMPMpMBdC',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:11:40',
  ),
  68 => 
  array (
    'id' => 1014,
    'spotify_id' => '6HaYwC9sUWfS9wJXJiR2hi',
    'title' => 'An Art Gallery Could Never Be As Unique As You',
    'artist' => 'mrld',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273e4192809974d7f11a318eb24',
    'meaning' => 'Lagu "An Art Gallery Could Never Be As Unique As You" karya mrld mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/6HaYwC9sUWfS9wJXJiR2hi',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:13:42',
  ),
  69 => 
  array (
    'id' => 1016,
    'spotify_id' => '4TcOggZWxVDajZQ803obGc',
    'title' => 'an art gallery could never be as beautiful as you - Original',
    'artist' => 'scribbletest',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273eb6f1effe027e2fe90da5d79',
    'meaning' => 'Lagu "an art gallery could never be as beautiful as you - Original" karya scribbletest mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/4TcOggZWxVDajZQ803obGc',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:13:42',
  ),
  70 => 
  array (
    'id' => 1019,
    'spotify_id' => '3vbWTjD7JWwhfuXExEI7TK',
    'title' => 'The Art Of Natural Dy(e)ing',
    'artist' => 'Amukredam',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27319e81767ffc4b2485d53d211',
    'meaning' => 'Lagu "The Art Of Natural Dy(e)ing" karya Amukredam mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3vbWTjD7JWwhfuXExEI7TK',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:13:42',
  ),
  71 => 
  array (
    'id' => 1020,
    'spotify_id' => '7ChJumjmPtJA23vgjncoZ9',
    'title' => 'Art Museum',
    'artist' => 'RIO',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2730e0796ebc3440a27d0b45ff2',
    'meaning' => 'Lagu "Art Museum" karya RIO mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/7ChJumjmPtJA23vgjncoZ9',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:13:42',
  ),
  72 => 
  array (
    'id' => 1021,
    'spotify_id' => '17e10lopWkvXRttxvzIRo9',
    'title' => 'Mr. Showtime (feat. 天馬司&鳳えむ&草薙寧々&神代類&巡音ルカ)',
    'artist' => 'ワンダーランズ×ショウタイム',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273d6787f7647bbad746d4e7a8c',
    'meaning' => 'Lagu "Mr. Showtime (feat. 天馬司&鳳えむ&草薙寧々&神代類&巡音ルカ)" karya ワンダーランズ×ショウタイム mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/17e10lopWkvXRttxvzIRo9',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:13:42',
  ),
  73 => 
  array (
    'id' => 1050,
    'spotify_id' => '1sVQuuvFDKu6vklPVeiUXT',
    'title' => 'Dunia Yang Nanti',
    'artist' => 'Raim Laode',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273a9d1f9b5d3275b0625e13e79',
    'meaning' => 'Lagu "Dunia Yang Nanti" karya Raim Laode mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1sVQuuvFDKu6vklPVeiUXT',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
  74 => 
  array (
    'id' => 1052,
    'spotify_id' => '0kosUz0jePvjiz4ctmR6wL',
    'title' => 'Dai Dai',
    'artist' => 'Shakira, Burna Boy',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27303cadf1b3fe324c1dc710ed4',
    'meaning' => 'Lagu "Dai Dai" karya Shakira, Burna Boy mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/0kosUz0jePvjiz4ctmR6wL',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
  75 => 
  array (
    'id' => 1054,
    'spotify_id' => '1MdjZzEInrmDBXf8zs0nKS',
    'title' => 'Dan...',
    'artist' => 'Sheila On 7',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27354270208627aa8061a8abe21',
    'meaning' => 'Lagu "Dan..." karya Sheila On 7 mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1MdjZzEInrmDBXf8zs0nKS',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
  76 => 
  array (
    'id' => 1055,
    'spotify_id' => '1sDHHLFY06AFKR2X722wIf',
    'title' => 'Dengarlah Bintang Hatiku',
    'artist' => 'Demeises',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b2737f4a679d2bb8d30b4457575f',
    'meaning' => 'Lagu "Dengarlah Bintang Hatiku" karya Demeises mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/1sDHHLFY06AFKR2X722wIf',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
  77 => 
  array (
    'id' => 1056,
    'spotify_id' => '5VyWqCgmRSa1o364B4UGI8',
    'title' => 'Disarankan di Bandung',
    'artist' => 'Dongker, Jason Ranti',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b27335e8c95e427167c4d26899e1',
    'meaning' => 'Lagu "Disarankan di Bandung" karya Dongker, Jason Ranti mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5VyWqCgmRSa1o364B4UGI8',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
  78 => 
  array (
    'id' => 1057,
    'spotify_id' => '5yvVYFDUpbnjcnRBgjwTzM',
    'title' => 'Dracula - JENNIE Remix',
    'artist' => 'Tame Impala, JENNIE',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273c7c031ce9d06b131f8563676',
    'meaning' => 'Lagu "Dracula - JENNIE Remix" karya Tame Impala, JENNIE mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/5yvVYFDUpbnjcnRBgjwTzM',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
  79 => 
  array (
    'id' => 1058,
    'spotify_id' => '3sK8wGT43QFpWrvNQsrQya',
    'title' => 'DtMF',
    'artist' => 'Bad Bunny',
    'cover_url' => 'https://i.scdn.co/image/ab67616d0000b273bbd45c8d36e0e045ef640411',
    'meaning' => 'Lagu "DtMF" karya Bad Bunny mengabadikan perasaan emosional yang mendalam, menyampaikan pesan rahasia yang sulit diucapkan dengan kata-kata biasa.',
    'spotify_url' => 'https://open.spotify.com/track/3sK8wGT43QFpWrvNQsrQya',
    'preview_url' => NULL,
    'created_at' => '2026-08-04 10:15:02',
  ),
);
$allLocalSongs = [];
$allMessages = [];
require __DIR__ . '/migration_common.php';
?>
